### ISSUE TITLE
GUI changes in settings are not instantly applied

### ISSUE THREAD

**Issue by oliexdev** [oliexdev/openScale#10]
Currently GUI changes in settings are not instantly applied. You have to restart the app or switch several time between the three sub fragments to update a GUI fragment.

**Comment by nastynabz** [comment]
Hello,
I want to try to fix this issue.
I have an idea to fix it.

**Comment by oliexdev** [comment]
Hi nastynabz,

that would be great. Please create a pull request with your code changes.

Best regards
oli

**Comment by oliexdev** [comment]
thanks to nastynabz the bug is fixed, see pull request #19.
