### ISSUE TITLE
smarter user assignment.

### ISSUE THREAD

**Issue by FransM** [oliexdev/openScale#1004]
**Is your feature request related to a problem? Please describe.**
If two users are about the same weight with smart user a measurement might be added to the wrong user.

**Describe the solution you'd like**
An improvement of the user matching algorithm that also takes other available data into account (e.g. impedance)

**Describe alternatives you've considered**
none

**Comment by oliexdev** [comment]
not every scale has an impedance available and so on.

**Comment by FransM** [comment]
Sure, but still it could be used if available
