### ISSUE TITLE
option to reject incomplete measurements

### ISSUE THREAD

**Issue by FransM** [oliexdev/openScale#1005]
**Is your feature request related to a problem? Please describe.**
My scale weighs and afterwards measures impedance. If the scale is left before the impedance is measured the weight is recorded with impedance 0.

**Describe the solution you'd like**
It would be nice to have an option that, when enabled drops those measurements.

**Describe alternatives you've considered**
none

**Additional context**
This happened to me on the Mi Body Composition Scale 2

**Comment by oliexdev** [comment]
go into settings->bluetooth and turn on smart user assignment and ignore data ...
