### ISSUE TITLE
More user documentation on setting up scales.

### ISSUE THREAD

**Issue by mo-g** [oliexdev/openScale#1015]
**Is your feature request related to a problem? Please describe.**
I bought a Medisana BG444 scale based on the Wiki, but when I added it to the app, I was only getting weight data, not biometric data. It turns out the manual is wrong - it describes the guest profile as "0" when on the scale it's "1". Also, I never read the manual until I had the problem, because I wasn't using their app anyway. Ok, some of this is on me, some of this is on them.

**Describe the solution you'd like**
User-level documentation in the Wiki, or an **optional** "set-up wizard" in the app so that when you want to add a new device, it helps you set it up correctly for use with the app.

**Describe alternatives you've considered**
I could go to Medisana and say "screw your app, just replace your documentation with something telling everyone to go use OpenScale" but honestly that seems less likely.

**Additional context**
I'm very amused that the manual was written by programmers (Profiles 0-7) but the firmware was written by UX designers (1-8).

**Comment by oliexdev** [comment]
you can add that to the wiki but openScale its not only for Medisana scales, it supports a various scales from different vendors. openScale cannot specific for each scale a wizard or a user-level documentation to recover the poorly written scale firmware.
