### ISSUE TITLE
Unable to switch some measurements on

### ISSUE THREAD

**Issue by kir0ul** [oliexdev/openScale#1027]
**Describe the bug**
I'm unable to add some measurements (the body fat caliper and waist-hip ratio, other measurements seems to work fine) to the list of measurements, apparently I'm able to switch on the toggle buttons but the measurements names stay greyed out and are not added to the measurement list that can be logged. Also, nothing happens when the settings/cog button next to the toggle button gets pressed.

**To Reproduce**
1. Go to `Settings > Measurements`
2. Click on `Body fat caliper` or `Waist-hip ratio`, the toggle gets activated, but the name stay greyed out

Reproduced with: v2.5.2 (64)

**Expected behavior**
Click on the toggle button to add the measurement to the list of measurements that can be logged.

**Additional context**
Screenshot of the measurements settings:

<img src="https://github.com/oliexdev/openScale/assets/6053592/83ceed66-0cae-478a-803f-7672b57afc81" width=35%>

Screenshot of the measurements list I can log:

<img src="https://github.com/oliexdev/openScale/assets/6053592/fd558959-4c9c-43b0-bc65-bd6a770c5f8f" width=35%>

**Comment by kir0ul** [comment]
I tried uninstalling and reinstalling, but I still have the same issue.

**Comment by oliexdev** [comment]
You can enable Wait-Hip measurement it if you enable the hip and waist measurment otherwise for the Wait-Hip ratio a measurement is missing, same for the caliper measurment, you need to enable all caliper measurement first.
