### ISSUE TITLE
Could you help me with connecting to Renpho scale with openscale.

### ISSUE THREAD

**Issue by Lakshmi-Narasimhan** [oliexdev/openScale#103]
Am a newbie and am unable to understand reverse engineering renpho scale as this scale is not even pairing with my bluetooth, the scale is connected and  values are shown only on the renpho app.

**Comment by oliexdev** [comment]
Did you try to reverse engineer your scale as described in the [wiki](https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Blueeoth-4.x-scale)?

**Comment by maszek** [comment]
That's a complex process. It's not clear where certain values should be filled in. 
The Bitsnoop log file is not readable:

![btsnoop logfile screenshot_20171129-171507](https://user-images.githubusercontent.com/990963/33385840-e2d677f0-d529-11e7-8a64-165786cb03ea.jpg)

The Open Scale app is searching, but only for a particular type of scale (MI-scale), it seems:

![open scale screenshot_20171129-171238](https://user-images.githubusercontent.com/990963/33385891-04b10c64-d52a-11e7-94d4-5bc02f0dd08f.jpg)

Finally, the method described still requires an app from Google Play (BLE scanner). I want to stay away from that.

P.S. is "Blueeoth" a typing error?

**Comment by oliexdev** [comment]
@maszek you have to open the Bootsnoop log file with [wireshark](https://www.wireshark.org/) 
openScale is searching for default the Mi scale but if you device is not supported then openScale can't connect to your scale.

Maybe they exist another BLE scanner that are open source.

Yeah Blueeoth was of course a typing error thanks for your hint.

**Comment by maszek** [comment]
Okay, I was hoping it would be easier when I read the 'crate of beer' instruction, which is about the level I am able to comprehend.
Good luck developing your app, it looks promising, I'll check in again later.

**Comment by oliexdev** [comment]
ok no problem I will close this issue. Please create a new issue or comment here if you have further questions related to this topic.
