### ISSUE TITLE
Minor dark mode issue

### ISSUE THREAD

**Issue by alexanderadam** [oliexdev/openScale#1038]
**Describe the bug**

Buttons "Ok" and "Cancel" are barely visible in openScale Pro's dark mode.

**To Reproduce**
Steps to reproduce the behaviour:

1. When creating a new user the datepicker for the birthday has black buttons in dark mode

![Screenshot_20240420_102835_openScale](https://github.com/oliexdev/openScale/assets/372620/38233808-ce71-4b24-b8f8-3e2f8c392f10)

**Expected behaviour**

The buttons should be properly visible instead

**Comment by KaushalDoshi** [comment]
Hi, I want to fix this issue. Which color is expected instead of black for buttons?

**Comment by alexanderadam** [comment]
I'm not the maintainer but most probably the same white like the calendar numbers and the pencil icon. Everything has the same colour except the buttons.

**Comment by oliexdev** [comment]
should be finally fixed with the latest dev build.
