### ISSUE TITLE
Script Modification for Wiki "Useful import scripts"

### ISSUE THREAD

**Issue by linuxlurak** [oliexdev/openScale#1044]
**Describe the bug**
On https://github.com/oliexdev/openScale/wiki/Useful-import-scripts your published the script "openScale CSV file --> Garmin format" which won't work with python 3.2 without the following two modifications:
Line 18 from
print "Missing file to transform\n"
to     
print("Missing file to transform\n")

Line 26 (file open mode in byte mode (wb) is wrong) from
with open("openScale_garmin_connect_import.csv", "wb") as outfile, open(sys.argv[1], "r") as infile:
to
with open("openScale_garmin_connect_import.csv", "w") as outfile, open(sys.argv[1], "r") as infile:

Sorry for reporting like this, I didn't have a diff handy in a hurry and didn't realize how to edit wikis.

**Comment by oliexdev** [comment]
thx fixed
