### ISSUE TITLE
Body fat,water etc. extrapolated from average based on research papers instead being calculated from measured impedance level

### ISSUE THREAD

**Issue by nuschpl** [oliexdev/openScale#1045]
**Is your feature request related to a problem? Please describe.**
As per issue #96 :
>  I Implemented body metrics estimations for the body fat, water percentage and body lean weight regarding to published scientific papers. But these are estimations based on your weight, age, sex, height but no impedance values are used for the calculations! I'

This is one of the basic features users of electronic scales like those expect . 

**Describe the solution you'd like**
Impedance based calculation of body fat, water etc. 

IMHO we should keep seperate issue open and make the current state clearly visible for  both for users and developers eager to implement some feature.

**Comment by oliexdev** [comment]
the implemented body metrics estimations are for those who don't have "smart" scales. Each scale has their own impedance based calculation that's why we have so different implementations.
