### ISSUE TITLE
Any way to tell the xiaomi v1 from the v2?

### ISSUE THREAD

**Issue by NastyFlytrap** [oliexdev/openScale#1070]
I went to their website and they look identical but on amazon i see a V2 with four circles and one without four circles. Both advertised as the version 2

**Comment by NastyFlytrap** [comment]
@oliexdev Ok.... So, did anything change? Was any information found out about how to tell them apart, or did you just close the thread so its not bothering you?

**Comment by oliexdev** [comment]
see https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale 
but I am not the vendor of any scales, its better to ask xiaomi or the sellers on amazon what they are selling.
