### ISSUE TITLE
Record raw impedance mesurements

### ISSUE THREAD

**Issue by LoHub** [oliexdev/openScale#1073]
**Is your feature request related to a problem? Please describe.**

I would like to understand how my scale compute measurements.

**Describe the solution you'd like**

Would it be possible to record raw impedance if available? According to this wiki measurements is available.
https://github.com/oliexdev/openScale/wiki/Beurer-Sanitas

**Comment by oliexdev** [comment]
Goto Settings->About and turn on save debug log to file
