### ISSUE TITLE
Override the measurement date and time

### ISSUE THREAD

**Issue by powfagged** [oliexdev/openScale#1085]
Whenever I download my weight measurement, the time (and date) is out by many hours.

One of the best things about openScale is that I don't have to download and register the manufacturers app in order to use my scales. The downside is that my scales haven't set the time and date correctly. This means that each time I use openScale, I need to edit the weight measurement to set the current date and time. It would be useful if there was an option in openScale to override the timestamp with the the phone date and time whenever I download my weight via bluetooth.

**Comment by oliexdev** [comment]
That's not possible you can only ignore those wrong dates in the Bluetooth options
