### ISSUE TITLE
Display Absolute Values for Fat and Muscle Mass in the Chart

### ISSUE THREAD

**Issue by derfloDev** [oliexdev/openScale#1086]
**Description**
It would be highly beneficial if openScale could display absolute values for body fat and muscle mass alongside the current percentage values in the chart. Currently, only the percentage values are available, but not the absolute values in kilograms. Adding this feature would give users a more detailed insight into their body composition and allow them to track changes over time both in percentage and in absolute terms.

**Benefits**
Improved Tracking: Users would be able to directly see changes in their absolute fat and muscle mass, making it easier to monitor their progress.
More Precise Data: Displaying the absolute values would allow for a more accurate interpretation of progress, especially for users focused on weight loss or muscle gain.
Consistency: Many users track their absolute fat and muscle mass values separately, and would appreciate the ability to view them directly in the chart without additional calculations.

**Implementation Suggestion**
Add columns or options in the chart or data table to show absolute values for fat and muscle mass.
Optionally, add a toggle in the chart settings to switch between percentage and absolute values, or to display both simultaneously.

Thank you for considering this suggestion!

**Comment by oliexdev** [comment]
You can do it already, go into->settings->measurements->muscle->click on the setting symbol and turn off the "mesurement in %" option.
