### ISSUE TITLE
Cannot delete Beurer BF700 measurements

### ISSUE THREAD

**Issue by igstewart** [oliexdev/openScale#115]
Readings from Beurer BF700 scales with 1.6.1 is recording the record id value as NULL.

This is resulting in readings from the scale having no trash can to delete them.

Exporting a backup, manually editing the record id and importing resolves the issue.

**Comment by oliexdev** [comment]
what do you mean with the record id? Is the record id from the scale? What do you mean it has no trash can?
Sorry currently I can't follow you but I also don't own this scale. Maybe the problem is along with the issue #111 which is currently in discussion?

**Comment by igstewart** [comment]
When you backup data from the app it saves a database and there is an id field which increments with each new reading, this has a NULL value for readings from the scale.
![null](https://user-images.githubusercontent.com/25162870/34319176-61c80e96-e7d3-11e7-8bda-0141cbe1b1b5.png)

When manually inputting weight a trashcan is shown to delete individual records.
![screenshot_20171223-110909](https://user-images.githubusercontent.com/25162870/34319135-1e02c5c6-e7d2-11e7-84e7-3be78b6ae227.png)

When read from the scale it is not there.
![screenshot_20171223-110917](https://user-images.githubusercontent.com/25162870/34319134-1de9fb36-e7d2-11e7-88d4-d91dbfbcf90b.png)

**Comment by linuxlurak** [comment]
I reinstalled openscale (from playstore this time) and reset my scale. Ill report back when the scale gets full again and won't delete the old results. Now jumping on and off the scale ;)

**Comment by igstewart** [comment]
There doesn't seem to be any issue in readings being deleted from the scale itself for me.

It's purely removing them from the app itself I'm having issues with.

**Comment by linuxlurak** [comment]
So i filled up my BF700 with measurements till it displayed "FULL". Now no data gets synced at all. My scale stays full. Perhaps this case is not handled?

**Comment by igstewart** [comment]
This is a different issue from mine...

**Comment by linuxlurak** [comment]
Sorry. You specifically meant the delete button / trash can, I see now, right? I'll open a new issue.

**Comment by oliexdev** [comment]
@igstewart Thanks Now I understand what you mean. Unfortunately I can't reproduce this behaviour. The id is defined as a primary key in the sql database, so its automatically set by the database. Also the manual adding via the add dialog and the automatic adding of the Bluetooth data is done with the same method `addScaleData(..)` in openScale.java file. 

Could it be that you are using an OnePlus smartphone?

**Comment by igstewart** [comment]
I'm using a Xiaomi Mi 5 running Lineage 14.1

**Comment by oliexdev** [comment]
hmm sorry I don't know I can't find the problem. Maybe its help to reinstall openScale? (Make before a backup of your data)

**Comment by igstewart** [comment]
There seems to be some sort of issue with exporting/importing backups.

I wiped the app data and set everything up fresh and readings from the scale are able to be deleted.

If I then export a backup of these readings and import it back again the  records lose the ability to be deleted again.

So a fresh, known working backup stops working when it is imported, never mind the one I made to import my beurer app data.

**Comment by oliexdev** [comment]
did you change something (e.g. add new rows) in the exported database?
Normally it can't break the database by exporting and importing the database again because it is an exact copy of the database.

If you want to import your old data from the beurer app it is better to use the import function on the table page. Create a csv file in the same format for openScale. See how it should look like by exporting a sample into a csv file.

**Comment by igstewart** [comment]
OK, I got it working by just doing a csv import, thanks!

But there is definitely something wonky with the backup import/export function in the settings menu.

As I say, exporting and immediately re-importing data purely created in app leads to breakage.

**Comment by oliexdev** [comment]
that is strange but currently I can't reproduce this behaviour.

**Comment by Dododappere** [comment]
@oliexdev I managed to compile openScale and running it. I can confirm the Beurer BF800 works with your last fix!

One question though, I had to try a couple of time before it would actually connect to the device. I saw in the log some lines with 'No device found'.....I am running Android 8.1 on a Nexus 5X. Does this sound familiar? It seems reconnecting to a known device is a bit unreliable...

**Comment by oliexdev** [comment]
@Dododappere 
It could be happened if the last Bluetooth connection was not successful terminated or if you reconnected to quickly. Currently I don't have a solution to this problem. :(
