### ISSUE TITLE
Reverse engineering steps.

### ISSUE THREAD

**Issue by blaggacao** [oliexdev/openScale#119]
For fun, I thought it might be insightful todu reverse engineering on my Tezzio scale which works with the android app Fat Scale, but this app is crap...
However, I've no idea where to start... Can you give me hints, tools?

**Comment by atmaniak** [comment]
You can start here, i'm currently trying to implement my scale to (Geonaute Scale 700).
https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale

**Comment by oliexdev** [comment]
as already @atmaniak wrote please read the wiki for hints how to reverse engineer a Bluetooth scale.

If you two have any question or a success please create a PR or open a new issue.
