### ISSUE TITLE
Keeps crashing in Android, after update to 8.1.0

### ISSUE THREAD

**Issue by govvin** [oliexdev/openScale#120]
I'm using version 1.6 from the FDroid repo, but after my recent update to Android 8.1, it has become unusable and I couldn't even launch the app. It just keeps crashing.

**Comment by oliexdev** [comment]
Hi @govvin 

I tested openScale with Android Oreo in a simulator and here it works fine.
Do you use an official stable version of Android Oreo or a beta version? 
Did you send a crash report?
Did you try to reinstall openScale? (make before a backup of your data)

Best regards
oli

**Comment by govvin** [comment]
Yes, I'm using the latest, official version of Oreo for the Pixel.

There's no option for sending a crash report. Just a notification: https://mstdn.io/system/media_attachments/files/001/062/016/original/c9d2356de8ec67c8.png

I can try to reinstall, but couldn't find the data folder. Could you tell me where?

**Comment by oliexdev** [comment]
That's wired normally they if an option to send a crash report if the app crashed. Maybe they change something in Oreo?

The data folder is on Android under `/data/com.health.openscale/databases` but you need root access to view it.

**Comment by govvin** [comment]
I am now convinced it had nothing to do with the Oreo update, and must likely to be the recent change in the database - and that I've missed using OpenScale for some time.

So, what I did was to recover my backup (CSV, and DB) from another device and tried to import the DB first. That failed, with the app crashing - a similar behavior I recently just experienced.

So I tried the CSV next, and it showed me an error message: "Error importing. Can't parse CSV. Field length is wrong."

![image](https://user-images.githubusercontent.com/5821688/34466424-4f4a30aa-ef0d-11e7-9209-bb33ba815e28.png)

I did a clean install, and made a dummy entry to check out the new CSV format, and now it has two new extra columns (for Water, and Muscle percentage it seems). I updated a copy of my older CSV to accommodate the new columns, and the import went correctly.

Now, the app is working correctly, and the data restored from backup. I suppose the app crash was caused by the unexpected format of the sqlite database.

**Comment by oliexdev** [comment]
I guess you had an older version of openScale. It is true that currently I don't have backwards compatible of csv and sql backup files. But you did the right thing to recover it.
Currently I try to change the SQL backend to Android Room library which is more powerful and much easier to use.
