### ISSUE TITLE
Overview display x-axis incorrect on year change

### ISSUE THREAD

**Issue by m-z-b** [oliexdev/openScale#122]
On 2 Jan 2018  the x-axis labels showed the values 359 days, 861 days, 862 days, 863 days, -1 days rather than the small negative numbers expected.

**Comment by oliexdev** [comment]
I guess your problem is already fixed with PR #116 by @erijo. 
You can try the latest [development build](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) by Travis if you want.
