### ISSUE TITLE
Date labels on overview page are overflowing on new year

### ISSUE THREAD

**Issue by jbvo** [oliexdev/openScale#126]
As we have just gone into 2018, I noticed that the date labels on the graph on the overview page are overflowing somehow.
I weighed on January 2 2018 and before that on December 26 2017. The rightmost label says `0 days`, the one left of that says `358 days`.

**Comment by jbvo** [comment]
![screenshot_20180103-092256](https://user-images.githubusercontent.com/24601408/34513698-ca027390-f069-11e7-97dd-d8118743d456.png)

**Comment by erijo** [comment]
This is fixed on master but not yet released. See #116.

**Comment by jbvo** [comment]
Indeed, excuse me for the duplicate.
