### ISSUE TITLE
Show last measurement when opening chart view

### ISSUE THREAD

**Issue by erijo** [oliexdev/openScale#128]
If you have done some measurements in December 2017, but none now in 2018, the chart view should show the last month with measurements instead of showing an empty chart for 2018 when opened.

**Comment by oliexdev** [comment]
Honestly I see no problem here. If you didn't weight in 2017 you should simple weight one time yourself in 2018 to see something ;) But if you have a simple solution for that issue I will implement that behaviour.

**Comment by erijo** [comment]
This is fixed in #157.
