### ISSUE TITLE
Translation participation?

### ISSUE THREAD

**Issue by AxiK101** [oliexdev/openScale#133]
I wanna translate this app to greek language. Is there any way like crowdin for example? Thanks

**Comment by oliexdev** [comment]
I don't have crowdin you have to translate the string.xml into your language, see the [wiki](https://github.com/oliexdev/openScale/wiki/Frequently-Asked-Questions-(FAQ)#why-is-my-language-xyz-is-missing-or-incomplete)

**Comment by AxiK101** [comment]
Can you help me a bit? What do i translate? The black text? What software do i need? A wordpad?

**Comment by AxiK101** [comment]
![](https://i.imgur.com/NXpVB0J.png)

**Comment by oliexdev** [comment]
Yes translate the black text with wordpad or another text editor.

**Comment by erijo** [comment]
@oliexdev: perhaps you can ask for hosting on https://weblate.org/en/hosting/ ? It would make it easier for translators to contribute.

**Comment by AxiK101** [comment]
Thanks, i will do that

**Comment by oliexdev** [comment]
@erijo I filled out the web form for the free weblate hosting service but it will take time up to one month.

@AxiK101 How is your translation going?

**Comment by oliexdev** [comment]
I guess @AxiK101 has vanished, so I will close this issue. Please comment here if you come back or create a PR.

**Comment by erijo** [comment]
@AxiK101: you can now use https://hosted.weblate.org/projects/openscale/ to do the translation.
