### ISSUE TITLE
App crash with RT-Libra-B

### ISSUE THREAD

**Issue by mmangard** [oliexdev/openScale#134]
Hello, 
I just tried openScale  with the latest development build (v1.7-beta-7d735146 ) and a "RT-Libra-B".
After a successful connection the app displays some values which differ from the display and crashes afterwards. The issues is 100% reproduce able. I use Android version 6.0.1. How can I help? If you want I could do some tests with a development build which includes some debug-traces.

**Comment by oliexdev** [comment]
Yeah would be great if you could print the stacktrace so we can see in which source code line the crash happens.

**Comment by mmangard** [comment]
How can I provide you the stacktrace? Do I need an  Android Development Environment for that (which I do not have)?

**Comment by oliexdev** [comment]
Do you have any programming experiences? You can install android studio and compile the source code.

Or see https://www.utest.com/articles/how-to-get-android-crash-logs-by-using-adb-commands
Or see here https://f-droid.org/de/docs/Getting_logcat_messages_after_crash/

**Comment by mmangard** [comment]
See my log/stackstrace [measurelog.txt](https://github.com/oliexdev/openScale/files/1629246/measurelog.txt)

**Comment by oliexdev** [comment]
Did you create an user in openScale? And what is the name of the user?

**Comment by mmangard** [comment]
I created a user with the name "mm".  In order to double check my settings i opened the settings and the app crashed again. After a restart of the app I could do measurements.

In order to force the problem again I reinstalled the app.  After the initial start the app shows the user-account dialog. After pressing the add button the app crashed with the following stacktrace. 
[settingslog.txt](https://github.com/oliexdev/openScale/files/1629439/settingslog.txt)

For me it seems that these crashes are somehow releated.

**Comment by oliexdev** [comment]
ok for first problem I think I know the problem can please try to use a name with at least 3 characters. 

> In order to force the problem again I reinstalled the app. After the initial start the app shows the user-account dialog. After pressing the add button the app crashed with the following stacktrace.
> settingslog.txt

That is strange. Can you exactly tell me what you entered in the user-account dialog? Currently I can't reproduce this error.

**Comment by mmangard** [comment]
I can reproduce the crash with a 2 letter username by doing the following steps:

1) delete all existing user 
2) exit the app
3) start the app  and create the following user
![screenshot_20180114-184505](https://user-images.githubusercontent.com/8190754/34918978-c188cd62-f95c-11e7-8f65-dce80253cc4c.png)

if I choose a username with 3 letters I can create the account without a crash.

**Comment by oliexdev** [comment]
In the latest development version you have to enter an username with at least 3 characters.

But does it crash again with your scale when you have a longer username?

**Comment by mmangard** [comment]
no it does not crash with a username with at least 3 characters and I can perform a measurement. 
The measurement only results in the weight (water, and other values are missing). 
Is this a known issue?

**Comment by oliexdev** [comment]
yes see [here](https://github.com/oliexdev/openScale/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-get-on-my-sbf70-scale-the-body-metrics-water-muscle-fat-percentage)

**Comment by oliexdev** [comment]
btw which tool did you use to get the stacktraces? And did you need root permission for that?

**Comment by mmangard** [comment]
first I tried "aLogcat" but somehow I could not get any logs so I installed Android Studio and compiled the sources.
