### ISSUE TITLE
App version v1.6.1 is missing on F-Droid

### ISSUE THREAD

**Issue by wolkenschieber** [oliexdev/openScale#135]
Current version *v1.6.1* hasn't been published to F-Droid. The latest version there is *v1.6*.

Can you please upload latest version? Thanks!

**Comment by erijo** [comment]
1.6.1 was attempted to build, but it failed. I reported it https://gitlab.com/fdroid/fdroiddata/issues/1061 but haven't gotten any real reply.

**Comment by oliexdev** [comment]
The next version of openScale will be incremental released soon. Therfore the new version will be published on F-Droid. Before you update to version 1.7 I would recommend to export your data to a CSV file because the backend of the database had been changed.
