### ISSUE TITLE
Connection to YunChen Smart Scale

### ISSUE THREAD

**Issue by pkscwc** [oliexdev/openScale#140]
Dear Olie,

I have recently purchased this Yunchen Brand smart scale. 
Can you add it as one of supported scales in your program.

I have tried using some hcitool and GATTtool commands to get relevant handles and UUIDs for this scale.

It is based on Texas Instrument chip.

Output of GATTTool commands like Primary  &  char-desc-hnd are given below:

Result of GATTtool log : command "primary"

attrhandle:0x0001,endgrp handle:0x0007 uuid:00001800-0000-1000-8000-00805f9b34fb
attrhandle:0x0008,endgrp handle:0x000a uuid:0000180a-0000-1000-8000-00805f9b34fb
attrhandle:0x000b,endgrp handle:0x000e uuid:00010203-0405-0607-0809-0a0b0c0d1912
attrhandle:0x000f,endgrp handle:0x0013 uuid:0000ffaa-0000-1000-8000-00805f9b34fb
attrhandle:0x0014,endgrp handle:0x001c uuid:0000fff0-0000-1000-8000-00805f9b34fb

Result of GATTtool log : command "char-desc"

handle:0x0001,uuid:00002800-0000-1000-8000-00805f9b34fb
handle:0x0002,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x0003,uuid:00002a00-0000-1000-8000-00805f9b34fb
handle:0x0004,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x0005,uuid:00002a01-0000-1000-8000-00805f9b34fb
handle:0x0006,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x0007,uuid:00002a04-0000-1000-8000-00805f9b34fb
handle:0x0008,uuid:00002800-0000-1000-8000-00805f9b34fb
handle:0x0009,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x000a,uuid:00002a50-0000-1000-8000-00805f9b34fb
handle:0x000b,uuid:00002800-0000-1000-8000-00805f9b34fb
handle:0x000c,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x000d,uuid:00010203-0405-0607-0809-0a0b0c0d2b12
handle:0x000e,uuid:00002901-0000-1000-8000-00805f9b34fb
handle:0x000f,uuid:00002800-0000-1000-8000-00805f9b34fb
handle:0x0010,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x0011,uuid:0000ffab-0000-1000-8000-00805f9b34fb
handle:0x0012,uuid:00002902-0000-1000-8000-00805f9b34fb
handle:0x0013,uuid:00002901-0000-1000-8000-00805f9b34fb
handle:0x0014,uuid:00002800-0000-1000-8000-00805f9b34fb
handle:0x0015,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x0016,uuid:0000fff4-0000-1000-8000-00805f9b34fb
handle:0x0017,uuid:00002902-0000-1000-8000-00805f9b34fb
handle:0x0018,uuid:00002901-0000-1000-8000-00805f9b34fb
handle:0x0019,uuid:00002803-0000-1000-8000-00805f9b34fb
handle:0x001a,uuid:0000fff1-0000-1000-8000-00805f9b34fb
handle:0x001b,uuid:00002902-0000-1000-8000-00805f9b34fb
handle:0x001c,uuid:00002901-0000-1000-8000-00805f9b34fb

The values received from each handle above through command "char-read-hnd" in above order are given under:

0018
12
59756e4368656e0000000000000000000000
02
0000
02
140028000000e803
0a18
02
028a2466820100
12190d0c0b0a09080706050403020100
16
00
4f5441
aaff
14
0000000000000000000000000000000000000000
0000
436d64205257
f0ff
10
0000000000000000000000000000000000000000
0000
53707020524f
04
0000000000000000000000000000000000000000
0000
53707020574f

I have browsed through files hosted at openScale/android_app/app/src/main/java/com/health/openscale/core/bluetooth/

and found that four of the java files use these UUIDs.

Like: 
BluetoothBeurerBF700_800 and BluetoothSanitasSbf70 use 

UUIDs of 00002A00, 01, 04 and 50. 

BluetoothDigooDGSO38H and BluetoothExcelvanCF369BLE use UUIDs of 0000FFF0, 1 and 4. 

I hope it helps.

**Comment by oliexdev** [comment]
Hi @pkscwc 

I can't find this scale on the internet. :thinking: 
Do you have a link to the vendors website?

Did you read the [wiki](https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale) about how to reverse engineer a Bluetooth scale?
Maybe [this](https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale) helps a bit too how you do it on a real device.

You have to analyse the incoming and outcoming values so we know which byte is used for what.

Some UUIDs are standard UUIDs but that doesn't mean that the data format are the same (but sure it could be possible).

I don't own this scale so its difficult to help in this stage. You have to do analyse the byte structure and the commands which are send from the your scale.

Btw. please use the Markdown code tags for posting source code or formatted output messages.

Best regards
oli

**Comment by pkscwc** [comment]
I have some hci snoop logs.

**Comment by oliexdev** [comment]
then try to analyse it with wireshark as described in the wiki.

**Comment by pkscwc** [comment]
OK. What data exactly may help us.

**Comment by pkscwc** [comment]
I have uploaded the blue pixel ble scan log having UUID s in it.

**Comment by Dododappere** [comment]
@pkscwc if your scale uses the FFF1 characteristic I would try to make a copy of the Digoo scale handler code and configure OpenScale to accept your scale. With a bit of luck it will work....if it doesn't you need to do reverse engineering of the hci snoop logs to see what is going on.

**Comment by pkscwc** [comment]
Ok. Thanks. I will put in required efforts from my side also.

**Comment by pkscwc** [comment]
Hi Olie,

I have done some work today on wireshark and ble snoop.

Perhaps, got the values required.



Hope, it helps.

**Comment by pkscwc** [comment]
Hi Olie,

I have attached the ble log file also.

**Comment by oliexdev** [comment]
@pkscwc you didn't attached anything.  Also you have to analyse the protocol to find weight and other data in the Bluetooth data packages.

**Comment by pkscwc** [comment]
Please check. I can see attachments sent in the email with desired
details...

**Comment by erijo** [comment]
I didn't get the attachment either. Please see https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ for how to attach files.

**Comment by pkscwc** [comment]
OK thanks.

**Comment by pkscwc** [comment]
I have submitted it as a new issue with relevant files. Thanks.

**Comment by pkscwc** [comment]
[YunchenLog.docx](https://github.com/oliexdev/openScale/files/1648948/YunchenLog.docx)
[YunChen_only_filter.log](https://github.com/oliexdev/openScale/files/1648949/YunChen_only_filter.log)

**Comment by oliexdev** [comment]
@pkscwc 
thanks for the files but I need more information.

1. Please provide a link to the vendors app
2. Please provide a link to the product page of your YunChen scale.
3. I need a photo of your scale for the gallery (same angle like the others)
4. I need the complete Bluetooth log file. Your `YunChen_only_filter.log` file filtered to much out. The commands from the vendors App are missing.

**Comment by pkscwc** [comment]
In a minute.

**Comment by pkscwc** [comment]
https://www.amazon.in/gp/product/B071J756ZB/ref=oh_aui_detailpage_o06_s00?ie=UTF8&psc=1

**Comment by pkscwc** [comment]
Vendors other products
https://www.amazon.in/Health-Personal-Care-Hesley-Inc/s?ie=UTF8&field-brandtextbin=Hesley%20Inc&page=1&rh=n%3A1350384031

**Comment by pkscwc** [comment]
Vendor's app known as KeepFit
https://play.google.com/store/apps/details?id=com.beikang&hl=en

**Comment by pkscwc** [comment]
The complete log. I just realized that I have filtered the commands from localhost to remote. This is the complete log containing all the bluetooth devices nearby to my mobile. Lot of garbage. 

[BtSnoop_17Jan2018.log](https://github.com/oliexdev/openScale/files/1649674/BtSnoop_17Jan2018.log)

**Comment by pkscwc** [comment]
hope it helps.

**Comment by pkscwc** [comment]
In this file, I have tried to include both. scale to mobile and mobile to scale.
[scale_to_mobile_all.log](https://github.com/oliexdev/openScale/files/1649681/scale_to_mobile_all.log)

**Comment by pkscwc** [comment]
Another, filtered but having both way traffic log

[scale_to_PERX_all.log](https://github.com/oliexdev/openScale/files/1649699/scale_to_PERX_all.log)

**Comment by oliexdev** [comment]
@pkscwc 
I implemented a first try for Hesley scale. Please try the latest dev version of openScale.

Some thinks that are not clear yet:

1. The scale is sending around 149 (:open_mouth: !) times the same command bytes `a5:01:2c:ab:50:5a:29`  to the scale. After every command the scale send sometimes mostly nothing or the weight with the body metrics.
2. Currently I don't know what the magic bytes `a5:01:2c:ab:50:5a:29` are. Maybe the date and time are in these byte!?
3. Which date and exact time did you weight in the above log files?
4. What did you enter in the app for your body height and your age?

Do you receive any data from the scale with openScale? A toast message should popup with some hex bytes. Please post that here.

**Comment by pkscwc** [comment]
Dear Olie,

I have noticed the  magic bytes a5:01:2c:ab:50:5a:29 and tried my level best to connect with them date and time formats. So far, there is nothing to link with them date and time. The exact date and time of each packet is logged and can be seen in Wireshark. 

![screenshot from 2018-01-21 19-47-19](https://user-images.githubusercontent.com/1967671/35195077-fad118c2-fee3-11e7-9a07-5ba21833a007.png)

**Comment by pkscwc** [comment]
another one from today.
![image](https://user-images.githubusercontent.com/1967671/35195197-ff5884b4-fee5-11e7-97d1-4fbf7e63b4ed.png)

**Comment by pkscwc** [comment]
This cannot be a data or time string as it is same for both days i.e. 17th and 21st January. Date & time should be somewhere else.

**Comment by oliexdev** [comment]
@pkscwc It was just an idea but please give clear feedback what is working and what not otherwise we don't get any further in the reverse engineering process.

**Comment by pkscwc** [comment]
An image of the scale:

![img_20180121_192113](https://user-images.githubusercontent.com/1967671/35195785-81603ea4-feee-11e7-950d-6d63e0d4c3b5.jpg)

**Comment by pkscwc** [comment]
Dear Olie,

I am sorry. But, I don't know how to install developer version of openscale on my mobile. Is there any apk to download? I cannot find anything helpful.

with regards,

**Comment by pkscwc** [comment]
Ok.
Got it, I have to install Android-Studio. 
Please give me some time.

**Comment by oliexdev** [comment]
Or use this APK file https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

**Comment by pkscwc** [comment]
Install openScale-dev-build.apk . Yes found this. Thanks.

**Comment by pkscwc** [comment]
In Bluetooth logs, it is recognised as Yunchen only.

**Comment by pkscwc** [comment]
App installed without any error. 
It found my scale as Yunchen.
After that, "trying to connect to Yunchen".
And then " no bluetooth devices found".

I noticed that app bluetooth search timeout is rather short. Scale remains active for twice more time.

**Comment by pkscwc** [comment]
So, no readings for now.

**Comment by pkscwc** [comment]
![img_20180121_192113](https://user-images.githubusercontent.com/1967671/35204360-9b1b8f46-ff53-11e7-8a81-3bf59eda8448.jpg)
![img_20180121_192242](https://user-images.githubusercontent.com/1967671/35204361-9b4bca30-ff53-11e7-96bd-8cf1aba978fb.jpg)
![img_20180121_192313](https://user-images.githubusercontent.com/1967671/35204362-9b76f7fa-ff53-11e7-814e-43eabb290a53.jpg)
![img_20180121_192429](https://user-images.githubusercontent.com/1967671/35204363-9ba591fa-ff53-11e7-9f99-43fce5a4f9f2.jpg)
![img_20180121_192445](https://user-images.githubusercontent.com/1967671/35204364-9bd83290-ff53-11e7-8314-17a6e67bc861.jpg)
![img_20180121_192528](https://user-images.githubusercontent.com/1967671/35204365-9c0b3e4c-ff53-11e7-8747-6d2af0ba5c1f.jpg)
![img_20180121_192542](https://user-images.githubusercontent.com/1967671/35204366-9c3934aa-ff53-11e7-8677-19587749af1d.jpg)
![img_20180121_192549](https://user-images.githubusercontent.com/1967671/35204367-9c6e329a-ff53-11e7-9da7-e4a6750f3620.jpg)

**Comment by pkscwc** [comment]
I used the apk file. It connects but no data comes back from scale to app.

Can we change the magic number and try.

**Comment by pkscwc** [comment]
nRF Connect, 2018-01-22
YunChen (78:9C:E7:0C:1F:F3)
I	14:49:22.839	[Server] Server started
V	14:49:22.858	Device Information (0x180A)
- PnP ID [R] (0x2A50)
Unknown Service (00010203-0405-0607-0809-0a0b0c0d1912)
- Unknown Characteristic [N R WNR] (00010203-0405-0607-0809-0a0b0c0d2b12)
   Characteristic User Description (0x2901)
   Client Characteristic Configuration (0x2902)
Unknown Service (0000ffaa-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N WNR] (0000ffab-0000-1000-8000-00805f9b34fb)
   Characteristic User Description (0x2901)
   Client Characteristic Configuration (0x2902)
Unknown Service (0000fff0-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N] (0000fff4-0000-1000-8000-00805f9b34fb)
   Characteristic User Description (0x2901)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [WNR] (0000fff1-0000-1000-8000-00805f9b34fb)
   Characteristic User Description (0x2901)
V	14:49:23.169	Connecting to 78:9C:E7:0C:1F:F3...
D	14:49:23.169	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE)
D	14:49:23.515	[Server callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	14:49:23.515	[Server] Device with address 78:9C:E7:0C:1F:F3 connected
V	14:49:23.515	[Server] Creating server connection...
D	14:49:23.515	server.connect(device, autoConnect = false)
D	14:49:23.521	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	14:49:23.521	Connected to 78:9C:E7:0C:1F:F3
D	14:49:23.524	wait(1600ms)
D	14:49:23.545	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
V	14:49:25.131	Discovering services...
D	14:49:25.131	gatt.discoverServices()
D	14:49:25.158	[Callback] Services discovered with status: 0
I	14:49:25.159	Services discovered
V	14:49:25.186	Generic Access (0x1800)
- Device Name [N R] (0x2A00)
- Appearance [R] (0x2A01)
- Peripheral Preferred Connection Parameters [R] (0x2A04)
Device Information (0x180A)
- PnP ID [R] (0x2A50)
Unknown Service (00010203-0405-0607-0809-0a0b0c0d1912)
- Unknown Characteristic [N R WNR] (00010203-0405-0607-0809-0a0b0c0d2b12)
   Characteristic User Description (0x2901)
Unknown Service (0000ffaa-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N WNR] (0000ffab-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
Unknown Service (0000fff0-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N] (0000fff4-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
- Unknown Characteristic [WNR] (0000fff1-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
D	14:49:29.620	[Server callback] Connection state changed with status: 0 and new state: DISCONNECTED (0)
I	14:49:29.620	[Server] Device disconnected
D	14:49:29.667	[Callback] Connection state changed with status: 8 and new state: DISCONNECTED (0)
E	14:49:29.667	Error 8 (0x8): GATT CONN TIMEOUT
I	14:49:29.667	Disconnected
D	14:49:29.814	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED

**Comment by pkscwc** [comment]
Log by nRF logger

**Comment by oliexdev** [comment]
please fork the project and edit the `BluetoothHesley.java` file in Android Studio. In that file you can see the magic bytes which you can change.
I can't help you much anymore because you have to do some kind of try and error analyses with your scale.

**Comment by pkscwc** [comment]
Hi Olie,

App now gets connected with scale. But it is not showing any measurement
yet. Can we increase the bluetooth time-out of the app. It time-outs before
the scale.

Any suggestion.

**Comment by oliexdev** [comment]
@pkscwc 
It has nothing to do with the Bluetooth time-out. Please create some image with the  [BLE Scanner](https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner). Then I can check again of the right services and characteristic. But as I said you have to experiment with your scale.

**Comment by pkscwc** [comment]
Dear Olie,

I would like to express my sincere thanks for all the encouragements and actually writing the BluetoothHesley.java file for users of Hesley scale. 


Yes, it worked. 

I studied the logs in wireshark as suggested by you and tweaked the java file. The scale starts broadcasting the data as soon as it is activated.  So, the use of magic bytes are still a mystery. 

Relevant files are attached with screenshot. 
![screenshot_20180128-222813](https://user-images.githubusercontent.com/1967671/35484825-b6455fae-047b-11e8-8949-51515ff28950.png)
[BluetoothHesley_worked_java.txt](https://github.com/oliexdev/openScale/files/1671314/BluetoothHesley_worked_java.txt)

**Comment by pkscwc** [comment]
Remaining data like fat etc is not present, because scale did not broadcast it.

**Comment by oliexdev** [comment]
I implemented your changes into the master repository. Use the latest development version of openScale.

I guess to get the remaining data we have to figure out what the magic bytes are. Until then I will close this issue. If you find a solution create a new issue or PR or reply to this issue.

**Comment by pkscwc** [comment]
Dear Olie,

It looks like that I made a mistake. It is not getting connected. I only read my manually entered data. I have updated some information in the java file. Particularly the data test part, data [1] = 0x01 should be 0xc1. I have altogether removed it. But, still it is not working. Although, in the log file, it clearly shows that scale is returning full data (including fat etc ) after receiving the magic bytes. 

Your expert opinion is required. 
[BluetoothHesley.java.txt](https://github.com/oliexdev/openScale/files/1678688/BluetoothHesley.java.txt)
[os30jan8640.log](https://github.com/oliexdev/openScale/files/1678691/os30jan8640.log)

**Comment by pkscwc** [comment]
Further, the toast commands are not creating any message window. What to do?

**Comment by oliexdev** [comment]
I have seen your post but I don't know either.

**Comment by oliexdev** [comment]
@pkscwc I changed the implemented Bluetooth search algorithm in openScale which use now the new Android API so please test it with the latest development version.

**Comment by pkscwc** [comment]
Hi,

Can you give me some idea for debugging the app. It is not picking up the
reading sent by scale. Scale is surely sending the readings as seen in BLE
log.

Bye

**Comment by oliexdev** [comment]
@pkscwc  for debugging see https://developer.android.com/studio/debug/index.html

I will remove this try in the master repository until we get working version.

For reference the latest implementation in the mater repository was [BluetoothHesley.java](https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothHesley.java).

**Comment by pkscwc** [comment]
Please check in the new issue. I have uploaded the screenshots and working
java file.
