### ISSUE TITLE
Exporting and importing info

### ISSUE THREAD

**Issue by ivvv** [oliexdev/openScale#141]
Many thanks for the good `openScale` app. I have started using and I really like it.

I want to import measurements from a file but I could not find any documentation on what the CSV columns should be. I exported my current measurements from `openScale` and it is easy to guess some of the columns, but not all of them.

The easiest way to improve this would be to add the column names when exporting the `openScale` measurements to a CSV file. And of course, better use human understandable column names :-)

**Comment by oliexdev** [comment]
It has been already implemented in the development or beta version of openScale. :wink:
