### ISSUE TITLE
Suggestion for improved chart

### ISSUE THREAD

**Issue by ivvv** [oliexdev/openScale#146]
Using v1.7 (beta) on Android 7.0.

The chart measurements are displayed with their values. This makes it difficult to see the general trend when there are many data points. The chart is too crowded, see the screenshot.

![screenshot_2018-01-14-22-35-25](https://user-images.githubusercontent.com/7148876/34920951-7feb3434-f97b-11e7-9c79-a7d618469d5d.png)

I would suggest to remove the value labels from the chart for the individual measurements: the y-axis provides the approximate values, e.g via the grid lines, and they are also available in the table if the actual value is important.

**Comment by erijo** [comment]
This can be set in the settings under chart -> Label on data point.

**Comment by oliexdev** [comment]
you can even add a regression line into the graph :wink:
