### ISSUE TITLE
newest version 1.4.3 not available

### ISSUE THREAD

**Issue by TjrGithub** [oliexdev/openScale#15]
Hi, in issue #13, you suggested to upgrade to version 1.4.3. However, only version 1.4.2 is available.

https://f-droid.org/repository/browse/?fdfilter=openscale&fdid=com.health.openscale

(fleshed out of #13)

**Comment by oliexdev** [comment]
be patient I released the new version just 10 min ago and F-Droid upgrade it daily or weekly?! 
If you can't wait download the apk file under [openScale 1.4.3 release](https://github.com/oliexdev/openScale/releases/tag/v1.4.3)

**Comment by TjrGithub** [comment]
Wow, thanks. Sorry I didn't check Github first.
