### ISSUE TITLE
Feature request Xiaomi Mi scale v. 2

### ISSUE THREAD

**Issue by pietroblu** [oliexdev/openScale#150]
Is there a chance to have full compatibility measures for this very known scale?
Thanks for your work.

**Comment by oliexdev** [comment]
Hi @pietroblu no currently it is very hard to reverse engineer the full scale see the remarks on the [wiki](https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale). They used an intransparent formula hidden in the app.

But sadly you gave openScale a 2-star review for that circumstance even it is clear described on the wiki. :disappointed: I hope you change you mind.

**Comment by pietroblu** [comment]
You're right Oliexdev, I've been unfair, I'll delete my review ;)
