### ISSUE TITLE
Beurer BF710

### ISSUE THREAD

**Issue by Megachip** [oliexdev/openScale#151]
Any chance to get support for the BF710?

**Comment by oliexdev** [comment]
No as long you reverse engineer your scale on your own. See the FAQ for more information.

**Comment by Megachip** [comment]
![20180121_2147327721](https://user-images.githubusercontent.com/487352/35198905-2c96a040-fef6-11e7-83a6-5e2c117152a0.jpg)
Hope this will help to start...

**Comment by pkscwc** [comment]
Dear Megachip,
the image is not clear.

Can you send it again.

**Comment by Megachip** [comment]
@pkscwc *fixed* Sorry, seems to catch the compressed one before. Not yet checked if they use the same characteristics as the BF700/800... hope a little bit. If not, I should try some package dumps next time ;)

**Comment by Megachip** [comment]
Seems using the same protocol like other Beurer scales. So it should work with openScale...

**Comment by Megachip** [comment]
Anyone had success? Get managed to create a test build but cant install it anywhere :/ (Tested Android 7 and 8)

**Comment by magaiverpr** [comment]
Waiting for this too.

This ticket was closed because there is no way to implement?

**Comment by erijo** [comment]
If you haven't seen it already, support is available in the latest [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build).
