### ISSUE TITLE
Is posible change the theme to ligth color?

### ISSUE THREAD

**Issue by Nadivar** [oliexdev/openScale#162]
Hi, I saw that the app showed in ligth color, but in my case is dark.... It´s very difficult reads anything
 could anybody tell me the way to change it?
this image is my actual theme....
![whatsapp image 2018-01-26 at 20 57 55](https://user-images.githubusercontent.com/35816818/35458336-337c46f0-02dc-11e8-8d9f-62a1660f4dcb.jpeg)
this one is like I want...
![image](https://user-images.githubusercontent.com/35816818/35458418-91e8e982-02dc-11e8-981e-5a26b49dc1f6.png)

**Comment by oliexdev** [comment]
You are probably using another App which change global wide the App theme of your installed Apps. It has nothing to do with openScale. In openScale you can't change the theme it use a default one.

**Comment by Nadivar** [comment]
Upsss, I don´t know, because it´s the only app shows in dark.
Best regards.
Thanks for answering.

**Comment by oliexdev** [comment]
@Nadivar I implemented now a theme selector for the app. Try out the latest development version of openScale.
