### ISSUE TITLE
No Bluetooth device found.

### ISSUE THREAD

**Issue by Sarkasper** [oliexdev/openScale#17]
I tried a couple times to connect but it won't work. 
If you need more info let me know.

![tmp_19829-screenshot_20170313-121415279015310](https://cloud.githubusercontent.com/assets/806597/23852465/3284c140-07e8-11e7-976d-ffa5012c6c6b.png)
![tmp_19829-screenshot_20170313-1214291164237786](https://cloud.githubusercontent.com/assets/806597/23852470/375a522a-07e8-11e7-93c1-e56e89245249.png)
![tmp_19829-screenshot_20170313-122118780939641](https://cloud.githubusercontent.com/assets/806597/23852471/3bc38c64-07e8-11e7-82d4-cd6f8a813cdc.png)

**Comment by oliexdev** [comment]
Hi Sarkasper,

thanks for your hint. Its seems like devices with starting hardware address `C8:OF:10` makes trouble. Which openScale version do you use and what is your SmartPhone and Android version?

Best regards
Oli

**Comment by Sarkasper** [comment]
![tmp_11110-screenshot_20170313-202042153956329](https://cloud.githubusercontent.com/assets/806597/23871467/d2c75ba8-082a-11e7-958a-6b3086142f98.png)
![tmp_11110-screenshot_20170313-202107810698885](https://cloud.githubusercontent.com/assets/806597/23871473/e0ca4fda-082a-11e7-9ebf-480da64f97f8.png)

**Comment by Sarkasper** [comment]
I found the new release of version 1.4.3 and that has fixed it, thanks!
