### ISSUE TITLE
weekly statistics

### ISSUE THREAD

**Issue by att90** [oliexdev/openScale#170]
Hi, 
Thank you for the great app first of all. I would like to have a question if is possible to add 7day average in current week and 7day average on past week, so you compare the weigh gain on average for a week. As you know the weigh is fluctuating and if you are going to gym and clean bulking you have to check it in average on weekly basis. Thanks

**Comment by oliexdev** [comment]
Yeah it is possible. If I have more time I will see if I can and how implement it.

**Comment by oliexdev** [comment]
implemented it with commit https://github.com/oliexdev/openScale/commit/dd6c9b20981d00d85b3bac621d52b38350c62b6f
