### ISSUE TITLE
memory leak occures on a screen orientation change

### ISSUE THREAD

**Issue by oliexdev** [oliexdev/openScale#175]
A memory leak occurs when the screen orientation is changed. Some fragments or variables are not cleaned up on destroying the activity. Right now, I didn't find out who was causing the trouble.

It would be great If anybody can look into it.

**Comment by erijo** [comment]
Could it be the fragmentList in OpenScale that holds on to fragments after they have been destroyed?

**Comment by oliexdev** [comment]
I doubt that because the fragment list is inside a singleton class.
Maybe the FragmentManager are not cleared up correctly?

**Comment by erijo** [comment]
As the list holds a reference to the fragment the GC can't free the memory even if the fragment is released by the manager. So even if not technically a memory leak, it will still consume memory each time a fragment is created.

**Comment by oliexdev** [comment]
but even if I clear the fragmentList on MainActivity destroy the memory usage is increasing on rotation.
