### ISSUE TITLE
SBS Kitchen Scale

### ISSUE THREAD

**Issue by muhammedgunes** [oliexdev/openScale#179]
Hi i try to connect [this scale](http://www.sbsmobile.it/en-gb/products/fitness-health/wearable/2239-digital-kitchen-scale.html). Can you help me? 

App connect this scale with BluetoothExcelvanCF369BLE but still i can't get bluetooth data.

**Comment by oliexdev** [comment]
Your scale is not a body scale so openScale probably won't support it but you can also see [here](https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale) to get an impression how general the reverse engineer process of a Bluetooth 4.x. scale works.
