### ISSUE TITLE
SBF70 Initialization not working properly

### ISSUE THREAD

**Issue by SebastianApel** [oliexdev/openScale#180]
Hi @jflesch,
first of all: thanks for the great work of reverse engineering the SBF 70! 

Management Summary: 
I have trouble with getting body fat readings. I read the FAQ, tried resetting the scale - it did not work. My hypothesis is that the initialization is not working properly. I am using v1.7 (23) installed via F-Droid.

Workaround: When I used the Sanitas HealthCoach app to initialize the scale and add the user, I received body fat readings.

Hypothesis: My hypothesis is that the user initialization is not working properly, but that is only a vague assumption based on the workaround and a quick glance at the log files. [sbf70log.txt](https://github.com/oliexdev/openScale/files/1708524/sbf70log.txt)

Any ideas?

Cheers,
Sebastian

**Comment by jflesch** [comment]
Initialization is not supported. I haven't had time to reverse-engineer it yet.
I don't know why it's checked on https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale . Neither initialization or history are supported (unless someone else made it ? oO)

**Comment by SebastianApel** [comment]
Ok, interesting, because now it works. The workaround that did it for me was: 
1. Kill the OpenScale App in the Android Settings, 
2. Reset the Scale, 
3. Activate the Scale by stepping on it, 
3. Step off the scale,
4. Start Openscale,
5. Wait until the Initials are shown on the scale,
6. Step on the scale for the first measurement

I am posting this in hope it helps someone else. Again thanks for the great work!

**Comment by jflesch** [comment]
I think I don't understand everything here. What do we call "initialization" ? Is it registering a user in the scale ? Or is it just connecting to the scale ?

**Comment by lenucksi** [comment]
@jflesch see #153 for details. The scale works fine for me.

**Comment by MartinNowack** [comment]
@jflesch I added the additional support and fixed a few things. Please have a look at #66 it's already merged since a couple of months.

**Comment by MartinNowack** [comment]
@jflesch "Initialization" is a base line measurement which allows to scale to detect the correct user even without the app. This is what happened in the original app HealthCoach app when you create a user.

@SebastianApel the log indicated that it could not assign/detect the user assigned to you.

But I'm glad it works now for you

**Comment by jflesch** [comment]
@MartinNowack oh nice, thanks :)

**Comment by oliexdev** [comment]
I am confused so is the wiki entry for SBF 70 right or not? Should I change something?

**Comment by MartinNowack** [comment]
@oliexdev Everything is fine. Entries are correct.

**Comment by oliexdev** [comment]
@MartinNowack thanks for the clarification.

@SebastianApel Does it work now?
