### ISSUE TITLE
Option to change the language

### ISSUE THREAD

**Issue by Pablohn26** [oliexdev/openScale#186]
First of all, thanks for this amazing app. I also had the need to track my measurements with open source since Xiaomi is not a big fan of open their code.

I have been translating the app and I missed an option to change the language. This is useful for translating tasks and also for people that have their phone in a language but want to use this app in another language. It seems the language is auto detected and applied, but it is also good to be able to change it.

I am not sure if this feature would be too much code, but would be good to have it.

**Comment by oliexdev** [comment]
@Pablohn26 thanks for your translation and your 5 star review. :+1: 

You are right, the language is auto detect depending on your system language, like most of the apps doing it. I don't see no need for a manual in app language selection. If you translate the app I guess most people will translate the app in their native language so the system language is also the target language. 

If you have an option to manual select the language the auto detect wouldn't work so easy and will confuse normal users if they have to first select manual their native language.
