### ISSUE TITLE
Finally working with Hesley scale

### ISSUE THREAD

**Issue by pkscwc** [oliexdev/openScale#187]
Dear Olie,

Debugging took some time. 

Strange error!! The toast does not work with Marshmallow!!! 

The working java file is attached alongwith screenshots. A number of them. 

We can add it to our list of scales. It is a good one. 
![screenshot_20180213-000903](https://user-images.githubusercontent.com/1967671/36165139-8e94c7ec-1114-11e8-9a66-243f41210412.png)
![screenshot_20180213-001216](https://user-images.githubusercontent.com/1967671/36165140-8ecbc63e-1114-11e8-87c2-0d5b6d002f48.png)
![screenshot_20180213-001447](https://user-images.githubusercontent.com/1967671/36165141-8f0340c8-1114-11e8-82b9-214a45629980.png)
![screenshot_20180213-081255](https://user-images.githubusercontent.com/1967671/36165142-8f38923c-1114-11e8-9344-4ac41dd47924.png)
![screenshot_20180213-081512](https://user-images.githubusercontent.com/1967671/36165143-8f6e18d0-1114-11e8-84ec-f0e1d6a3f6eb.png)
[BluetoothHesley_java_13Feb2018.java.txt](https://github.com/oliexdev/openScale/files/1720995/BluetoothHesley_java_13Feb2018.java.txt)

Thanks.

**Comment by oliexdev** [comment]
great I change the code with commit https://github.com/oliexdev/openScale/commit/0050ec46ff9e24ca500afa79f487afc2ef6a0aaa

**Comment by pkscwc** [comment]
Do we have APK also updated with Healey scale.

**Comment by pkscwc** [comment]
Thanks a lot.

On 14 Feb 2018 11:07 p.m., "OliE" <notifications@github.com> wrote:

great I change the code with commit 0050ec4
<https://github.com/oliexdev/openScale/commit/0050ec46ff9e24ca500afa79f487afc2ef6a0aaa>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oliexdev/openScale/issues/187#issuecomment-365685507>,
or mute the thread

**Comment by erijo** [comment]
See https://github.com/oliexdev/openScale/releases/tag/travis-dev-build for an APK built from latest master.

**Comment by pkscwc** [comment]
Dear Olie,
Can we have only one reading for every step on scale. I am attaching a csv
file for clarifying the issue. I am getting 100s of reading for each time I
step on the scale.

On 15 Feb 2018 12:39 a.m., "Erik Johansson" <notifications@github.com>
wrote:

See https://github.com/oliexdev/openScale/releases/tag/travis-dev-build for
an APK built from latest master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oliexdev/openScale/issues/187#issuecomment-365712647>,
or mute the thread

**Comment by oliexdev** [comment]
Sure modify the BluetoothHesley.java file so that only the last send data is valid.

**Comment by pkscwc** [comment]
:-)
Is it through BluetoothHesley.java file?
I cannot read it in this file. Isn't there any separate java file for data?

**Comment by pkscwc** [comment]
Dear Olie,

Any hint!
I would work on that further.

Thanks.

**Comment by oliexdev** [comment]
try to avoid that the method `parseBytes(...)` is always called in the BluetoothHesley.java file call it just once time if you receive a new weight.

**Comment by pkscwc** [comment]
OK.
Will try and let you know.
