### ISSUE TITLE
Photo of Runtastic scale

### ISSUE THREAD

**Issue by oliexdev** [oliexdev/openScale#189]
Can somebody post a photo of the Runtastic scale for our [wiki](https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale)? Due to copyright reasons I can't take a photo by the internet. If you take a photo please take one with the same angle like the other ones. Thanks.

**Comment by Dododappere** [comment]
![runtastic-libra](https://user-images.githubusercontent.com/34566117/37387870-83a57b64-275e-11e8-9ff0-c0b5bbbde72e.jpg)
Here you are...

**Comment by oliexdev** [comment]
thanks @Dododappere
