### ISSUE TITLE
Only weight measured on SBF70

### ISSUE THREAD

**Issue by ivvv** [oliexdev/openScale#203]
I have read the FAQ on this problem but it does not solve it. Here is what I did, using the latest development build (but also tried the same with the google store one). The following steps were done **on both** phones that connect to SBF70 (mine and my wife's):

1. Remove any existing user from `openScale`
2. Completely remove the legacy SBF70 app (health coach)
3. Reset the scale with the button, until I see `DEL` on the display. 
4. Open the `openScale` app and add a new user
5. Open bluetooth settings and connect to SBF70, selected `search for scale at startup` and `automaticaly assign user`.
6. Bluetooth connection is established and it starts measuring.
7. At the end, only the weight appears on the SBF70 display and in `openScale` table.

What am I doing wrong? Do I need to do something else at some point?

Thanks for the good work!

**Comment by oliexdev** [comment]
look into the issue #153 or search for other issues.
