### ISSUE TITLE
can get weight scale's fat rate data ?

### ISSUE THREAD

**Issue by oceanpad** [oliexdev/openScale#214]
https://github.com/oliexdev/openScale/blob/65824e8ed2f8196aefc924ef8c2f187ddebe46cd/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java#L208

**Comment by erijo** [comment]
See https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale
