### ISSUE TITLE
Measurement sorting isn't optimised for the dark theme 

### ISSUE THREAD

**Issue by hirnsushi** [oliexdev/openScale#215]
Just a small papercut…
![screenshot_20180307-115244](https://user-images.githubusercontent.com/5706729/37095135-5da6526a-2215-11e8-87e8-aa9a005698b7.png)

**Comment by erijo** [comment]
This should be fixed in d4a968d. You can try the dev version of you want to verify it: https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

**Comment by hirnsushi** [comment]
Aaah, should have looked at the past commits, sorry.
Tested and works, closing this.
