### ISSUE TITLE
Feature Request: Make the graph on the overview page adjustable

### ISSUE THREAD

**Issue by hirnsushi** [oliexdev/openScale#225]
With muliple types of measurements enabled, the graph on the overview page basically defaults to a straight line.
Maybe it could get it's own settings for showing / hiding of measurements or inherit the options chosen in the diagram tab.

**Comment by oliexdev** [comment]
done with commit https://github.com/oliexdev/openScale/commit/06549f5b3f1a4f510c298ad3584150c1d1f483ea
But currently you have to recreate the overview page (e.g. rotate the smartphone) to see an effect.

**Comment by hirnsushi** [comment]
Took me a moment to find the new settings, but looks and works great 👍
Thank you! 😃
