### ISSUE TITLE
The last n days, with a fixed max and min?

### ISSUE THREAD

**Issue by rangzen** [oliexdev/openScale#231]
Hello,
First thanks for openScale!
I can't find a way to see the last 30 or 90 days with a fixed maximum and a fixed minimum weight. I always have to zoom, to translate the diagram, etc. And when an objective is filled I can't zoom around, it's like a fixed minimum (yeah, I'm above :) )
Is it possible actually?

**Comment by oliexdev** [comment]
Sorry I don't really know what you mean. Can you do some screenshots?

**Comment by oliexdev** [comment]
Seems not a real problem so I will close this issue.

**Comment by rangzen** [comment]
Sorry, updates was in spam folder...
I want to fix a minimum and/or a maximum for the Y axis, actually the diagram take the max and min value.
And a number of days of history, actually it's the start of the year. In january I don't have any history visible.

For example, with 70kg min, 80kg min and 90 days of history, the diagram will look like that :
![example](https://user-images.githubusercontent.com/132700/38517457-5b723524-3c3a-11e8-878a-e2702d3a1aa7.png)

**Comment by oliexdev** [comment]
and what exactly is the problem with that behaviour?

**Comment by rangzen** [comment]
The actual behaviour?
