### ISSUE TITLE
add support for postprocessing of data after measuring happened

### ISSUE THREAD

**Issue by linuxlurak** [oliexdev/openScale#236]
Thanks for your great piece of software! My Beurer B700 works nicely. 

I automated my home with home assistant (https://home-assistant.io) . It would be really nice to have some kind of post processing of the measured data with support of sending the data via curl or something to my server. This would be a very generic solution so there are a lot of different cases to use this functionality.

Perhaps you could add some text boxes: one to set the servers url and some more boxes to add the links parameters. 

Idea of sending JSON: https://gist.github.com/subfuzion/08c5d85437d5d4f00e58
Idea for useing REST API: https://www.home-assistant.io/developers/rest_api/

Thanks again for all your efforts!

**Comment by erijo** [comment]
It's an interesting idea, but I see a problem with having to add the internet permission for this. One selling point of openScale is that it doesn't send the data to the cloud and not having permission to access the internet is a strong guarantee of that.

One solution to your problem could be to use the export feature in openScale to export your data in CSV format to eg Google drive (openScale can in this case write data to the cloud as it's an operation initiated by the user). Perhaps there is then some way to use ifttt or something similar to bring the data to HA.

If this works we could add an option to perform an automatic export of the data when a new measurement is added.

What do you think about this?

**Comment by linuxlurak** [comment]
Ok. That's true. Privacy is a very strong point. That was indeed a reason for me to choose openscale. And its nice and clear design.

What about an option in the settings menu to save data locally or to export it with the built in function **automatically**? So some checkbox would be nice ("[ ] automatically export data after measuring") and a text box for defining the target file. Then the user can install some third party tool and do the post processing.

Do you know an app besides the google drive app that automatically checks for a changed file and executes custom commands?

**Comment by oliexdev** [comment]
As @erijo said a direct upload function in openScale to a cloud is for privacy and license reasons no option. 

But an auto export / auto backup was already on my ToDo list for openScale. The auto backup should be configurable to a daily, weekly, monthly backup. There could be also an option to overwrite the last backup to have only one file so you can use some thirst party Apps for the post processing.

@natrius Do you have a tutorial how to set a sync process up or could you write one for the openScale wiki?

**Comment by lenucksi** [comment]
How about publishing a flavour of openScale with network-backup functions and one without, just like e.g. QRDroid did it?
I'd very much appreciate some integration into Nextcloud or similar on-premise "cloud" software.

**Comment by erijo** [comment]
If the backup feature uses the ACTION_CREATE_DOCUMENT intent as the export does, then the backup can be made to any destination that supports the storage access framework.

**Comment by oliexdev** [comment]
@lenucksi as in wrote in issue #82 an "openScale connector" would be possible. Two version of openScale with and without network function is not maintainable. Behind openScale is not a company and I already see the problem with the high possibilities of different cloud integration. You want the integration to nextcloud, the next user want the integration to GoogleFit and other one to GarminConnect and so on... Then if some company change slightly the API everything don't work anymore and who will be the user blame to? Of course openScale! But as openScale is open source you are of course free to go to implement such a function on your own as long as you comply with the GPLv3 (which some Cloud-API doesn't comply to btw).

**Comment by natrius** [comment]
Not yet a tutorial, but i will write one. Its a simple process in Nextcloud and i will try it with SyncThing and write one for that one too. Write here or can i write directly to the wiki? (Looking it up :D )

And, creating a backup on a self-chosen location with some options (how often, after every entry, etc.) is pretty good to work with imho. So, it would be easy for the user to directly integrate Nextcloud, Dropbox, whatever, but its not needed. My opinion.

**Comment by oliexdev** [comment]
@natrius please write it here or create a new issue @erijo or I will post it then in the wiki.

**Comment by oliexdev** [comment]
I implemented a first version of the auto backup in the branch tree. Please try it out. 
A selection which database should be imported is currently missing and is on the ToDo list.

**Comment by oliexdev** [comment]
I added a first auto backup version of the database in the db version. For an auto backup function with  CSV we need to define how we auto export CSV with multiple users? One simple idea is to export for each user in a separate CSV file.... but that would be a bit messy ;)
Anyway I think the auto backup could be improved and is still not done but for a first version it is ok.

**Comment by natrius** [comment]
Just to inform you: Autobackup seems to work, really nice! Infos about Nextcloud integration next week, in a new issue maybe.

**Comment by oliexdev** [comment]
@natrius thanks I added a new wiki page with your tutorial on https://github.com/oliexdev/openScale/wiki/Autosync-with-Nextcloud

**Comment by linuxlurak** [comment]
This would be great. I'm still searching for a convenient approach to export openscale data (to home assistant in my case).
