### ISSUE TITLE
It doesn't work on Beurer BF710

### ISSUE THREAD

**Issue by zachrdlapetr** [oliexdev/openScale#237]
I have tried connect application to BF710 but it doesn't work. I can see a transfer informations between application and the scale but next there is an information that it isn't possible to connect. Please, could you fix it? Thank you so much.

**Comment by erijo** [comment]
Please see this: https://github.com/oliexdev/openScale/wiki/Frequently-Asked-Questions-(FAQ)#my-scale-xyz-is-not-supported-why

Especially this link: https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale

Some work was done in #151, but as we don't own that scale we need your help.

**Comment by zachrdlapetr** [comment]
Erijo, thank you for the explanation. I have opened this issue because oliexdev wrote a comment on Google Play. He responded to the negative evaluation where a man wrote that his scale BF710 doesn't work with openScale. And oliexdev recommended him to input new issue on github.

**Comment by erijo** [comment]
I've ordered a BF710 and we'll see if I manage to make it work once I get it.

**Comment by zachrdlapetr** [comment]
Wow. Thank you so much. I appreciate it. I believe there will be a huge amount grateful people because the orginal app from Beurer is really crap.

**Comment by weliem** [comment]
The BF710 is identical to the BF700. Just add it to the list of advertisement names....and it will probably work

**Comment by erijo** [comment]
Thanks for the tips @weliem. I'll test that once I get the scale.

**Comment by magaiverpr** [comment]
I have this scale. I could test for you. How can I do that?

**Comment by erijo** [comment]
Just adding an entry to the list is not enough. Other changes are needed as well. But I have gotten it to work and will try to put something together for test.

**Comment by erijo** [comment]
Please try the dev version and let me know how it works for you: https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

**Comment by zachrdlapetr** [comment]
Yes, It does work!! Great job. Thank you. I appreciate it.

**Comment by weliem** [comment]
@erijo , nice! So apparently it is then using the same protocol as the Sanitas SBF70. Didn't expect that...

So now you could remove the Sanitas handler code and use the BF700 handler code.....if you would add their advertisement names...Nice cleanup...

**Comment by erijo** [comment]
Will do that, thanks for the hint @weliem.

**Comment by oliexdev** [comment]
@erijo could you add a photo of the BF710 scale for our wiki gallery?

**Comment by erijo** [comment]
I've done the merge now @weliem. Could you please try the [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) and see if it still works with SBF70?
