### ISSUE TITLE
[feature request] Autosave when app closes

### ISSUE THREAD

**Issue by natrius** [oliexdev/openScale#239]
Implement an option for an opt-in autosave when the app-closes. I set the backup to a folder that is synced automatically via nextcloud.
Now i have to do it manually, i would love an option like that - no clue how easy it is to implement.

**Comment by erijo** [comment]
In #236 we discussed adding an option to automatically export the measurements when a new one is added. Would that work for you as well, i.e. are you ok with CSV format or do you really want the sqlite database?

**Comment by natrius** [comment]
Thanks for the fast answer. I did not connect the other isse with that :D 

Actually i just want a kind of a backup in case somethings happenes to my cellphone. 
.csv would be perfectly fine, because its accessible through excel or libreoffice calc. It should be possible to import the file again (=restore)

Further comments in #236

**Comment by erijo** [comment]
If you have backup enabled for Android I think it automatically backs up the database. See under system settings -> system -> backup -> app data.

**Comment by natrius** [comment]
Well, i found the backup dialogue, but its empty and i don't know how to add something there. Still, thanks for the help, will research a bitmore :D
