### ISSUE TITLE
App unable to locate exported data

### ISSUE THREAD

**Issue by fabianmani** [oliexdev/openScale#240]
#### Expected behavior
I expected after exporting my details to the default folder created by the app, I should be able to import the file from the folder back to the app for further usage. 

#### Actual behavior
When I tried to import the exported file I get an error message that the file isn't found but when I check my file manager the file is there hence making me unable to import my exported file. 

#### How to reproduce
* Download and open the app.
* create a user and input your details.
* export to the default folder created by the app
* click on import. 

* Device: Tecno K7
* Operating system: Android 7.0
* App Version: 1.7.1

#### Recording Of The Bug
https://youtu.be/qrhZuOwJ52o

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/app-unable-to-locate-exported-data">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by erijo** [comment]
This is very strange. Could you try removing the backup directory first and retry the steps?

**Comment by fabianmani** [comment]
I'll try that and let you know the result.

**Comment by oliexdev** [comment]
strange but what makes me wonder that the write/read permission was not asked? 
Did you already grant these permission? Can you check if these permission are granted to openScale?

**Comment by fabianmani** [comment]
I just checked and discovered the permissions were not granted and that's
because it was not asked from the start. I granted the permission and its
now working fine.

On Apr 9, 2018 16:27, "OliE" <notifications@github.com> wrote:

strange but what makes me wonder that the write/read permission was not
asked?
Did you already grant these permission? Can you check if these permission
are granted to openScale?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oliexdev/openScale/issues/240#issuecomment-379792374>,
or mute the thread

**Comment by erijo** [comment]
It seems like a bug if it didn't ask for permission.

Can you try installing the [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) and see if it asks for permission when you try to backup?

**Comment by oliexdev** [comment]
could be possible a problem with the Tecno’s HiOS 2.0 on his smartphone which is a custom made Android OS.

**Comment by oliexdev** [comment]
I hope the problem doesn't happen anymore with the implemented file chooser dialog.
