### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [oliexdev/openScale#241]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by erijo** [comment]
I think this is something that @oliexdev should comment on, but here are my 2 cents.

Replacing the logo with something (radically) different is not something I think should be done without a lot of consideration, specially since I think the current one looks rather good. On the other hand it's hard to do this consideration without knowing what the alternatives are.

Do you have some more details on why you think a change would be good and/or a design that we can see?

If you would like to contribute something graphical (something we of course welcome) perhaps it would be easier to start with some in-app icon or ideas on how the look and feel could be improved?

**Comment by jbeguna04** [comment]
Thanks ill be proposing it today

**Comment by oliexdev** [comment]
@jbeguna04 did you change you mind?

**Comment by jbeguna04** [comment]
No sir, i still making designs for your project. I want to make you satisfied as i can

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39756566-b814b58a-52fc-11e8-8c18-e577d9440209.png)
Sorry for the wait
this is my proposal for the logo design. Im open to your suggestions
![sfswegfw](https://user-images.githubusercontent.com/35353768/39756957-e42d1620-52fd-11e8-8780-a5720ef22438.png)

**Comment by jbeguna04** [comment]
I will have some improvement on that. Please allow me to send the designs for a moment

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39867501-ce369e00-5487-11e8-9e44-209ad890cf5b.png)

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by oliexdev** [comment]
@jbeguna04 I think your first version looks better. Maybe if you rotate the needle a bit then it wouldn't look a bit better and not like a off button!?

Btw it reminds a bit of the [Arduino icon](https://www.arduino.cc/).

**Comment by jbeguna04** [comment]
Thank you for your suggestion.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39923592-e9a4fbee-5556-11e8-9102-d5a087299dad.png)
What do you think sir?

**Comment by oliexdev** [comment]
I think the new version looks better. Thanks! :+1: 

Only two small remarks. The icon with the shadow (2nd row 1st icon on your first icon version) is missing and could you write openScale with a small "o"? That would be great :smiley:  

Would you mind to post the svg files for each icon? I will try out this new icon in the next version. We will see how the reaction of the users will be.

Do you have also an idea to have a nice [feature graphic ](https://developer.android.com/distribute/best-practices/launch/feature-graphic) (1024x500px banner) for the GooglePlay store? 
See [here](https://incipia.co/post/app-marketing/google-play-feature-graphic-ideas/) or [here](https://medium.com/@incipiagabe/google-play-feature-graphic-examples-43ac8a473a2a) for some examples.

My current feature graphic looks like the following:
![openscale_funktionsgraphik](https://user-images.githubusercontent.com/10166185/39930992-6e36736c-553c-11e8-8fcf-41c36a601d36.png)

**Comment by jbeguna04** [comment]
(2nd row 1st icon on your first icon version) is missing. Im sorry sir, I cant truly understand this.
![image](https://user-images.githubusercontent.com/35353768/39931734-df4a7e0c-5570-11e8-94d9-b501c296386a.png)

**Comment by oliexdev** [comment]
The following version is missing:

![](https://user-images.githubusercontent.com/35353768/39756957-e42d1620-52fd-11e8-8780-a5720ef22438.png)

**Comment by jbeguna04** [comment]
Now i got it, here sir
![image](https://user-images.githubusercontent.com/35353768/39932257-401ccb08-5572-11e8-9e57-2e383f691253.png)

**Comment by oliexdev** [comment]
Thanks do you have a SVG version of the icons?

**Comment by jbeguna04** [comment]
[New folder.zip](https://github.com/oliexdev/openScale/files/1995979/New.folder.zip)

**Comment by jbeguna04** [comment]
sorry sir but i didnt mean to closed this. It was accident due to hanging up my conputer

**Comment by jbeguna04** [comment]
can  i create a PR for my designs sir?

**Comment by oliexdev** [comment]
sure

**Comment by jbeguna04** [comment]
thank you sir. Here is the link
https://github.com/oliexdev/openScale/pull/263

**Comment by oliexdev** [comment]
@jbeguna04 Thanks in the branch [icon_design](https://github.com/oliexdev/openScale/tree/icon_redesign) I added a slightly different icon.
It looks like the following:

![ic_launcher_openscale](https://user-images.githubusercontent.com/10166185/39938413-2fbde126-5553-11e8-859f-d6baa3fd589d.png)

I close the gap in the middle and lighten up the shadow a bit. The problem is that if the icon is really small, the details of the icon will really hard to see.

Currently, I am a bit unsure if the original icon fits better for small resolutions!? I need to think a bit more. :thinking: 

Anyway, thank your really much for your effort @jbeguna04 You did a great job! :1st_place_medal:

**Comment by jbeguna04** [comment]
I can adjust the sizes sir.

**Comment by erijo** [comment]
One potential issue I see with the new design is that to me it isn't directly obvious that the app has anything to do with a scale in the same way that it was with the old version. Is it possible to achieve that in some way?

**Comment by jbeguna04** [comment]
Sir. That proposal doesnt mean that you have to change the old icon. As what i have in mind is, my proposal can be used by an open source project that i can extend my help through this. Its up to you sir if you want to use my proposed logo someday. Thank you for your time But the  Letters o and s stands for open sclae and the mini scale illustrated on letter o

**Comment by jbeguna04** [comment]
The Project Owner by the way is performing a testing on the new icon design. Hope it can help the project

**Comment by oliexdev** [comment]
I have archived your icon design into the [repository](https://github.com/oliexdev/openScale/blob/master/doc/raw_icons/launcher_design_proposal_%20jbeguna04.zip)
Thanks again for your effort and contribution @jbeguna04 :+1:
