### ISSUE TITLE
 The last n days, with a fixed max and min? Was #231

### ISSUE THREAD

**Issue by rangzen** [oliexdev/openScale#242]
Sorry, updates was in spam folder...
I want to fix a minimum and/or a maximum for the Y axis, actually the diagram take the max and min value.
And a number of days of history, actually it's the start of the year. In january I don't have any history visible.

For example, with 70kg min, 80kg min and 90 days of history, the diagram will look like that :
![example](https://user-images.githubusercontent.com/132700/38517457-5b723524-3c3a-11e8-878a-e2702d3a1aa7.png)

**Comment by oliexdev** [comment]
please don't create a new issue if the same issue exist already.
