### ISSUE TITLE
graph axis

### ISSUE THREAD

**Issue by en1389** [oliexdev/openScale#249]
One thing I like the openScale app is the graph.
It it interesting to see my body weight changing over time.
![screenshot 26 apr 2018 10_59_58 am](https://user-images.githubusercontent.com/38743025/39341898-d085d4a8-4a07-11e8-92fa-c6222bc5ddcc.png)

But if I add other measurements (e.g. body fat) to the graph, they became flat lines.
And that is no fun.
![screenshot_20180427-103126](https://user-images.githubusercontent.com/38743025/39341847-a287f37e-4a07-11e8-9d25-17c40f19d920.png)

It is because the Y axis has to spread across all the data points. And weight and body fat are in different data range.
I suggest the graph support a secondary Y axis, So that, the primary and secondary Y axis can have different data range.
User can have option to choose which measurement data reference to which Y axis.
![210aaa](https://user-images.githubusercontent.com/38743025/39341919-f157b7a0-4a07-11e8-80d6-ba5f497e6b77.png)

**Comment by oliexdev** [comment]
you can simple hide and show diagram lines if you click on the circles in the graph page.
What do you do if you want to show your weight, your BMI and your waist in one graph?
Well, you could present a three dimensional graph but what if you want to show a 4th diagram line?
Then it will reach the limits. I think with the current option you are flexible enough.

**Comment by en1389** [comment]
I know I can hide the lines in the chart in the second page.
I am interested in the overview chart in the home page.
I am not talking about making some multi-dimensional graph. 
I would like 2 Y axis to take care low number range data and high number range data.
e.g. body weight, lean body mass can be reference to the primary Y axis with range 50-70 kg
and body fat, water, muscle, bone % can be on the secondary Y axis with 0-60% range

**Comment by oliexdev** [comment]
You can also disable the percent of some values and show it in the unit format. So it will complicated everything and hard to handle. If we add more and more options, openScale won't be easy to use anymore.
