### ISSUE TITLE
Please Clarify Hardware Support.

### ISSUE THREAD

**Issue by Penguin-Guru** [oliexdev/openScale#26]
Hello and thanks for making something great. Like you, I have been very frustrated by the lack of "non-cloud" smart devices. I would like to buy a scale to use with your app but, unfortunately, I am not technically savvy enough to understand your engineering notes. Could you please consider adding a section at the Wiki page for each hardware device to clearly outline how well it is supported by the app? The app page says Xiaomi is supported, but is it really fully supported? I would like to make sure before buying one.

Also, I would be happy to buy through your Amazon affiliate link, or something similar, if you have one. If you do not have one, it might be worth setting up. I think I am not the only person who would like to give back for your work.

You might also consider creating an email account for personal contact. Just an idea. I don't know if GitHub has a built in messaging service but I would recommend email anyway.

**Comment by oliexdev** [comment]
Hi Penguin-Guru,

thanks for your comment. Well I will not guarantee that the Xiamoni scale works but currently they are no complains about it. The best way is to try it out for yourself. If it doesn't work you can send the scale back or?

No I don't have any affiliate links or something like that. I am happy if you like the program. :)

My e-mail address is olie.xdev@googlemail.com you can find it on Google Play but I prefer to write on GitHub, maybe someone else is also interested in your question.

Best regards
oli
