### ISSUE TITLE
Incorrect measurement date on Yunmai Mini

### ISSUE THREAD

**Issue by erijo** [oliexdev/openScale#261]
Reported on Google Play by user "Leo Vlat":
> Shows incorrect date of weighing (1970). How to fix it? Device: Yunmai Mini

**Comment by erijo** [comment]
Setting the time as described [here](https://gist.github.com/conoro/f0c1d96c450a8f5cce70e2846c3686c4) doesn't match the snoop logs from #71 (and thus not how openScale does it).

**Comment by oliexdev** [comment]
fixed with commit https://github.com/oliexdev/openScale/commit/ca5e0b9cbf7d69c29e572b0ee643d683199ebb85
