### ISSUE TITLE
Add support for an activity level

### ISSUE THREAD

**Issue by oliexdev** [oliexdev/openScale#266]
Add an user option to support an activity level (e.g. 0-none; 1-average: 2-high). With this option we can  refine the BMR calculation.

**Comment by erijo** [comment]
Are three levels enough? I think I've seen that some have five (but I might be mistaken).

**Comment by oliexdev** [comment]
yeah some have five but some have three. No matter what we decide we have to convert some activity level ranges.

**Comment by erijo** [comment]
[This formula](http://www.globalrph.com/harris-benedict-equation.htm) has five levels. There are also a couple of other equations listed there that seem to use 4-5 levels.

**Comment by oliexdev** [comment]
added activity level option with commit https://github.com/oliexdev/openScale/commit/6cbdfbbe05bc6e0cfc0d4d503961024e679e7dfc

**Comment by erijo** [comment]
I think it would be easier to understand if the user activity had the levels listed by name in a spinner.

**Comment by oliexdev** [comment]
Yeah if you want you can change it to a spinner.
