### ISSUE TITLE
Add support for sleep and rise times

### ISSUE THREAD

**Issue by bontibon** [oliexdev/openScale#274]

**Comment by oliexdev** [comment]
I don't know what you mean? Can you explain it please.

**Comment by bontibon** [comment]
I mean adding a metric for what time you feel asleep and what time you awoke in the morning. Since sleep is plays a factor in one's weight, it would seem useful to track it.

**Comment by oliexdev** [comment]
Thanks for your idea but that is not the purpose of the app to track those parameters. Sorry.
