### ISSUE TITLE
Unable to set reminder on landscape mode 

### ISSUE THREAD

**Issue by adisalat2** [oliexdev/openScale#277]
Project Information
.Repository
https://github.com/oliexdev/openScale

.Project Name:OpenScale

Expected Behaviour
User should be able to set reminder time when on landscape mode

Actual Behaviour
User was unable to set reminder time in landscape because it got cut off or does  not display

How to reproduce
Download and install from fdroid
Run the app
Enable landscape mode
Change your screen orientation to landscape
Goto settings
Select reminder
Choose time
The clock failed to display

.Browser: OpenScale v1.8.1 (28)
.Operating System: Android 7.0

Recording of the bug
https://youtu.be/2PhATYmgKVc

**Comment by oliexdev** [comment]
doesn't work for me but as far as I see it is a bug by Android.
