### ISSUE TITLE
Color mismatch on the overview page

### ISSUE THREAD

**Issue by hirnsushi** [oliexdev/openScale#279]
Just a small papercut, the color of the indicator on the right doesn't match the color of the current position on the scale, it should be green.
![img_20180529_093909](https://user-images.githubusercontent.com/5706729/40644937-1e52ed66-6325-11e8-9663-fb5f4d2b6f70.jpg)

**Comment by erijo** [comment]
Good catch!

Should be fixed now. If you want to you can try the [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) to verify the fix.

**Comment by hirnsushi** [comment]
👍 checked the dev version, looks great 😀
