### ISSUE TITLE
script to import database from libra

### ISSUE THREAD

**Issue by feclare** [oliexdev/openScale#28]
I created a simple python script to transform the csv file from libra to the openscale csv format. 
https://gist.github.com/feclare/9ce446a640ac1b8854456a4da468dc05

**Comment by oliexdev** [comment]
Hi feclare,

awesome thanks for the script.

Best regards
oli

**Comment by sa5bke** [comment]
I googled importing from libra and came to this issue. The mentioned script is for python2 so I had to do some small changes to get it work in python3:

```diff
10c10
<     print("Missing file to transform\n")
---
>     print "Missing file to transform\n"
13,14c13,14
< r = csv.reader(open(sys.argv[1]), delimiter=";")
< writer = csv.writer(open("openScale_data_Libra.csv", "w"), delimiter=",")
---
> r = csv.reader(file(sys.argv[1]), delimiter=";")
> writer = csv.writer(file("openScale_data_Libra.csv", "w"), delimiter=",")
```
