### ISSUE TITLE
Idea/Request: Step counter and blood pressure trackers

### ISSUE THREAD

**Issue by leofedep** [oliexdev/openScale#281]
Hi!

The app is just amazing!!! Although, I would love to include 2 more trackers: step counter and blood pressure/oxygen saturation/heartbeats register. Since some Samsung phones (or gadgets) can measure these values, would be really useful to include them in the app.

Thanks in advance.

**Comment by oliexdev** [comment]
Thanks for your idea but the focus of openScale are the body scales. Supporting more external device trackers are currently not the aim.

**Comment by gappleto97** [comment]
Given that you now support calories and tape measurements, are you willing to revisit this? I would love to have an easy way to keep track of my blood pressure.
