### ISSUE TITLE
v1.8.1 problem with accuway scale

### ISSUE THREAD

**Issue by en1389** [oliexdev/openScale#282]
I tried out the new v1.8.1(28) with my Accuway scale.

Frist, I am happy that the Visceral fat is added.
But I found that when I stepped on the scale, the app always made 2 entries each time.
And the first entry has incorrect data, i.e. body fat, body water, muscle are all at 80%.
And the Visceral for both entries are 0.

Please check it.
![screenshot_20180528-104635](https://user-images.githubusercontent.com/38743025/40695037-f092f77c-63f1-11e8-8b0a-58ed962ab736.jpg)

**Comment by oliexdev** [comment]
can you try out the latest dev version?
Is in the original app the visceral **fat** displayed?
Please compare also the visceral fat value with the original app.

**Comment by en1389** [comment]
I tried the dev version
v1.8.1-dev_b52d9274(1527369785)
The result is the same, i.e. got 2 entries each time.

The original app has the visceral index. You can see the captured image of my previous issue (#248 )

BTW, visceral is measured as an index, not in kg or %.

**Comment by oliexdev** [comment]
Do you get the correct visceral index?
Can you post the debug log when you get two entries please.

**Comment by en1389** [comment]
The visceral read 0.00 both in the released version and dev version.
My visceral index should be around 8 or 9
You could check the screen capture of the original app and the bt hci log file in #248 

The debug log is attached.
[openScale_2018-05-29_07-56.txt](https://github.com/oliexdev/openScale/files/2057373/openScale_2018-05-29_07-56.txt)

**Comment by oliexdev** [comment]
did you connect to the scale and weight yourself while the debugging is on?

**Comment by en1389** [comment]
debug log attached
[openScale_2018-06-01_07-56.txt](https://github.com/oliexdev/openScale/files/2060725/openScale_2018-06-01_07-56.txt)

**Comment by erijo** [comment]
If you try the latest version it should be fixed.

**Comment by oliexdev** [comment]
I changed also the percentage to an index value and added the visceral fat evaluation with commit https://github.com/oliexdev/openScale/commit/93085eecb43a6996d7cf06823d3a330c2fb0d939
Please try out the latest dev version @en1389 and tell us how it works.

**Comment by oliexdev** [comment]
@en1389 could you also test your scale with different weight units?

**Comment by erijo** [comment]
It would also be interesting in seeing a debug log where you have weighed yourself with socks on (so that no fat measurement can be done).

**Comment by en1389** [comment]
I tried the latest dev version.
It is working fine, and the visceral index displayed correctly.

**Comment by en1389** [comment]
my scale supports wright unit in kg, lb, and st.
I switch the unit to lb and do the measurement.
The log file is attached.
The scale display my weight is in lb, but the data transfer to the app is still in metric.
[openScale_2018-06-03_22-19.txt.docx](https://github.com/oliexdev/openScale/files/2066609/openScale_2018-06-03_22-19.txt.docx)

**Comment by en1389** [comment]
When I step on my scale with slippers on. After displaying my weight, the scale trying to analysis my body components. And then "Error" is displayed on the scale.

Here is the log file.
[openScale_2018-06-03_22-22.txt.docx](https://github.com/oliexdev/openScale/files/2066626/openScale_2018-06-03_22-22.txt.docx)

**Comment by en1389** [comment]
my photo of the accuway scale
![dsc_0567](https://user-images.githubusercontent.com/38743025/40896584-59fbe850-67e8-11e8-9632-f4654171aa74.JPG)

**Comment by erijo** [comment]
@en1389: could try changing the unit on both the scale and in openScale to lb and verify that what you see on the scale matches what you get in openScale? Using the latest dev version.
