### ISSUE TITLE
[Request] Tasker support

### ISSUE THREAD

**Issue by Radiotechniman** [oliexdev/openScale#283]
Personally I'd like to have the option to sync to (web) services but I understand why this is not included in the app.  
Having Tasker support would allow anyone to create any integration they want.

I would automatically post data to my fitbit account (using autoWeb & Tasker) but i can see someone starting disco lights when they reach a certain weight :-)

**Comment by oliexdev** [comment]
With the openScale automatic backup function you have access to the complete database. You can backup it daily and write for example a Tasker plugin that is reading the backup file in and do whatever you want. So the support should come from Tasker not by openScale ;)
