### ISSUE TITLE
Naming of autobackup

### ISSUE THREAD

**Issue by natrius** [oliexdev/openScale#285]
Thanks for the feature - amazing! (The whole app actually)

Maybe on thing for improvement:
Change the naming from dd.mm.yy_openscale to yy.mm.dd_openscale because the default folder-sorting in windows and android will sort it chronological. That way, the newest one will always be on top or on bottom and not somewhere in the middle. 
Doint it the same way for my pictures and so on :)

**Comment by oliexdev** [comment]
thanks you point is good. It is now changed to yyyy-MM-dd. Before your short local default date was used. So for Austria or Germany it was dd.mm.yy.
