### ISSUE TITLE
Mi Scale 2 typo?

### ISSUE THREAD

**Issue by rochamorelli** [oliexdev/openScale#286]
On line 184 and 187 of [Mi Scale 2](https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java), is this a typo or the data is really used for two distinct things?

```
final boolean isDateInvalid = isBitSet(ctrlByte1, 6);
final boolean isCattyUnit = isBitSet(ctrlByte1, 6);
```

Thanks :D

**Comment by oliexdev** [comment]
I copied the source code of mi scale v1 for the v2. Then I tried to discover some differences. It could be possible that I didn't test other scale units with the mi scale v2 so the bit of `isCattyUnit` might be wrong or I did that to have a "speaking" name but I can't remember anymore. Sorry!
Why you asking? Is something not working?
