### ISSUE TITLE
Support for GBF-1251-B (by Lifesense(?))

### ISSUE THREAD

**Issue by Freso** [oliexdev/openScale#287]
Just a note that I'd love to see added support for the GBF-1251-B scale (not 100% sure who it's made by, but it only works with [an app by/from "Shenzhen Lifesense"](https://play.google.com/store/apps/details?id=com.lifesense.LSWearable.intl)).

The user manual for the scale can be seen at http://docplayer.dk/29229362-Brugsanvisning-kropsanalysevaegt.html (in Danish)

I'll try and do the [reverse engineering](https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale) at some point, but the scale seems to only want to pair or connect while the app is open… And the authentication/login system for the app (at lifesense.com) doesn't seem like it's responsive at the moment.

**Comment by oliexdev** [comment]
Could be possible that you only get the impedance and weight value like for the mi scale v2 or 1byone scale but we will see if you did some reverse engineer steps.

**Comment by erijo** [comment]
A good start is to enable debug log in settings -> about and then search for the scale in bluetooth settings. Once found, click it and openScale will download some debug data. Then post the log here.

**Comment by oliexdev** [comment]
I will close this issue due inactivity.
