### ISSUE TITLE
muscle mass is to high

### ISSUE THREAD

**Issue by Teyro** [oliexdev/openScale#288]
Hi there,

Is there a chance to increase the "muscle mass" scale? My Girlfriend has muscles like Hulk but she looks awsome.... But at 44% the scale is over.... Is there a chance to increase the Value for Hulk like girls?

best wishes from Hamburg, Germany

Teyro

**Comment by oliexdev** [comment]
which scale? But anyway I am not a manufacture of a scale, you have to ask the company of your scale. 
Alternative you can enter the muscle mass manually in openScale.

**Comment by erijo** [comment]
@Teyro: do you mean that 44% is considered too high muscle value (i.e. marked as red by openScale)?
