### ISSUE TITLE
Goal weight not displayed properly in Chart and statistics.

### ISSUE THREAD

**Issue by faisal-shah** [oliexdev/openScale#292]
v1.8.1 (28)

In user configuration I have my scale unit set to lb, and my goal weight set to the appropriate value in lbs.
When I view Chart and Statistics, it shows my goal weight as the number I have in my profile converted to the numerical equivalent in kgs. As a result, derived values are also incorrect, such as Weight Difference. 

For example, I put a goal weight of 150lb in my user profile. On Chart and Statistics it shows a goal weight of 68.0 lbs.

**Comment by erijo** [comment]
The statistics bug is already fixed (see #272), but the graph bug remains.

**Comment by erijo** [comment]
Should be fixed now. If you want to can verify it by testing the [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build).

Thanks for the report!

**Comment by faisal-shah** [comment]
Thanks for the app! Glad to be able to contribute in a small way.
