### ISSUE TITLE
Request: Make a component for Home Assistant

### ISSUE THREAD

**Issue by godinperson** [oliexdev/openScale#296]
I don't always have my phone on me. It would be nice if we could create a component for Home Assistant https://www.home-assistant.io

The Home Assistant would scan for a connection with the scale and if it receives data, would add it. It would be easy to keep my history under my home automation software

**Comment by erijo** [comment]
Seems like this would be a new project, separate from openScale.

**Comment by godinperson** [comment]
In fact, it would be a port of your application into a component, not interested? I can put it in Home Assistant component request if you like

**Comment by basboers** [comment]
Anyone connected this to HomeAssistant yet?
