### ISSUE TITLE
Diagram view: Increase month selector minimum height

### ISSUE THREAD

**Issue by hirnsushi** [oliexdev/openScale#299]
It's very hard to select a month with very few measurements, would be great if you could set a minimum height for those bars.
Examples:
![screenshot_openscale_ dev _20180701-083415](https://user-images.githubusercontent.com/5706729/42181742-3b1fe76e-7e3c-11e8-967f-0dd5a0d95365.png)
1 measurement, nearly impossible to select.
![screenshot_openscale_ dev _20180702-160439](https://user-images.githubusercontent.com/5706729/42181743-3b40e374-7e3c-11e8-8bbc-ca29e6817336.png)
2 measurements, still very hard to hit.

**Comment by oliexdev** [comment]
Unfortunately, the library that we are using doesn't support that and it is not maintain anymore.
I am not sure how we can best solve this issue... any ideas?

**Comment by hirnsushi** [comment]
Is the value shown on the bars linked to the bar height somehow? If not, would it be possible to increase the number of measurements in the background by x and use the real amount of measurements minus x for the value on the bars? I've obviously no idea how this is implemented, so just a thought 🙂

**Comment by breversa** [comment]
Time to refactor the graph view then, and switch to a maintained library (if there's any...) ?

**Comment by oliexdev** [comment]
@hirnsushi could be solution. More a hack but could work :wink: 
@breversa not for that one reason but if you have a good alternate you could suggest another library which doesn't lack at design.

**Comment by oliexdev** [comment]
@hirnsushi please try out the latest dev build. Now the minimum height should be 20% of the maximum value.

**Comment by hirnsushi** [comment]
Perfect! 👍
