### ISSUE TITLE
Maximum allowable percent body fat

### ISSUE THREAD

**Issue by patzzz** [oliexdev/openScale#30]
This app is very useful to obese persons, but in 1.5 version the maximum allowable percent body fat is 40% and it is insufficient to them.
In 1.4.3 version I could add higher values without problems.

This study reveals that in females, mean percentage body fat ranged to 42.4% at age 60-79 years.
https://www.cdc.gov/mmwr/preview/mmwrhtml/mm5751a4.htm

Is possible rise maximum allowable percent body fat to 45%?

Thanks.

**Comment by oliexdev** [comment]
Hi patzzz,

thanks for your hint. It forgot to change the maximum value while I refactoring the source code. Now I changed the maximum fat percentage to 80% with commit https://github.com/oliexdev/openScale/commit/b7befd8aa8837375d29e93bd69cdd7fa2da1b0ef

Best regards
oli
