### ISSUE TITLE
Request to make contributions to openScale.

### ISSUE THREAD

**Issue by HarryHeights** [oliexdev/openScale#308]
Hello!.. 
I'll love to contribute to your project in documentation. I'll draft a privacy policy and also compile a list of Frequently asked questions(FAQs).
It'll be great thing if prospective users know what information they'll be parting away with while using the software and how that information is utilized. The FAQs will solve some usage problems for prospective users. 

I'll be anticipating your reply.

**Comment by HarryHeights** [comment]
Alright. I already made a proposition though. If by proposals you mean compiling the document and submitting it for review, I'll do that right away.

**Comment by oliexdev** [comment]
sure propose your documentation. I cannot promise to you I will use it but I will look into it.

**Comment by HarryHeights** [comment]
Oh okay. I'll get back to you real soon.

**Comment by oliexdev** [comment]
I will close this issue due inactivity.
