### ISSUE TITLE
Add measurements in 1-step again

### ISSUE THREAD

**Issue by patzzz** [oliexdev/openScale#31]
In 1.4.3 version I could add all measurements in 1-step and old values could be edited in the same screen, for example change only decimals:
![1 4 3](https://cloud.githubusercontent.com/assets/25534423/25564928/fcfa09ee-2dbd-11e7-88ed-c6586c9395c4.png)

But in 1.5 version I need 5-steps and old values aren't editable.

First step to add weight:
![1 5_step_1](https://cloud.githubusercontent.com/assets/25534423/25564933/19bba6a0-2dbe-11e7-9a8d-583f59e0be44.png)

Second step to view old values:
![1 5_step_2](https://cloud.githubusercontent.com/assets/25534423/25564934/1fb12cb0-2dbe-11e7-96a0-6d9f9d987a5b.png)

Third step to add water percentage (you can't change old value):
![1 5_step_3](https://cloud.githubusercontent.com/assets/25534423/25564935/258e2a2a-2dbe-11e7-8584-646494f0fe74.png)

Fourth step to add muscle percentage (you can't change old value):
![1 5_step_4](https://cloud.githubusercontent.com/assets/25534423/25564937/2c48dcc0-2dbe-11e7-943b-8b8be599e7ed.png)

Fifth step to add body fat percentage (you can't change old value):
![1 5_step_5](https://cloud.githubusercontent.com/assets/25534423/25564938/31d9c870-2dbe-11e7-849a-8296d1856d69.png)

Is possible change it again to 1-step changing old values?

Thank you very much.

**Comment by oliexdev** [comment]
Thanks for your comment. That is true that you can't change easily the position after decimal point, so I will show the old value in the edit text with the commit https://github.com/oliexdev/openScale/commit/b7befd8aa8837375d29e93bd69cdd7fa2da1b0ef . But I am not quite sure if it's better or worse to have an edit text instead of an input dialog.

**Comment by patzzz** [comment]
The 1-step screen of 1.4.3 version was perfect for me, but perhaps a setting to add measurements in old-style or new-style (with multiple screens and an empty text dialog) would be perfect for all.

Thank you for this fantastic app.

**Comment by oliexdev** [comment]
let me think about that which method is better but I don't want to have two input modes.
