### ISSUE TITLE
Add overall overview

### ISSUE THREAD

**Issue by natrius** [oliexdev/openScale#313]
Add an overview over all input data. It would be nice to see the whole picture over a longer period of time. On the top right is the option for weekly and monthly, add new one for "overall" for example.

And a good one would be "defined range" so if i want to show someone something special that would be nice too.

**Comment by sik0vny** [comment]
I agree on this one.

**Comment by oliexdev** [comment]
please test the latest openScale branch build of [MPAndroidChart](https://github.com/oliexdev/openScale/releases/tag/travis-dev_MPAndroidChart-build)
