### ISSUE TITLE
Add support for Yunmai Premium Smart Scale

### ISSUE THREAD

**Issue by thoth291** [oliexdev/openScale#316]
Yunmai app sucks - your one looks exactly what I need, but it doesn't seem to support my scale. Please help.

**Comment by oliexdev** [comment]
I would like to support this scale but I guess it has the same problem as the yunmai mini scale, please see issue #71

**Comment by oliexdev** [comment]
You can also manually enter your weight and estimate your body measurements with openScale ;)
I will close this issue until we can resolve the puzzle in issue #71.

**Comment by oliexdev** [comment]
Please enable the log under the settings-about debug and post it here (read the wiki for details)

**Comment by OrcaXS** [comment]
[openScale_2018-11-27_18-57[1].txt](https://github.com/oliexdev/openScale/files/2619575/openScale_2018-11-27_18-57.1.txt)
Here it is.

**Comment by oliexdev** [comment]
@OrcaXS try out the latest [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) and post the log file here.

**Comment by OrcaXS** [comment]
[openScale_2018-11-27_18-57[1].txt](https://github.com/oliexdev/openScale/files/2619687/openScale_2018-11-27_18-57.1.txt)
Looks like it's working fine!

**Comment by oliexdev** [comment]
Good but you posted the same log file again. ;)

**Comment by OrcaXS** [comment]
[openScale_2018-11-27_19-30[1].txt](https://github.com/oliexdev/openScale/files/2619705/openScale_2018-11-27_19-30.1.txt)
Oops... that was the cached file from MTP on Windows
