### ISSUE TITLE
Add support YNUMAI Mini 2 SCALE (YNUMAI-ISM2-EN)

### ISSUE THREAD

**Issue by Danix58** [oliexdev/openScale#317]
I find a Ynumai mini 2 scale that is not supported. I'm very insteresting in openScale.

The device name identified by BLE scanner is: **YNUMAI-ISM2-EN**  (3C:A3:08:97:33:F0)

**20-08-2018 13.36**
`0d:1f:14:02:00:5b:7a:a7:a2:23:d8:82:ea:1e:01:01:bb:05:28:36  // weight: 76.8 Kg 13.2 Body fat`
1e:01 = 76.81 kg
05:28 = 13.2 % body fat

The protocol is the same of BluetoothYunmaiSE_Mini.java. #71 
Please help.

[mini2](https://user-images.githubusercontent.com/42542269/44342612-e2f64580-a48b-11e8-8525-d4aa0e7f9015.jpg)

**Comment by oliexdev** [comment]
please try out the latest [dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build).

**Comment by Danix58** [comment]
I try th new dev version. Now i can find my scale. Thanks

**Comment by oliexdev** [comment]
and does it work?

**Comment by Danix58** [comment]
Yes, it works

**Comment by oliexdev** [comment]
great :smile: 
Does your scale support other body measurements like water and body fat percentage?
Could you post an image again but with the same camera angle like the one in out wiki gallery?

**Comment by Danix58** [comment]
![img_20180821_092219_resized_20180821_092249515](https://user-images.githubusercontent.com/42542269/44387755-a62b5c80-a526-11e8-9fdd-3155cb6815e5.jpg)

The scale have these body mesaurements:
![screenshot_2018-08-21-09-18-43-908_com yunmai scaleen](https://user-images.githubusercontent.com/42542269/44387822-db37af00-a526-11e8-9c4a-39f919d23164.png)

2018-08-21 09-17 (76,22 kg and 13.1 body fat)
`0d:1f:14:02:00:5b:7b:bc:83:23:d8:a0:99:1d:c6:02:09:05:1e:1f`
1d:c6 = 76.22 Kg
05:1e = 13.1 body fat

**Comment by naor88** [comment]
I'm also try install the dev build (openScale-1.8.1.apk and latest) and at both can't find the device..
@Danix58 What type off android phone and OS version you use?
