### ISSUE TITLE
New View with Moving Average

### ISSUE THREAD

**Issue by wangeleile** [oliexdev/openScale#322]
When you measure daily your weight, you will see a volatile curve, with +- 2kg without changing your diet. 
Reason is simple: water, Food, etc. 

To eliminate this, there is an approach to weigh your measures over the last 10 measures. so called moving average. 

So, I don't know how complex this is to program, but it would be a great added value to have this option in openScale. 

More details and example: 
1. https://play.google.com/store/apps/details?id=net.cachapa.libra (an app which does this, but is not supported anymore)
2. The guy who invented this approach: https://www.fourmilab.ch/hackdiet/e4/
3. A web solution which use the moving average: https://trendweight.com/

**Comment by oliexdev** [comment]
If you weight yourself multiply times on the day the average value will be displayed. If you show the week the average of the week will be displayed. The same goes with the month and year. In my opinion weight variations are already eliminated. Additionally, you can add a "trend" line by adding a regression line. 
If we use your approach we would destroy the current diagram design which I am currently not prefer.
