### ISSUE TITLE
Xiaomi Mi scale v2

### ISSUE THREAD

**Issue by itge13** [oliexdev/openScale#324]
Please make the rest of the data also available

**Comment by oliexdev** [comment]
see issue #150

**Comment by itge13** [comment]
So no chance in near future? Is there a way to copy the data from the Mi Fit app?

**Comment by oliexdev** [comment]
sure there is a chance but it takes some time. You could enter manually the measurement from the mi fit app :wink: no seriously you can't copy the data from the mi fit app or do they have an export function? Then maybe you could import it via the CSV import by openScale.

**Comment by itge13** [comment]
Nope, no export function but the data is stored anywhere on the phone (shows the data even in flight mode) so there is maybe a way.

**Comment by oliexdev** [comment]
yeah in the database but you don't have access to another database if the app doesn't allow it. Would be a security nightmare if this would be general possible.
