### ISSUE TITLE
There should be a separate unit for each scale, in addition to user prefered unit.

### ISSUE THREAD

**Issue by 0e318236-1680-41a8-a989-3c9227637cdf** [oliexdev/openScale#326]
My Yunmai Signal M1US  Scale displays in pounds, (xxx lbs), and openscale unit is lb, but when the data is synced, it shows the kilograms value as pounds, (yy lbs). If i plug in 'yy to pounds' in google, I get xxx lbs.

A workaround is to set openscale unit to kg when syncing data, and when you need to look at charts for actual values, manually toggle over to lbs. This thens converts the kg units to lb correctly, but only for old data.

The issue appears that openscale does not support automatic conversion of units from scale (kg) that is different from the user preference (lb).

As an aside, yunmai app is very invasive, but I changed the units of physical scale from kg, to lb to no effect in openscale. It looks like yunmai app recieves kg over bluetooth, even though it displays lb on scale, and lb in yunmai app.

**Comment by erijo** [comment]
This has been fixed on master (in 7c2573f8135) and will be included in the next version. If you want to you can test the [development build](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build) to verify that it works.
