### ISSUE TITLE
Scale Support Medisana BS 444 connect

### ISSUE THREAD

**Issue by Auctoritas-Dirk** [oliexdev/openScale#329]
That device does Not work with his own App.

**Comment by oliexdev** [comment]
I don't know what you mean? Does your Medisana BS 444 scale doesn't work with openScale or with the vendors app? What doesn't work?

**Comment by Auctoritas-Dirk** [comment]
Korrektur:
Ich hatte ursprünglich Probleme mit der Verbindung mit dieser Waage - jetzt
funktioniert es meistens, ich teste noch.
Ich habe eine weitere Waage gekauft, YUNMAI MINI 2, mit dieser hat es kein
enziges Mal funktioniert, ich teste aber noch. Die App zeigt verbinde (auch
dann wenn die Batterien raus sind)
Ich vermute, das ich den Bluetooth key brauche

Am Fr., 28. Sep. 2018 um 14:32 Uhr schrieb OliE <notifications@github.com>:
