### ISSUE TITLE
How to get body fat from impedance and body weight on Renpho scale ?

### ISSUE THREAD

**Issue by YilmazTasdelen** [oliexdev/openScale#331]
I'm using Renpho scale I get the value :10:0b:15:22:fb:01:01:fc:01:f8:44
22 fb is  weight
01 FC is impedance
10:0b:22 is always same 
01:f8:44 can't understand this part of my value
I need to know how to calculate bodyfatand body water. I found OpenScale formulas but the OpenScale result doesnt match with Renpho scales app result.

**Comment by oliexdev** [comment]
please read https://github.com/oliexdev/openScale/issues/291#issuecomment-425615095

It's not easy but it is possible.
