### ISSUE TITLE
SBF70 connects successfully with openScale but get no data from it

### ISSUE THREAD

**Issue by studioart** [oliexdev/openScale#347]
Hi,

meanwhile when starting openScale it says, that it has successfully connected to the Sanitas SBF70 scale. 
But it does not get any data from it.
Yes, username is the same in openScale and in the vendor app.

How can I do this please?

- Samsung Galaxy Note with Android
- openScale latest version
- Sanitas SBF70 scale

**Comment by oliexdev** [comment]
do the steps in issue #335 and post back if it works
