### ISSUE TITLE
[FR] Skip entering some fields

### ISSUE THREAD

**Issue by woj-tek** [oliexdev/openScale#349]
Currently, the only way not to enter values for some fields is to disable them completely in options. It's impossible to remove value (in form) or to clear it from main entry screen (with multiple fields, with long tap for example)

**Comment by oliexdev** [comment]
you can also reorder it. I think that is enough. I don't see a problem. If you don't use a measurement disable it. If you want to skip it in one measurement just click next.

**Comment by woj-tek** [comment]
Thanks, I ended up disabling it. Clicking 'next' would simply put calculated value which is slightly different than no entry.
