### ISSUE TITLE
Vitalmaxx scale support (icomon)

### ISSUE THREAD

**Issue by cyroxx** [oliexdev/openScale#370]
I just tested with the Vitalmaxx scale and I successfully got both body weight and the body metrics into openScale.
The Vitalmaxx shows up as icomon and as you seem to have icomon support already, is it safe to assume that the values are correct? I didn't test against the official app because of privacy concerns. 

Official App:
https://play.google.com/store/apps/details?id=com.icare.iweight&hl=de

Scale:
https://www.maxx-world.de/alle-kategorien/fitness/vitalmaxx-korperanalysewaage-bluetooth-schwarz-mit-gesundheits-app

**Comment by oliexdev** [comment]
it looks like it use the same firmware as the MGB scale. I can't say if the values are correct. I don't own these scales but people with the MGB scale are not complaining that these are incorrect.
