### ISSUE TITLE
not receiving data from Yunmai mini

### ISSUE THREAD

**Issue by SarahDal** [oliexdev/openScale#372]
My Samsung Galaxy S9 pairs with my Yunmai and I am able to add the device in OpenScale, however beyond that I can't get any data from the scale. I feel like I've missed a step! the scale speaks to the Yunmai app no problem.

I have reinstalled openscale, rebooted phone, uninstalled the Yunmai app.

**Comment by erijo** [comment]
Have you clicked the Bluetooth icon in the app's main view? That's needed to make the app connect to the scale and fetch measurements.

**Comment by SarahDal** [comment]
Thank you for your quick reply, and happy new year! There doesn't appear to be a bluetooth icon in the main view.

![screenshot_20190101-095752_openscale](https://user-images.githubusercontent.com/46293785/50571841-e8558c00-0dab-11e9-840f-d39a03d4cf38.jpg)

**Comment by erijo** [comment]
For some unknown reason the button is sometimes black. Try clicking just left of the "+" button.

**Comment by SarahDal** [comment]
yep that's solved it - thank you!
