### ISSUE TITLE
[FR] Mood tracker

### ISSUE THREAD

**Issue by OffifialMITX** [oliexdev/openScale#377]
Would it be possible to include a mood tracker that can be used mixed or separately from the app's current main functionality? I am looking for a F(L)OSS app with that functionality, but couldn't find anything yet, and from what OpenScale does, it appears that this wouldn't require any big changes in the code.

I understand though, if this is not what you want to achieve and you wouldn't want to do that.

**Comment by erijo** [comment]
You could use emojis in the comment field for this.

**Comment by OffifialMITX** [comment]
Of course, but I'm looking for something that can show me statistics, and I'd like it if it w

On January 13, 2019 4:09:14 PM UTC, Erik Johansson <notifications@github.com> wrote:
>You could use emojis in the comment field for this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/oliexdev/openScale/issues/377#issuecomment-453842217

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oliexdev** [comment]
It is not the goal of openScale to track the mood of the user.
You could learn to program your own Android app and create an open-source Mood tracker app. But I see you did also ask other projects to implement this feature. Maybe they are willing to do it.
