### ISSUE TITLE
Rotation lock not working

### ISSUE THREAD

**Issue by kapitaniglo11** [oliexdev/openScale#39]
Application is not respecting Android's Portrait/Landcsape lock.

After rotating the mobile it rotates the screen not keeping system's rotation lock.

**Comment by oliexdev** [comment]
thanks for the hint. It is fixed with commit https://github.com/oliexdev/openScale/commit/b03f58f66be266b8cd3e47baf9382ed2e18b1ef5

It was old code that was not necessary any more which made the problem.
