### ISSUE TITLE
The reminder doesn't work

### ISSUE THREAD

**Issue by cao-** [oliexdev/openScale#394]
I receive no notification as reminder to weight in at the set time.  When I used this app some time ago (approximately a year ago), it used to work.  Now it doesn't work anymore.  But I don't know what to give you so that you can spot where the problem is.  Tell me.

**Comment by oliexdev** [comment]
could you disable and enable the reminder in openScale? Does it work then?

**Comment by cao-** [comment]
I tried it again.  It doesn't work, both when the app is in the background and in the foreground.

**Comment by oliexdev** [comment]
Unfortunately, I can't reproduce it, on my phone it works. I didn't change anything for the reminder function in the source code but in the new Android version you can revoke notification for apps!? Did you disable it in Android?

**Comment by cao-** [comment]
Yes!  I'm on Android 8.
I've tested the latest dev build and it works!  Good job.  Thank you!
