### ISSUE TITLE
Overview graph should have fixed range

### ISSUE THREAD

**Issue by ivoid** [oliexdev/openScale#413]
For the new Overview graph in version 2.0, I feel that it should be a fixed range of dates (similar to version 1.x, or maybe configurable) and not be scrollable and zoomable. If it's scrollable like now then the vertical axis should scale dynamically to the data points that are being shown.

My problem is that the Y-axis is scaled to my entire weight range dating back to 2017 with a difference of around 15 kg, as a result the current weight is a flat straight line at the very bottom of the graph.

Thanks and keep up the good work.

**Comment by oliexdev** [comment]
use the fragment graph for fixed range or disable the rolling chart.

> My problem is that the Y-axis is scaled to my entire weight range dating back to 2017 with a difference of around 15 kg, as a result the current weight is a flat straight line at the very bottom of the graph.

It depends if the graph library supports that. You are welcome to send a PR
