### ISSUE TITLE
Turning off lines from measurement bar in overview page

### ISSUE THREAD

**Issue by ivoid** [oliexdev/openScale#414]
If all the lines in the graph are turned off using the measurement bar then there's no way to bring them back. X-axis is shown but Y-axis is blank and no graph appears.

Thanks and keep up the good work.

**Comment by oliexdev** [comment]
I don't really understand you can bring it back if you enable it again!?

**Comment by ivoid** [comment]
It only happens if rolling chart option is enabled.
My normal overview page.

![image](https://user-images.githubusercontent.com/7450497/53372436-6fc31400-3985-11e9-864e-65a5cb16ffda.png)

All lines turned off.

![image](https://user-images.githubusercontent.com/7450497/53372450-7487c800-3985-11e9-93a2-f1f19f890709.png)

Turn back on, no lines appear. The lines will only re-appear after toggling any of the options in the graph's display option menu.

![image](https://user-images.githubusercontent.com/7450497/53372457-781b4f00-3985-11e9-8c3f-b28248859cfc.png)

**Comment by oliexdev** [comment]
can't reproduce it. Did you test it with the latest dev version?
