### ISSUE TITLE
Data import seems to be broken.

### ISSUE THREAD

**Issue by WinMinerGMX** [oliexdev/openScale#415]
~~I wasn't happy with how v2.0 displays the graphs so I wanted to downgrade to an older version which still has the graph scaling that I like. So I exported the data (openScale User.csv) through the export menu (in v2.0) and downgraded to v1.9.3 through Fdroid.~~

~~Import of data doesn't seem to do anything. Chart says: No chart data available and the user doesn't get recreated. So I tried to import with v2.0 again. Same issue. No Info in FAQ, Wiki, Issue-Tracker or anywhere else. I also tried to recreate the user first but no deal.~~

~~Any help?~~

~~Update: Now I managed to export something in "SQLite format 3" but I am uncertain how. Can't seem to export CSV anymore. No idea what's going on here.~~

**Okay turns out there are two import/export dialogs, the one in the settings menu and the on in the diagram (graph) view. These two don't seem to do the same thing.**

**The import/export dialog in the settings menu seems to export "SQLite format 3" and stores _probably user and programm settings(?)_**

**The import/export dialog in the diagram view seems to export CSV files and stores only graph data and a (previously created) user must be present to import data into the diagram.**

**Guess this "issue" resolved itself. PEBCAK. :P**

**Comment by WinMinerGMX** [comment]
Importing with user already created yields the error message displayed in the screenshot.

![screenshot_2019-02-25-10-27-16](https://user-images.githubusercontent.com/34789416/53327442-1b1d8b80-38e8-11e9-91de-928d12ccbd7e.png)

**Comment by oliexdev** [comment]
good observation :wink:
