### ISSUE TITLE
Senssun scale

### ISSUE THREAD

**Issue by quthla** [oliexdev/openScale#417]
When weighing one time, since latest version it'll insert dozens of measurements with all the same values.

**Comment by gmarco** [comment]
i'll take a look at it next days.there was changed a lot.

**Comment by voyager** [comment]
Just to illustrate what @quthla referred to:

![screenshot_20190304_001553_com health openscale](https://user-images.githubusercontent.com/457281/53702829-e17ee000-3e13-11e9-8148-ff47f32642eb.jpg)

**Comment by quthla** [comment]
> 
> 
> Just to illustrate what @quthla referred to:
> 
> ![screenshot_20190304_001553_com health openscale](https://user-images.githubusercontent.com/457281/53702829-e17ee000-3e13-11e9-8148-ff47f32642eb.jpg)

That's exactly it. Also the values are not all the same. The first few measurements have partially old values but following measurements then only have current values.

**Comment by voyager** [comment]
It seems that the app does not consolidate the feed and then enters the last value, but instead saves all the incoming values, almost like it's saving raw feed, as now one can see the table being live-fed and expanded with new rows while the app is connected to the scale.

**Comment by quthla** [comment]
@oliexdev Is this caused by your new BT state machine?

**Comment by gmarco** [comment]
yes the last changes break the function. i'll try to fix this today.
The Scale is sending continous the weight (thats why the many saves)

**Comment by IronJunkie** [comment]
Sorry, above ref is not valid to this issue.
