### ISSUE TITLE
missing statistics in statistics-tab

### ISSUE THREAD

**Issue by john-bill** [oliexdev/openScale#422]
Hi,
I really would like to get the weight-average statistics back in v2.x.
Comparing weight-per-week to weight-per-month was on of the best features in v1.x, now I have two (at least for me) unreadable diagrams without the statistics information.
Is there a chance to get this (and maybe some other statistics) back?

**Comment by oliexdev** [comment]
click on the diagram then you will see the values!?

**Comment by john-bill** [comment]
in both diagrams (which look exactly the same) I only get the exact same actual data, nothing per week or per month.

**Comment by oliexdev** [comment]
then your average for last month and week are the same

**Comment by oliexdev** [comment]
both diagram are compared with your last measurement

**Comment by john-bill** [comment]
average for month and for week are different! But this is not reflected in the diagrams nor do I see anything besides the actual measurement in it.

**Comment by gappleto97** [comment]
Agreed, this seems to be a bug. My weekly should be 182.3, yet it shows 181.6, which happens to be the most recent measurement, and also what monthly shows.
