### ISSUE TITLE
Add FITINDEX ES-26M To Supported Scales Wiki

### ISSUE THREAD

**Issue by srwareham** [oliexdev/openScale#434]
The FITINDEX ES-26M scale is supported by openScale and was used to develop the QN-Scale implementation. I've attached to this issue an image of the scale, along with a link to an appropriately modified [Supported-scales-in-openScale.md](https://raw.githubusercontent.com/srwareham/openScale/wiki_additions/Supported-scales-in-openScale.md) (if I understand correctly it isn't possible to PR to the wiki itself).

![fitindex_es26m](https://user-images.githubusercontent.com/3392952/54042872-28186580-4199-11e9-80c1-17d66a0e1d80.jpg)

Thanks!

**Comment by oliexdev** [comment]
thanks for the image. Yes, users can't edit the openScale wiki. Unfortunately, I commited the image into the wrong branch. Will be later automatically fixed if the branch will be merged.
