### ISSUE TITLE
Improvement: Order of openScale users

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#44]
When you add a new user to openScale, it goes to the top of the user list and the user drop down menu. I would expect that the list is ordered from old (top) to new (bottom). I think the main reason for creating two or more users is the smart assignment filter function. And the first created user is probably the most (or even the only) important one since it is created when you start openScale for the first time. Being able to manually move the users up and down would be nice too.

**Comment by oliexdev** [comment]
it is fixed with commit https://github.com/oliexdev/openScale/commit/4a34cdc6dbfe6b1813755a474a4fc71a26f2493c
