### ISSUE TITLE
Purchase links for supported scales

### ISSUE THREAD

**Issue by gappleto97** [oliexdev/openScale#444]
Hi,

I was wondering if it was possible to provide store links on the wiki. After spending some time, I was unable to find most of them on major platforms like Amazon (except one on German Amazon), so it would be useful to know where to get them.

Apologies if this is a bit silly, but I guess my Google-foo wasnt up to the task. Im sure I am not the only one.

**Comment by oliexdev** [comment]
I don't know where to buy the scales either. If I would know it would also be valid for some countries, so it is better that everybody look out for their favourite shop if they are available.
Some scales used the same chip set, some are only different in the name and so on.
