### ISSUE TITLE
y-axis values cropped

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#45]
I found out that different conditions lead to cropped y-axis values:

1) weights over 100kg:
![screenshot_20170601-043331](https://cloud.githubusercontent.com/assets/28578876/26749157/30ea80f0-4806-11e7-971b-b68351e80bc8.png)
![screenshot_20170601-043613](https://cloud.githubusercontent.com/assets/28578876/26749161/493fbaa8-4806-11e7-80fb-3a7db1f99618.png)
![screenshot_20170603-001322](https://cloud.githubusercontent.com/assets/28578876/26749173/5bfe256c-4806-11e7-8e00-6569b9e88baf.png)

2) very small changes of weight:
![screenshot_20170603-012133](https://cloud.githubusercontent.com/assets/28578876/26749188/7b2b7994-4806-11e7-8f85-c8015e4ff398.png)

**Comment by oliexdev** [comment]
it is fixed with commit https://github.com/oliexdev/openScale/commit/88def160b7c0172d1f15008adb143897f6a7b0fe
