### ISSUE TITLE
Import from Mi Fit support

### ISSUE THREAD

**Issue by recod4** [oliexdev/openScale#463]
**Is your feature request related to a problem? Please describe.**

I've been using Mi Fit for quite a while before discovering openScale and have a lot of data that I don't want to lose. So what about ability to import that data from Mi Fit?
I've got all the measurements in .csv file.

**Describe the solution you'd like**

You can export Mi Fit data already in .csv format, so the ability to import it to openScale would be great.

**Comment by oliexdev** [comment]
you can import .csv files with openScale. Just export a sample measurements with openScale to see the file format (column names) and re-range the MiFit csv file to fit it with the openScale csv file.
