### ISSUE TITLE
Status light and bar for weight disagree with each other (1 red, 1 green)

### ISSUE THREAD

**Issue by gappleto97** [oliexdev/openScale#467]
![Cropped screenshot](https://i.imgur.com/WbRZaw4.png)

BMI worked correctly (crossed that threshhold yesterday). If it matters. I am entering using a Yunmai Bluetooth scale, and I am on the latest F-Droid version as of this posting. Pixel 2, Android 8.1.0.

**Comment by oliexdev** [comment]
thanks should be fixed with https://github.com/oliexdev/openScale/commit/f2faf6717c53296470f951e1bda0e49a1ec51507 please try out the latest dev version
