### ISSUE TITLE
x-axis values (dates) on overview diagram very narrow 

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#47]
The dates below the overview diagram are very narrow. The one on the right is even cropped. I think we don't need the year in this diagram since it only shows the last few measurements.

Example:
![screenshot_20170601-043408](https://cloud.githubusercontent.com/assets/28578876/26749459/67f4cfd8-480b-11e7-9933-80e0a55141a2.png)

**Comment by oliexdev** [comment]
should be fixed with commit https://github.com/oliexdev/openScale/commit/d36cc0ed1b72ea72ba6693243908bfc0da0c7479
I don't show the last date anymore instead I will only show the days between the last measurement.
