### ISSUE TITLE
Transfer data to YAZIO app

### ISSUE THREAD

**Issue by JosefUcker** [oliexdev/openScale#473]
I am using Yazio and the Samsung Watch with the Samsung Health app.
It is very fine to transfer all watch data to Yazio.

So I wish to Transfer the data from openscale (with Sanitas SBF70) to Yazio.

**Comment by oliexdev** [comment]
I don't know Yazio and I don't support smart watches, see freeyourgadget project.

I have no idea if there a csv import function in Yazio, if yes you could export the openScale data via csv and import it in Yazio!?
