### ISSUE TITLE
Xiaomi Body Scale v2 - Wrong values

### ISSUE THREAD

**Issue by Maligola** [oliexdev/openScale#476]
In the current version Version 2.1.0 (45) the values are no longer correct at all. Body fat at 61% and water content at 27.84%?
I am slim and sporty. At ~30% water content I would no longer be responsive.
Has the file path assignments been swapped?

See screenshot.

![Screenshot_20190629-174215_openScale](https://user-images.githubusercontent.com/52354824/60386593-403d2900-9a97-11e9-9770-9bc27564a00e.jpg)

I checked the data with the original software. These are completely different.
![IMG_20190629_175805531](https://user-images.githubusercontent.com/52354824/60386615-9a3dee80-9a97-11e9-92ee-e6178bdb68b0.jpg)

Please check the paths for the Xiaomi Bodyscale v2.

Thank you

-------------

In der aktuellen Version 2.1 stimmen die Werte überhaupt nicht mehr. Körperfett bei bei 61% und Wassergehalt bei 27,84%?
Ich bin schlank und sportlich. Bei ~30% Wasseranteil wäre ich nicht mehr ansprechbar.
Wurde da die Dateipfadzuordnungen vertauscht?

Siehe Screenshot.

Ich habe die Daten mit der originalen Software gecheckt. Diese sind gänzlich anders.

Bitte einmal die Pfade für die Xiaomi v2 kontrollieren.

Danke

**Comment by oliexdev** [comment]
please provide more information about your gender, height, age and selected activity level.
The implementation is based on https://github.com/wiecosystem/Bluetooth/blob/master/sandbox/body_metrics.py
Please check this python script if you get the right values. 

And do more data acquisition regarding to https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale step 1
