### ISSUE TITLE
BMI field not editable

### ISSUE THREAD

**Issue by serussell** [oliexdev/openScale#478]
In a new entry, or editing an existing entry, the BMI field is not editable.

My scale is not supported, so I enter records manually, which is fine. The scale supports a BMI measurement, and not being able to enter this measured value seems wrong. Is there a setting somewhere I'm missing that enables this?

**Comment by oliexdev** [comment]
no the BMI is automatically calculated based on https://en.wikipedia.org/wiki/Body_mass_index
