### ISSUE TITLE
Bug: Wrong dates in overview diagram

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#48]
I noticed that some dates below the overview diagram are incorrect. This happens with openScale-1.5.2-MultiUserFix and two different users on two different phones. The corresponding list measurement entries are correct. I didn't test the regular 1.5.2 version for this bug yet.

Example ("03.06.17, 03.06.17, 03.06.17" but should be "02.06.17, 02.06.17, 03.06.17":
![screenshot_20170603-001322](https://cloud.githubusercontent.com/assets/28578876/26749504/fdc6583c-480c-11e7-81b3-7e06565f15d7.png)
![screenshot_20170603-001328](https://cloud.githubusercontent.com/assets/28578876/26749508/0737f4ac-480d-11e7-8ac4-1ade24af2ca8.png)

**Comment by oliexdev** [comment]
should be fixed with commit https://github.com/oliexdev/openScale/commit/d36cc0ed1b72ea72ba6693243908bfc0da0c7479
The problem was that the calculation took place between the days in seconds and that was too precise. :grin:
