### ISSUE TITLE
Different users are not respected during data import

### ISSUE THREAD

**Issue by sanjaay** [oliexdev/openScale#480]
**Describe the bug**
I am using two different user. 
When I import all data to a fresh installation of open scale all data is displayed only for one user (user A). The data for the one user (user A) also includes all data from the second user (user B).

**To Reproduce**
1. Genrate two different users
2. Add data to both users
3. Export a .csv file (same behavior with a with a .db file)
4. Delete the application to remove all data
5. Install the application
6. Generate both users (user A and user B) again 
7. Import all data

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): 2.0.3

**Expected behavior**
Saved data (.csv and .db file) should contain information about the user.

**Additional context**
My recommendation: 
Proposed solution 1: Add user name field to the exported data.
Proposed solution 2. Allow the intelligent user allocation after a data import and not only while retrieving data via Bluetooth. This may fix the data.

**Comment by oliexdev** [comment]
in the CSV only the current selected user data is exported therefore you should import it only for the current selected user.

If you export the database the user data field are also exported but again you always have to create the user manually. We had these discussion before please search in the issues.
