### ISSUE TITLE
Yunmai mini muscle mass missing and other values seems off

### ISSUE THREAD

**Issue by Naguz** [oliexdev/openScale#484]
**Describe the bug**
Fat percentage missing from Yunmai mini (YUNMAI-ISM2-W) and also other values seems off. 

**To Reproduce**
1: weigh yourself after connecting to the scale
2: Everything but muscle % is there. Muscle %, is 0

In addition, water % is 72,51 while muscle is 70%

It seems related to issue 71, but I'm suspecting it's not the exact same model.

**Comment by oliexdev** [comment]
please provide the [openScale log file](https://github.com/oliexdev/openScale/wiki/Frequently-Asked-Questions-(FAQ)#how-to-get-the-openscale-debug-log-file). I own this scale too but I can't reproduce this error. I need more information about your settings. Female/Male, age and so on.
