### ISSUE TITLE
Add custom measurements?

### ISSUE THREAD

**Issue by kinow** [oliexdev/openScale#485]
**Is your feature request related to a problem? Please describe.**

I was showing the app to my wife, and she missed only the option to add custom measurements. Would it be possible?

**Describe the solution you'd like**

A new type of measurement (Custom Measurements). My wife keeps track of

- Meditation time
- Weight (morning)
- Weight (evening)

But in openScale she has only one weight, and no way to keep track of her meditation time. She'd like to see that information plotted over time as with other measurements in openScala if possible.

**Describe alternatives you've considered**

I thought about hijacking another measurement, but that doesn't sound like a good idea.

**Additional context**

Thanks

**Comment by oliexdev** [comment]
thanks but the mediation time is not the aim of openScale. You can weight yourself multiply times on a day with openScale. Currently you can add your mediation time in the comment. We had already the discussion to add custom mesaurements but it is not easy to implement, see issue #4
