### ISSUE TITLE
Runtastic Libra support broken?

### ISSUE THREAD

**Issue by Robyer** [oliexdev/openScale#486]
I see in readme that Runtastic Libra is supported, but when I try to search for it in application, it found "Libra-B [mac address]" and on second line says "Device not supported". 

What am I doing wrong?

**Comment by oliexdev** [comment]
please post the openScale log file, read the FAQ for more details

**Comment by Robyer** [comment]
Here is the log. I tried to search for scales, then clicked on the Libra-B which was found (even though it said it's unsupported), waiting dialog was showed and then closed automatically. I clicked it once again with same result.

[openScale_2019-08-13_10-40.txt](https://github.com/oliexdev/openScale/files/3496067/openScale_2019-08-13_10-40.txt)

**Comment by oliexdev** [comment]
your device name is a bit different than the other Libra scales. I added your device name, please try out the latest dev build of openScale and give feedback if it works or not.

**Comment by Robyer** [comment]
Thanks, it works now.
