### ISSUE TITLE
How to install openScale dev version (GitHub)

### ISSUE THREAD

**Issue by retrodimi** [oliexdev/openScale#491]
I am quite new to all of this and tried to install the developer version before, yet somehow it does not work properly anymore. 

I downloaded the files in the link below both the .apk as well as the source code
https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

I connected my phone to my laptop and placed the files into the phones memory as well as the secure digital card or sd-card. Both options did not work. 

I then downloaded and tried the same.
https://github.com/oliexdev/openScale

It also did not work, yet the first time I tried it it did work somehow. 

I bought the offical version, yet I don't understand yet how I cannot use the dev. version for instance from GitHub now when I could before.

Do I need to drag it into a specific folder ?

**Comment by oliexdev** [comment]
check out https://www.androidauthority.com/how-to-install-apks-31494/
