### ISSUE TITLE
Sanitas SBF70 - 22 Byte Measurement Wireshark

### ISSUE THREAD

**Issue by retrodimi** [oliexdev/openScale#492]
Hello I was curious I downloaded the dev version and again thanks for the link! Yet, I want do reverse engineer this scale badly, so I can't find the 22 Byte Measurement in the log before I can start to code. Yet, it is listed here https://github.com/oliexdev/openScale/wiki/Beurer-Sanitas, so I don't know if the 22 Byte Measurement can be found with at all with all the relevant data !
 
I looked into the code of openScale. The point is I don't find the water percentage and I also can't predict the values by some formular on the net. If I can't get the values of open scale I tried it with the Sanitas Healthcoach app, yet I was not succesful yet. 

Can I find the 22 Byte Measurement containing <timestamp><weight><impedance><fat percentage><water> etc in the hci_logs ?

I am missing a few values before I can start programming. Including water percentage, bone mass, amr and muscle mass. I did not find it for a couple of weeks now inside the hci-logs.

I would very much appreciate an answer! since I am new and I am really interested in this field also the topic. Yet, I am stuck here.

**Comment by oliexdev** [comment]
please use this issue #488
