### ISSUE TITLE
Goal weight isn't updated when switching users

### ISSUE THREAD

**Issue by alexanderadam** [oliexdev/openScale#500]
**Describe the bug**
The graph will always show the goal weight line of the user that was selected when the application was started. It's not updated when the user is switched.

**To Reproduce**
1. Have more than one user with a goal weight configured (and users should have different goal weights obviously so that someone can see to expect a change). :wink: 
2. Close the app
3. Start the app and have a look on the goal weight in the graph
4. Switch the user via user switcher on the top and see that the goal weight stays the same

Reproduced with [latest F-Droid version](https://f-droid.org/en/packages/com.health.openscale/#2.1.0): `v2.1.0 (45)`

**Expected behavior**
The goal weight should change with it's user

**Additional context**
Thank you for your work! :pray:

**Comment by oliexdev** [comment]
thanks should be fixed in the dev version.
