### ISSUE TITLE
Auto daily backup is not complete

### ISSUE THREAD

**Issue by FifiTheReal** [oliexdev/openScale#501]
**Describe the bug**
The automatic daily backup is only completed when I enter the Settings/Backup menu.

**To Reproduce**
[See my screen capture.](https://www.dropbox.com/s/qd7jlnqzn4rg6wh/2019-10-05%2008.28.03.mp4)

**Comment by oliexdev** [comment]
The backup time is inexact scheduled by Android, see https://developer.android.com/training/scheduling/alarms for more information. openScale will save the time and date based on your settings when you exit the Settings/Backup menu, so the alarm manager might be triggered with the new settings but it should automatically triggered every day/week/month and so on.

**Comment by FifiTheReal** [comment]
Thanks for the reply!

I think the problem was that the phone didn't let the program run in the background. I enabled running openscale in the background and now everything is fine:
![Screenshot_20191016_140721](https://user-images.githubusercontent.com/34412887/66918115-eef17f00-f01e-11e9-99a8-ef04fad2d900.jpg)
