### ISSUE TITLE
Add Support for the ETEKCITY Bluetooth Scale

### ISSUE THREAD

**Issue by Dipan61241828** [oliexdev/openScale#509]
Hi it's great app. it works like a charm for almost all devices. Thanks for this great creation.
recently i bought new weight measurement scale of ETEKCITY and it is not supported by this app.

https://www.etekcity.com/product/100334

here the debug log file attached with your debug app

[openScale_2019-10-17_12-57.txt](https://github.com/oliexdev/openScale/files/3738102/openScale_2019-10-17_12-57.txt)

More debug Log,
[openScale_2019-10-17_16-04_new.txt](https://github.com/oliexdev/openScale/files/3738761/openScale_2019-10-17_16-04_new.txt)

Scale information
![Screenshot_20191017-184936](https://user-images.githubusercontent.com/56672883/67012835-b41b4400-f10f-11e9-998e-3ee65d5b0b51.jpg)

Let me know if the above is sufficient or should I need to give more.

Thank you.

**Comment by oliexdev** [comment]
Sorry but openScale focused on the body weight scales and not on the kitchen scales. But well you could try to reverse engineer the kitchen scale anyway, see the wiki more information.
