### ISSUE TITLE
Requesting for Formula's

### ISSUE THREAD

**Issue by Jeyaseelan2528** [oliexdev/openScale#511]
Dear Team,

I really appreciate the way you provide information about the scales and apps.

But I am finding it difficult to take the formula's and check manually my measurements 

Is there a way in which I can get the formula's that happens with Yolanda scale to test the calculation 

Please advise me to move further 

I will be expecting your reply 

Thank you in advance

**Comment by oliexdev** [comment]
we don't have the formula neither, see #291.

**Comment by Jeyaseelan2528** [comment]
Is there a way in which we can get the formula?

Please let me know if there is a way?
