### ISSUE TITLE
Add "Medisana BS 410 Connect" to the list of supported devices

### ISSUE THREAD

**Issue by Mickey91522** [oliexdev/openScale#512]
Hi there,

thanks for you nice work!

I just bought a "Medisana BS 410 Connect" scale and OpenScale works fine with it.

I think technically it should be the same like at least on of the other Medisana scales, that are already supported officially.

Maybe you want to add this scale to the list of supported devices, too.

Best regards

**Comment by oliexdev** [comment]
thanks for reporting. I added it in the wiki.

**Comment by jovandeginste** [comment]
@Mickey91522 I have a BS410; it does not mention "connect"; this is a different model, right? (I can't seem to connect it to open scale)
