### ISSUE TITLE
Automatic Backup seems not to work anymore

### ISSUE THREAD

**Issue by natrius** [oliexdev/openScale#523]
**Describe the bug**

The last successfull backup was created 2019-05-29_openScale.db and i have added entries later. "Auto backup: enabled", "Backup schedule: daily", my custom folder. Various entries for example 01.08.2019, 30.07.2019 and so on. 

**To Reproduce**
No clue, to be honest. 

Reproduced with 2.1.2 from F-Droid. 

**Expected behavior**
With the settings a lot of backups.

**Comment by oliexdev** [comment]
Could you attach the openScale log file while enabling and disabling the backup functionality and please check if i you have the same problem as issue #501
