### ISSUE TITLE
Body fat change in pounds / kg

### ISSUE THREAD

**Issue by silberberg** [oliexdev/openScale#533]
Enhancement suggestion / request:  While openScale calculates changes in body mass and body fat percentage, as far as I can tell it doesn't calculate change in pounds (or kg) of fat.

That is: `delta = (Body Mass 2 * Fat % 2) - (Body Mass 1 * Fat % 1)`
Note: % means percentage, not modulo

I could probably send a pull request and work on this myself, but I don't know Java.

Thank you for creating this code!
Steve

**Comment by oliexdev** [comment]
You can change the body fat in % to kg/lb/st if you click on the fat measurement in the settings->measurements and disable the percentage option. Do you mean that?

**Comment by silberberg** [comment]
OMG yes thank you!  One more question.  Does the app work with the RENPHO scale?  It's not in the list, but maybe someone has reverse engineered the bluetooth

**Comment by oliexdev** [comment]
not yet, see issue #291
