### ISSUE TITLE
Possible issue with some arrow colors

### ISSUE THREAD

**Issue by naoliv** [oliexdev/openScale#538]
**Describe the bug**
The arrow color for the body mass index, fat, waist perimeter and waist-to-height ratio should probably be green while they are decreasing, and not red.

For example:
![](https://user-images.githubusercontent.com/982338/72482333-17367880-37dc-11ea-9efd-89e1a864eeb8.png)

If I am losing weight (and the BMI, fat, waist, etc are decreasing) I consider this to be a good thing and I would expect them to be green too, like the weight arrow in this example.

For the body mass index, the color probably should tend to a normal/healthy BMI (ie if the person is above or below the ideal BMI, the arrow should be red; if it is within the normal range, green).

For fat, waist perimeter and waist-to-height ratio I am unsure if there is any ideal range, but like I said, I consider it a good thing if they are lowering.

I am using version `2.2.0-light (48)`

**Comment by oliexdev** [comment]
sorry for the late respond but now it is implemented, the arrows are colored towards the evaluation results (if we can compute the evaluation of a measurement)
