### ISSUE TITLE
BS444 no bluetooth device found

### ISSUE THREAD

**Issue by kuehnelth** [oliexdev/openScale#54]
Hi,
I just installed the app from Google Play (v1.5.3) but I cannot connect to my scale.
Probably because the MAC-address is not in the whitelist. It starts with C9:A6:8A.
Could you add that address?

Thanks

**Comment by oliexdev** [comment]
thx for the hint. I added the new hw address. Please install the latest development build 21.

**Comment by vogan** [comment]
Hi,

I had the same issue, different MAC-address. Fixed it by adding:

`hwAddresses.add("D60211");`

Thank you!

**Comment by oliexdev** [comment]
Hi vogan,

thanks for adding it. If you want you can create a pull request, so you will listed as a contributor. If not no problem then I will add it.

Best regards
oli

**Comment by slobinger** [comment]
Same issue here. Added my hdAddress and made pull request #64.

Tanks for your great work.
Best regards
Sebastian

**Comment by hirnsushi** [comment]
Same problem here.
My MAC-Address starts with DA:45:CF.
I would have opened a pull request myself but wanted to make sure I really only have to include the beginning of the address.

**Comment by hirnsushi** [comment]
That would be great, thx.

**Comment by oliexdev** [comment]
it's done with commit https://github.com/oliexdev/openScale/commit/94104497beb009c71cc03e80ef97e5157b2327b8
Please install the latest developer build 41 to get this change. The hw address will official contain in the app after the next release.
