### ISSUE TITLE
Enhancement when entering the polynomial regression degree value

### ISSUE THREAD

**Issue by naoliv** [oliexdev/openScale#540]
**Is your feature request related to a problem? Please describe.**
When configuring `Regression polynomial degree` there are two things that could be improved:

1. the app should automatically focus at the input field and open the keyboard
2. the keyboard type should be numeric and not like this (since we won't be entering letters at the value):

![](https://user-images.githubusercontent.com/982338/72554983-819df600-387a-11ea-8692-50a9e86329b5.png)

**Describe the solution you'd like**
It should automatically focus at the field and open a numeric keyboard.

About the phrase, shouldn't it be `Polynomial regression degree` instead `Regression polynomial degree`?

**Comment by oliexdev** [comment]
not needed anymore in the latest version.
