### ISSUE TITLE
Xiaomi Mi Scale Firmware Update

### ISSUE THREAD

**Issue by klepbroe** [oliexdev/openScale#541]
Is it possible to update the Xiaomi Mi Scales' firmwares via openScale?

The firmware files can be extracted from the Xiaomi Mi Fit app.

com.xiaomi.hm.health.apk\assets\firmware.json:

    "version": 1,
    "weight": {
        "fw": {
            "name": "weight.fw",
            "version": "V0.5.8"
        }
    },
    "weight_bfs": {
        "fw": {
            "name": "weight_bfs.fw",
            "version": "V0.3.2"
        }
    },
    "weight_bfs_h": {
        "fw": {
            "name": "Huaihe_OTA.bin",
            "version": "V1.0.0.12"
        }
    },
    "weight_scale2": {
        "fw": {
            "name": "weight_scale2.fw",
            "version": "V1.0.0.12"
        }
    },

**Comment by oliexdev** [comment]
sorry no it is not possible
