### ISSUE TITLE
Xiaomi Mi Body Composition Scale 2 Bluetooth 5.0 not 4.x version

### ISSUE THREAD

**Issue by psper** [oliexdev/openScale#549]
Xiaomi Mi Body Composition Scale 2 Bluetooth 5.0

Hi, 
I read that OpenScale suports Xiaomi Mi Body Composition Scale 2, but I read also that uses Bluetooth 4.2 not 5.0.

If I bought a Bluetooth 5.0 version ,"Xiaomi Mi Body Composition Scale 2 Bluetooth 5.0" it is also supported?
https://www.pcdiga.com/balanca-xiaomi-mi-body-composition-scale-2-branca-bluetooth-5-0?gclid=CjwKCAiA-P7xBRAvEiwAow-VaZB_hrUV4p7YN4jf6BjFmcbi4F4z1hJzagxqrB2jFhVYIa90P1SgLxoCIokQAvD_BwE

Thanks in advance,
Paulo

**Comment by oliexdev** [comment]
I have no idea, I don't own every scale and scale version. You have to test it.
