### ISSUE TITLE
openScale 1.5.3 not on F-Droid

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#55]
The recent version of openScale is missing on F-Droid.
I don't know the exact process of publishing apps on F-Droid, but probably you forgot to do something for version 1.5.3? The older versions had a delay of max. 3 days from github to f-droid.

BTW: I don't use Google Play. So I loaded the .apk from github. I didn't see any bugs so far. Good work, oliexdev! :smiley:

Momo

**Comment by oliexdev** [comment]
Hi momo,

I changed in the source code the version code to 16 after I tagged the new version to 1.5.3 on github. I guess that is why f-droid didn't compile the new version. I didn't know that before but it makes sense for me.
Next time I will make sure that I commit the new version code before I tag it.

Best regards
oli
