### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by alexanderadam** [oliexdev/openScale#553]
It's a luxury feature but I thought it would be nice if openScale could also add entries to a calendar.
Each title could contain a summary and some details in the description.

**Comment by oliexdev** [comment]
What should the calendar entry contain in the summary and in the detailed description?

**Comment by alexanderadam** [comment]
Maybe something like

**Title**: `Weight on May 23, 2023 at 12:12 p.m .: xxkg`

**Description** (maybe just showing the details that are selected for viewing in the app):

```
Body mass index (BMI): xxx
Weight difference: xx.x
Body fat: xx.x
…
```

**Comment by oliexdev** [comment]
Wouldn't you spam your calendar with these information? I think this feature is very special, I see no really benefit from it.
