### ISSUE TITLE
Add missing metrics

### ISSUE THREAD

**Issue by Ilnahro** [oliexdev/openScale#558]
**Is your feature request related to a problem? Please describe.**
When trying to track muscle development, I noticed that there is only one circumference measurement for biceps and thighs (rather than two, one for each side) and that several others were unavailable. What I was missing was shoulders (possible with two measures as well), calves (left and right) and forearms (also left and right)

**Describe the solution you'd like**
I see two possible solutions: either add these specific metrics or allow users to add their own metrics using existing measurement types in the app.

**Comment by oliexdev** [comment]
see issue #4 or issue #485
