### ISSUE TITLE
Medisana BS444: Only last measurement fetched (was #425)

### ISSUE THREAD

**Issue by sebmate** [oliexdev/openScale#561]
Hi all,

I'm re-opening the closed issue #425, see https://github.com/oliexdev/openScale/issues/425#issue-416737660 where it was described that the current version of OpenScale only fetches the last measurement of the MEdisana BS444:

The problem still persists, at least for me (Android 7, Medisana BS444). As stated by steffenl82, the old version (<=1.9.3) correctly fetched all measurements, whereas the new version fetches only the last measurement. I kept switching between both versions to see if this got fixed many times, but as this is a pain I have decided to comment on this again.

Sometimes, the recent version fetches all or at least multiple measurements. I was not able to figure out when this happens. It might be after I have restarted the phone.

What also bugs me is that it always tells me to "step barefoot on the scale" after it has fetched the measurement(s). Sometimes fetching does not work at all and I have to go to the Bluetooth settings menu in OpenScale and select the scale again.

I think I'll switch back to the old version again. Would be great if someone could have a look at this again. Anyway, MANY thanks to all developers for this useful app!

Sebastian

**Comment by oliexdev** [comment]
Please don't open a new issue on an existing issue. Without a log file and the scale it is mostly impossible to help. Furthermore it would be better to use the Bug template in GitHub.
