### ISSUE TITLE
Bug with Beurer BF700 - error code "error_max_scale_users"

### ISSUE THREAD

**Issue by schneeschuhhase** [oliexdev/openScale#565]
After first connection with Beurer BF700 everything was fine so far.
Then I removed the right to locate again, as described in the description as possible.
I also disabled GPS.
The I got the same error with my Beurer BF700.

Solution (workaround!):
Enabling GPS is not enough.
I had to go into "android settings -> apps -> OpenScale -> permissions" again in enable the right for location tracking.
Then I was able to establish a bluetooth connection again.

Greetings
schneeschuhhase

This bug was already mentioned by:

https://play.google.com/store/apps/details?id=com.health.openscale.pro&hl=de&reviewId=gp%3AAOqpTOG8BxbQO-MdKg62s5363LHJ8xizID3h7-aztw4kNt1XEDWupmg7N_vNHyTX79vp7UXz4h7ay6Ccxpq4Gi4

Till Daniel Zühlke
18. Januar 2020
Bisher hat die App alles tadellos aufgezeichnet. Lediglich seit ich lineageos 16 installiert habe muss ich vor dem verbinden mit der Beurer bf700 den Reset Knopf betätigen, sonst kam die Meldung "maximale Anzahl Benutzer bereits erreicht". Seit dem letzten Update hängt sich die App jedoch konsequent auf, sobald eine Verbindung hergestellt wird. Bitte fixen, dann gerne wieder 5 Sterne.

**Comment by oliexdev** [comment]
Without the log files it could also that the maximum scales users are reached by this type of scale.

Some bad designed scales needs a Bluetooth scan before connecting to the scale. Therefore the GPS has to be on (needed for the Bluetooth scan). It is not a bug in openScale it is the bad Bluetooth implementation on some scales.
