### ISSUE TITLE
Scale support report: Quanta QTBL10 

### ISSUE THREAD

**Issue by rmansilha** [oliexdev/openScale#566]
Hi, 

I'm glad to share with you and your community that openScale works with Quanta QTBL10 (http://www.quantaproducts.co/produto/QTBL10/balan.html). The weight and BMI metrics were successfully checked against values obtained from KeepFit (https://play.google.com/store/apps/details?id=com.beikang), the app recommended by Quanta. Below is a picture of my scale:
![6bb30b76-26ac-4bc4-914d-e62a5177669e](https://user-images.githubusercontent.com/9573205/78501076-87e09780-7730-11ea-84c6-06cf64617b97.jpg)

I found your project through a closed issue (https://github.com/oliexdev/openScale/issues/140) while googling for an alternative to KeepFit. I'm not using KeepFit mostly due to privacy concerns. For example, it requires permission for making phone calls.

Thus, I suggest to add Quanta QTBL10 to the list of supported scales and, perhaps, to create "Scale support report" kind of issue. 

Please, let me know if you need further information.  

Congrats for the very good work and thanks for your attention,
Rodrigo.

**Comment by oliexdev** [comment]
Thanks, could you tell me what is shown when you found the device in openScale? Which device driver is used?

**Comment by rmansilha** [comment]
Hi, the device is "YunChen" (as in issue #140).

**Comment by oliexdev** [comment]
Thanks, I added it to the wiki
