### ISSUE TITLE
Support Wi-Fi Body Scale (WBS01)

### ISSUE THREAD

**Issue by PanderMusubi** [oliexdev/openScale#572]
**Scale name**

Wi-Fi Body Scale (WBS01)

https://support.withings.com/hc/en-us/categories/200118157-Wi-Fi-Body-Scale-WBS01-

This scale does not support Bluetooth but works over WiFi. There is existing implementation in OpenHAB to support this scale which reports weight, fat and bmi.

**Comment by oliexdev** [comment]
sorry but openScale supports only Bluetooth scales at the moment.
