### ISSUE TITLE
Import backup into mysql

### ISSUE THREAD

**Issue by dproetel** [oliexdev/openScale#573]
Good morning,
I try to import the sqlite db into mysql to have all weights in a central database.
My challenge is the datetime. Where can I find how to convert on shell/mysql level the datetime int in something mysql understands?
Thanks in advance
Daniel

**Comment by oliexdev** [comment]
What is your goal? The datetime is a long value which can be saved in mysql.

**Comment by dproetel** [comment]
Hi,
My goal is to save it in the database and easily use it with mysql functions. Actually I cut off the last 3 digits and have a unix time stamp. It works, but is that right?

Ciao Daniel

**Comment by oliexdev** [comment]
yes you have to interpret the long value depending on your goal. To which app to you want to connect your mysql database?
