### ISSUE TITLE
RENPHO Bluetooth Body Fat Scale supported but not listed

### ISSUE THREAD

**Issue by teeks99** [oliexdev/openScale#574]
**Scale name**
The RENPHO ES-CS20M scale was not listed on the supported scales page, but worked perfectly out of the box. 

It was detected by bluetooth as a "QN-Scale".

![IMG_20200506_070301](https://user-images.githubusercontent.com/33045/81360163-c0adbc80-90a0-11ea-9371-249657396a46.jpg)
![IMG_20200506_070326](https://user-images.githubusercontent.com/33045/81360169-c3a8ad00-90a0-11ea-8f6e-e36920785264.jpg)
![IMG_20200506_070333](https://user-images.githubusercontent.com/33045/81360171-c5727080-90a0-11ea-91f8-2066297e8da5.jpg)

Successful log:
[openScale_2020-05-06_06-08.txt](https://github.com/oliexdev/openScale/files/4596557/openScale_2020-05-06_06-08.txt)

**Comment by oliexdev** [comment]
thanks I added the scale into the wiki.

**Comment by giupardeb** [comment]
@teeks99 Can you explain the steps to add this scale on the app? openScale doesn't find it

**Comment by teeks99** [comment]
I don't have this model anymore. However, there wasn't anything special. Open the app, pair with the scale when you stand on it.

**Comment by giupardeb** [comment]
it doesn't work for me xD

**Comment by guix77** [comment]
See #769
