### ISSUE TITLE
Support for multiple scales

### ISSUE THREAD

**Issue by julian-klode** [oliexdev/openScale#579]
**Is your feature request related to a problem? Please describe.**

I (will soon) have two scales (at two houses), and want to use both.

**Describe the solution you'd like**
I'd like to be able to connect multiple scales.

**Describe alternatives you've considered**
Disconnect and reconnect? Sounds annyoing.

**Comment by oliexdev** [comment]
The implementation is much more complex and the benefit is low but if anybody want to implement that feature you are welcome to send a PR.

**Comment by oliexdev** [comment]
will close this one please use #770
