### ISSUE TITLE
Initial preset of measurement settings not regarded

### ISSUE THREAD

**Issue by MilenaMMay** [oliexdev/openScale#58]
**Steps to reproduce:**

When I load the app to a new (virtual) device and create a new user,
the Overview view contains _all measurement settings_.

When I then go to Settings -> Measurements,
_I see that waist and hip circumferences are disabled by default_.

When I then close the Settings without changing anything and go back to Overview, 
only the measurements that are enabled are shown (waist and hip circumferences are not shown).

This can only be reproduced by loading the app to a new (virtual) device and not by creating a new user because the settings are global.

**Expected behaviour:**

When I load the app to a new (virtual) device and create a new user,
the Overview view contains _only the measurement settings that are enabled by default_.

**Comment by oliexdev** [comment]
thx it is fixed some default values were on true instead of false.

**Comment by MilenaMMay** [comment]
Great, thx =)
