### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by soyxan** [oliexdev/openScale#582]
I am sharing a Yunmai scale with my GF and I am wondering if with OpenScale I can share/sync the measurements in 2 smartphones. What I want is to be able to see the readings in my smartphone and that my GF can also view them in hers. Is that possible? How?
Thanks!

**Comment by oliexdev** [comment]
since openScale itself protects your data, your health data are only locally stored on the smartphone. You can sync your weight with openScale sync but this sync works only with one selected user. So all in all I am sorry that doesn't work.
