### ISSUE TITLE
Connection to SBF70 dont work anymore

### ISSUE THREAD

**Issue by Danielmae** [oliexdev/openScale#588]
I Have a Huawei P30 pro and use the SBF70 since almost a year. It works more or less stable but sice end of May the Scale does not longer connect to the App (or vice versa).
I see the Scale in the App and the App says also connected but it reads no Data.
I have Android 10

If the Scale isnt Supported anymore then please tell me one which works.

**Comment by andrerodr** [comment]
Check your permissions, location must be enabeled for bluetooth.

**Comment by oliexdev** [comment]
please search in the issues
