### ISSUE TITLE
Smart Pulley compatibility

### ISSUE THREAD

**Issue by matthawkes869** [oliexdev/openScale#590]
Hi Oliedev I am developing a smart pulley that uses the same electronics as a smart scale. The smart pulley can be placed in any weight machine that already uses a pulley. This will allow for tracking your workout. I have the electronics done just looking for help putting an app together. I want to share the idea with you and see what you think but I cant find your contact info my email is matthawkes869@gmail.com contact me if you would like to know more.

**Comment by oliexdev** [comment]
my mail address is olie.xdev@googlemail.com
