### ISSUE TITLE
Export to CSV has stopped working in version 2.3.0

### ISSUE THREAD

**Issue by miluskch** [oliexdev/openScale#591]
**Describe the bug**
Export to CSV has stopped working in version 2.3.0. The exported file contains only column headers, no measurements.

**To Reproduce**
Selecting "Export" from the menu in the upper right corner of the application and saving the file.

**Expected behavior**
The CSV file should contain all measurements

**Debug log**
Quick code verification indicates that an empty collection is passed to the measurement exporting method.

**Comment by oliexdev** [comment]
thanks it is fixed.
