### ISSUE TITLE
[Bug] With Xiaomi Mi Scale 2 app shows ~10% too high visceral fat value

### ISSUE THREAD

**Issue by huuhaa** [oliexdev/openScale#597]
**Describe the bug**
When using Xiaomi Mi Scale 2 with Openscale app, there is ~10% bigger visceral fat percentage shown than with Amazfit app, I say approximately since Amazfit doesn't show decimals like OpenScele does, and it's also not %/kg issue and that also can't be changed from settings so it could be that.

I report this as a bug even thought this is just small error at one of the values not showing right.

**To Reproduce**
1. Use Xiami Mi Scale 2 with openScale
2. Check visceral fat value
3. Compare values to the ines showed by  Amazfit or MiFit app.
4. You'll see ~10% difference in values, openScale shows ~10% more

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

With version 2.30(49) from F-droid

**Expected behavior**

Visceral fat value would expected to be about same than with official app.

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by oliexdev** [comment]
It could be a rounding error or the calculation is slightly wrong. You are welcome to reverse engineer by yourself and send a PR with the correct formula.
