### ISSUE TITLE
Bounty for mi scale 2 support

### ISSUE THREAD

**Issue by kxpvcr** [oliexdev/openScale#60]
Hey! Just tested this with the 1st gen. scale and it works just fine. Do you have any idea of how much effort to support the 2nd gen. scale?

I can set up a bounty and contribute to it. Maybe people are into that, it'd be nice to have those extra measurements.

What do you think?

**Comment by oliexdev** [comment]
Hi kxpvcr,

I have no idea how much effort is to reverse engineer the 2nd generation of the mi scale. Maybe they change not much but it could also be possible if they encrypt all Bluetooth messages.

Thanks for your offer maybe somebody will accept it. For me I don't want any bounty (if you like openScale give it a positive rating). Furthermore here in Germany you can't buy the 2nd generation of the mi scale only as an expensive import from China. 
But I will do my holidays in South Korea. Maybe I will buy one for testing purpose ;)

Best regards
oli

**Comment by kxpvcr** [comment]
Stellar 🥇 

I got mine from Spain, not that expensive. If you decide you'd like some monetary compensation for your effort, let me know!

**Comment by nykroy** [comment]
Me too, i searched time ago to donate some money for your efforts but i didnt find anything

_Sent from my Lge LG-H870 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NerosTie** [comment]
Hey! Any news about the support of the Mi Scale 2? Thanks

**Comment by oliexdev** [comment]
Yeah yesterday I got an email that the package was sent to me but it comes from China so it takes some time.

**Comment by NerosTie** [comment]
Nice! Because my Mi Scale 1 just died after 2 years so maybe I'll take the new version...

**Comment by mNantern** [comment]
Hey ! And thank you for that nice app' !

Any news about the full support of Mi Scale 2 ? How can we help ?

**Comment by erijo** [comment]
The best way to help would be if someone could reverse engineer the original app to learn how the calculations are done.
