### ISSUE TITLE
Little question in developing app like yours

### ISSUE THREAD

**Issue by TheJackuz** [oliexdev/openScale#605]
I'm sorry this is not a Feature request, but i didn't know where to ask you.
I'm a student and i'm facing a problem while developing an app like yours.
I'd like to connect to a weight scale via an android custom app, but I can't connect.
The weight scale is a Healthkeep CS20M3.
It seems I can only connect to it only via its own app.
Is it possible that I can't connect to it due to some private connection method?
Thank you very much for your time!

**Comment by oliexdev** [comment]
The Bluetooth connection could be encrypted but for Bluetooth scales that's unlikely but I don't know your scale, see https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale how to reverse engineer your scale.
