### ISSUE TITLE
Runtastic Libra: only the first value was recorder

### ISSUE THREAD

**Issue by RenaudDardenne** [oliexdev/openScale#606]
I only have the first value recorder on 19/07/2020 since then I see the value in the app but it is not recorded.

Reproduced with v2.2.0-pro

I expect to have multiple values recorded from the scale.

Debug will help 
[openScale_2020-07-29_19-27.txt](https://github.com/oliexdev/openScale/files/4996508/openScale_2020-07-29_19-27.txt)

**Comment by oliexdev** [comment]
could you reinstall openScale and reset your scale and do it again? (save before your measurements)
