### ISSUE TITLE
Wrong weight on chart page

### ISSUE THREAD

**Issue by mbenedetti** [oliexdev/openScale#609]
On main page overview for ex. the weight is 75.90. On chart page the weight is 76.65?!? On table page is correct 75.90
Also if try to export the data from chart page the file. csv is empty. 

I'm using the v2. 3.0 (49) with runtastic libra

**Expected behavior**
I'm expected the same value on all page. 

Best regards 
Massimo
![Screenshot_20200813_083429_com health openscale](https://user-images.githubusercontent.com/5930495/90101960-e998ba00-dd3f-11ea-97cf-695365c38be7.jpg)
![Screenshot_20200813_083444_com health openscale](https://user-images.githubusercontent.com/5930495/90101967-ec93aa80-dd3f-11ea-9a48-6bfbdcd722f1.jpg)

**Comment by mbenedetti** [comment]
I see the code and try to modify it.
I undersend now the problem is the data in week mode is in avarage not in value. 
I thought selecting week wold only display the values for the current week. 
The problem remains that when I export the data the file csv is empty. 
Is there any way to proceed to export?

**Comment by oliexdev** [comment]
see #600
