### ISSUE TITLE
"Ignore data that are out of range" doesn't work (v. 1.5.3)

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#61]
Hello oli,

yesterday I used our Mi Scale to weigh a large parcel (~20kg).
Direct before the next phone sync I ticked the 'Ignore data that are out of range' box (wasn't ticked before) on my wifes and my phone to prevent a wrong weight assignment. But it didn't do the trick.
On my wifes phone the parcel values went to her user (first user). On my phone the values went to my user (also first user). My wife's weight is ~65kg and my weight is ~115kg. Separation of 'real' measurements between my wife and me works well on both phones. (Didn't try to weigh a parcel till yesterday. :-) )

I didn't restart the app between ticking and sync. Could this be the reason?

regards
Momo

**Comment by oliexdev** [comment]
I wrote wrong the internal option name. I wrote "ignoreOfOutRange" instead of "ignoreOutOfRange" :blush:
