### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mbenedetti** [oliexdev/openScale#610]
I try to install openScale-2.3.0-release.apk but when i finish installation there is an error "App not installed "
I try to compile with android studio from source file and copy the .apk on mobile phone but still same problem.
I try on Android Studio simulator copy and install the apk but recive the same error.
If i execute the project with Android Studio simulator running correct.
Let me know please.
Best regards
Massimo

**Comment by oliexdev** [comment]
I don't know but that nothing to do with openScale but with your smartphone. I can't help you with that.
