### ISSUE TITLE
Table view shows values for the selected user but 'detail' view shows all (v. 1.5.3)

### ISSUE THREAD

**Issue by momo42** [oliexdev/openScale#62]
Hello oli,

Today I had to delete some values from the table and stumbled upon a problem.

On the 'Table' page, you see all measurements for the selected user. When you tap on such a value, you come to a 'detail' page. On this page you can use the < and > buttons to switch to the next or previous measurement. In this view there are not just the users values but 'all' values. I write 'all' beause I didn't do extensive testing on that. It definitive shows my AND my wife's measurements in chronological order. I don't know if this is a bug, but I would expect to find just my own (users) values in this view.

regards
Momo

**Comment by oliexdev** [comment]
You are right I didn't filter out the other users. Please test the new developer version if it works now.
