### ISSUE TITLE
Entering birth year is tedious with scroll wheel

### ISSUE THREAD

**Issue by jimhenshaw** [oliexdev/openScale#623]
Using a wheel to set the date for a birth date takes too long and requires a lot of scrolling depending on the user's age. Recommend allowing user to manually type in the four digit for birth year.

**Comment by oliexdev** [comment]
This is one of the default input method of Android. I recently change that because of the other input method was obviously more complex, search in the issues for more information. And manually input of a date format is more complex than you think if you want support more than one language.
