### ISSUE TITLE
Goal date pre-populated with birth date.

### ISSUE THREAD

**Issue by jimhenshaw** [oliexdev/openScale#624]
Populating the goal date with the birth date makes no sense since all goals will be in the future and birth date is always in the past. Recommend defaulting goal date to current date.

**Comment by jimhenshaw** [comment]
I just tried this on a Google Pixel and did NOT have the goal date pre-populated with birth date. This was seen a simulator in Android Studio.

**Comment by oliexdev** [comment]
The default goal date is +6 months of the current date
