### ISSUE TITLE
Re-hacking same scale? 

### ISSUE THREAD

**Issue by dmsqui** [oliexdev/openScale#630]
Please delete if this is not appropriate place for this question. 

I am not a developer but I am working with a team of developers and wondering if it's possible to "hack" one scale, one single time, so you can access many units of the same scale going forward? Or do you have to "hack" each scale individually? I am working with a manufacturer of cheap BLE scales where I hope to use this code to access many copies of them but first hoping to understand how it works. To confirm, nothing physically has to be done to the scale correct? 

Also, have developers been successful in "waking" a scale? For example, weight is on the scale for days it has already been hacked/paired with a phone. The phone comes into range of the device, is it possible to "wake" the scale for it to provide an updated weight reading? 

Either way, great work and thank you

**Comment by oliexdev** [comment]
>  I am working with a manufacturer of cheap BLE scales

Then it is best to ask the manufacturer of the cheap BLE scales, isn't it?
