### ISSUE TITLE
Language is missing in Setting's language selection though it's 100% translated in WebLate

### ISSUE THREAD

**Issue by PavelGorbanj** [oliexdev/openScale#640]
**Describe the bug**
Ukrainian language is not displayed in "Settings->General->Language" though it's marked as 100% translated in WebLate https://hosted.weblate.org/projects/openscale/strings/uk/

**To Reproduce**
1. Go to 'Settings->General->Language'
2. Inspect list of languages - Ukrainian is missing

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): v2.3.1-pro(50)

**Expected behavior**
Ukrainian is displayed in the languages list.

**Additional context**
N/A.

**Debug log**
N/A.

**Comment by oliexdev** [comment]
Thanks the list should be updated in the latest dev build.
