### ISSUE TITLE
List apps along with scales for compatibility checks?

### ISSUE THREAD

**Issue by famewolf** [oliexdev/openScale#644]
I'm having problems finding the models you mention on several scales @ Amazon.  For example you list the FitIndex ES-26M but I find the FitIndex ES-24M.  If you are using a library that gives support to several different manufacturer scales can we assume other model that use the same app would also be compatibe?   There are several that are 1/2 the cost of the models listed.

Thanks for your time.

**Comment by oliexdev** [comment]
I don't own every scale, so it's a community task to identify scales that are working with openScale.
We can't be 100% sure that they are using the same library, we need to test every scale. Additionally, we need to know the Bluetooth name of the scale to get it work with openScale.

So if you find out that the FitIndex ES-24M is also working with openScale give me a hint and I will add it to our supported list.
