### ISSUE TITLE
Renpho ES-CS20M Bluetooth not found

### ISSUE THREAD

**Issue by giupardeb** [oliexdev/openScale#648]
I bought a Renpho ES-CS20M because it is supported, but I can't finding the scale through the app (with blue-tooth and Location enabled). Why?

**Comment by oliexdev** [comment]
What do you mean you can't find the scale? You can't see the scale at all in Android? You can't see while you search in openScale in the settings?

**Comment by giupardeb** [comment]
I can't see the scale when I searching it in openScale. With the official application ([renpho](https://play.google.com/store/apps/details?id=com.qingniu.renpho&hl=en_US&gl=US)), I can find the scale.

**Comment by oliexdev** [comment]
Then you probably has paired the Bluetooth scale with your phone already. Please uninstall the official app and try again.

**Comment by giupardeb** [comment]
i tried but it keeps getting the same problem. Openscale Does not found the scale

**Comment by oliexdev** [comment]
reset your scale and unpair the scale in the Android system. This only happens if the scale is already connected or not on.

**Comment by GreyMarvel** [comment]
I have the same issue , in my phone's Bluetooth menu I can see the scales Bluetooth address when I stand on them but in the openscale app it doesn't discover the renpho scales . Is it possible they have changed something in the scales firmware on newer versions of this model ?
