### ISSUE TITLE
Amazon affiliate as "revenues" stream

### ISSUE THREAD

**Issue by mzzntn** [oliexdev/openScale#650]
**Is your feature request related to a problem? Please describe.**

Not a problem but actually an idea on how to make more "sustainable" the project. 

Couple of days ago I had to buy a new scale and I off course checked this GitHub page to evaluate the compatibility with the app. It'd have been easier for me (and I suppose many others) to just click on the scale in the Readme and being immediately redirected to Amazon to directly buy the scale. 

**Additional context**
I know that there is a "Donate" section and that usually it's difficult to accept other forms of payments in open surce projects,

These are just my 2 cents :)

**Comment by oliexdev** [comment]
Thanks for the idea but I don't want to get the impression if I can guarantee if these scales are working with openScale.
