### ISSUE TITLE
Flag field bit in MiScale2 used twice with two meanings

### ISSUE THREAD

**Issue by tjaderxyz** [oliexdev/openScale#652]
https://github.com/oliexdev/openScale/blob/b4e9624d169bea3f8c9c6e9f7f903d7a61ced505/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java#L143-L148

Here both ```isDateInvalid``` and ```isCattyUnit``` are set to ```isBitSet(ctrlByte1, 6)```. I haven't seen any bug caused by this, but I don't think this makes any sense and is probably a bug  waiting to happen.

**Comment by oliexdev** [comment]
Indeed but currently I don't see any problems with this code snippet. If somebody has the mi v2 scale and time could find out the true meaning of the bit 6. So long I will close it here.
