### ISSUE TITLE
Inconsistent Measurements

### ISSUE THREAD

**Issue by mzzntn** [oliexdev/openScale#655]
**Describe the bug**
Hi I recently bought a new scale 

I moved from a generic Kamtron #373 to a Xiaomi MiScale Body composition 2  I checked the compatibility as mentioned in #650 but the measurements from the two scale are completely different.

![photo_2020-11-22_17-25-25](https://user-images.githubusercontent.com/37122612/99909273-c76fea00-2ce7-11eb-99f8-9fd49f9d2ace.jpg)

As you can see in the picture I gained 20kg of muscle and 5 of fat in 2 days (I know that the measurements aren't completed at the same time but it shouldn't make too much difference) 

I suppose that the measurements from the Kamtron are more real but I actually have no really idea at this point :)  

I just want to understand which measurement are more accurate and stick with them (even though would be a shame to lose one month of measurements) In the reality I actually have not idea if it's a scale, app or other error.

**Additional context**
Unfortunately I can't measure anymore with the old scale (I changed house)

**Comment by mzzntn** [comment]
I just noticed that in #637 #543 #412 similar problems are mentioned

**Comment by oliexdev** [comment]
so the other values are from the Kamtron scale?

**Comment by mzzntn** [comment]
Yes, from the 29/10 to 20/11

**Comment by oliexdev** [comment]
then it could be possible that the mi scale use some different definitions of the muscle mass and so on. You can't compare different scales from different vendors.
