### ISSUE TITLE
A menu is missing the dark theme

### ISSUE THREAD

**Issue by naoliv** [oliexdev/openScale#656]
**Describe the bug**
It seems that one menu is missing the dark theme.

**To Reproduce**
When using the dark theme and clicking at the  **⋮**  menu:

![1](https://user-images.githubusercontent.com/982338/100363347-5b3d0100-2fdb-11eb-81de-c8d6144da382.png)

It's possible to see that the menu isn't properly themed (it's using a light theme):

![2](https://user-images.githubusercontent.com/982338/100363343-5a0bd400-2fdb-11eb-9afa-aa3d19cff7dc.png)

Reproduced with version `2.3.3-light`

**Comment by PavelGorbanj** [comment]
if I chose Light scheme, I see the same 3 items. @oliexdev, should this issue be closed?

**Comment by naoliv** [comment]
> if I chose Light scheme, I see the same 3 items. @oliexdev, should this issue be closed?

Why sould it be closed?
The menu should be dark when using the dark theme, like this one:

![](https://user-images.githubusercontent.com/982338/108211614-a9116300-710b-11eb-9fdd-265c38267622.png)

**Comment by oliexdev** [comment]
@naoliv then fix it?

**Comment by naoliv** [comment]
> @naoliv then fix it?

I really wish I knew how to fix this and other issues.

**Comment by oliexdev** [comment]
you could learn it, that's why it tagged as "good first issue". I would appreciate it.

**Comment by oliexdev** [comment]
should be fixed in the latest dev build
