### ISSUE TITLE
FitIndex ES-26M question

### ISSUE THREAD

**Issue by niladrieko** [oliexdev/openScale#660]
**Scale name**
FitIndex ES-26M

Is the FitIndex ES-26M still supported ? According to https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale it is but I am unable to get it to work with the OpenScale app. I looked at the code in `BluetoothQNScale` and looks like it expects to connect to the scale in order to read the measurements. But on inspecting the adv packet the scale seems to be advertising as "not connectable" 

I bought the scale here https://smile.amazon.com/gp/product/B078HW8BPY/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1.

**Comment by oliexdev** [comment]
I don't own this scale, so I don't why. According to a quick search https://github.com/oliexdev/openScale/issues?q=es+26m some had the same problem but resolve it and were able to connect.
Btw you need to unpair your device with the smartphone to able to connect with openScale. I even don't no if the offiicial app interfer the connection.
