### ISSUE TITLE
Have openscale work with gadgetbridge (open source smartwatch app also on f-droid)

### ISSUE THREAD

**Issue by famewolf** [oliexdev/openScale#665]
**Is your feature request related to a problem? Please describe.**
No.   I would just like to see the two open source products work with each other.  It's possible you could pull information from the smartwatch which would help make certain measurements more accurate.  They could use weight as part of their calculations.

**Comment by oliexdev** [comment]
see https://github.com/Freeyourgadget/Gadgetbridge/issues/1291

**Comment by behrisch** [comment]
Just for anyone coming here via a search engine. The link has changed: https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/1291 but the issue is still open as of 2025-01-19
