### ISSUE TITLE
Scale Support Request: Renpho ES-24M Bluetooth Scale

### ISSUE THREAD

**Issue by famewolf** [oliexdev/openScale#668]
Renpho ES-24M Bluetooth Scale
product page:
https://renpho.com/collections/scale/products/renpho-es-24m-bluetooth-body-fat-weight-scale
vendors app:
https://play.google.com/store/apps/details?id=com.qingniu.renpho

To support a new scale it is necessary to gather some information.

Step 1: Read the general reverse engineer process

I have read the "how to reverse engineer a Bluetooth 4.x wiki."  Since the scale is not detected I'm unsure how far I can get with this.  I would assume the process would be similar to the Renpho ES-26M which is supported by openscale.

2. Find out the Bluetooth services and characteristic
OpenScale dev version was not able to find my scale. The log shows the scan starting and ending with no info in between.
BLE scanner Raw Data Screenshot attached.  The "iBeacon" shown in background of image is NOT the scale.  It was at bottom of page and showed "Not connectable" in Red before I clicked on "Raw Data".

![Screenshot_20201216-150610](https://user-images.githubusercontent.com/4558832/102401351-2c4df580-3fb1-11eb-8461-bc6729bf0d15.jpg)

**Comment by oliexdev** [comment]
You need to find the scale at least otherwise your might have a faulty scale. Does it work with the vendors app?

**Comment by famewolf** [comment]
It works fine with the vendor app and I made sure to step on the scale when searching for it in openscale.

**Comment by oliexdev** [comment]
I added a new FAQ entry at https://github.com/oliexdev/openScale/wiki/Frequently-Asked-Questions-(FAQ)#why-is-my-scale-not-found

**Comment by guix77** [comment]
See #769

**Comment by Androphin** [comment]
Same with model Renpho es-26m-w

Currently investigating.
