### ISSUE TITLE
See 7 day averages 

### ISSUE THREAD

**Issue by humgit1** [oliexdev/openScale#670]
Hey,
I would really like to have a feature, where one could see 7 day weight averages. Both in numbers and the graph.
Daily weight fluctuations are really meaningless, averages provide much better data. 
The graph could have a switch function, and the numbers in the table could have an extra column where your weekly average is written. Alternatively the red and green arrows that show if your weight is going up and down, should represent weekly data and trends, rather than daily
Just so get an overview if your weight is going up, down or stays the same on a weekly basis.
I don't have any programming skills, but I would be happy to provide support with this Idea.

**Comment by oliexdev** [comment]
just change the view in the graph to week.
