### ISSUE TITLE
Tutorial text is invisible when system theme is dark

### ISSUE THREAD

**Issue by str4d** [oliexdev/openScale#674]
**Describe the bug**
The tutorial text is not readable when the system theme is set to dark mode.

**To Reproduce**
1. Set system theme to dark.
2. Install openScale dev app.
3. Open for the first time.
4. Briefly see the main app's background is dark.
5. Tutorial pops up.
6. The tutorial's background is white, but the regular text is also white, so it is invisible. Images are visible, along with linkified text (which is blue).

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): Yes.

**Expected behavior**
I can read the tutorial, because either the tutorial background is dark per dark theme, or the text is dark per light theme.

**Comment by oliexdev** [comment]
hmm this should be fixed in the latest release. Which Android version do you have? Could you attach a screenshot?

**Comment by oliexdev** [comment]
Which openScale version do you use?
