### ISSUE TITLE
Bluetooth connection issues with supported Xiaomi Mi scale v2

### ISSUE THREAD

**Issue by stepeck** [oliexdev/openScale#676]
Hi,
I bought the Xiaomi scale for it is listed as fully supported.

Well, in the Bluetooth connection app of android i can scan and see the device but not been able to connect with the hint "connection only possible with an app".

In openscale the same issue: detection possitive but no connection possible.

So I installed BLE scanner and  detect the scale too even seeing data transfered.

Scanning in Openscale results in:

_Suche beendet  
MI Band 2 [xx:xx:xx:xx:xx:xx]  
Gerät wird nicht unterstützt  
MIBFS [xx:xx:xx:xx:xx:xx]  
Gerät wird nicht unterstützt  
Wird deine Waage nicht unterstützt?  
Klicke hier, wenn du helfen möchtest_

What am I missing?

Do I have to install the original app?

Thanks!

**Comment by oliexdev** [comment]
In openScale goto settings->Bluetooth search for the scale click on it and they click on the Bluetooth icon in openScale in the overview fragment.

**Comment by stepeck** [comment]
Hi,thats what I am doing. And this is the result:It is not possible to connect with the scale.With the original app everything is fine.Please check the Bluetooth name in the screenshot, maybe there is a new firmware/protocol?Yours sincerely
-------- Ursprüngliche Nachricht --------Von: OliE <notifications@github.com> Datum: 08.01.21  11:29  (GMT+01:00) An: oliexdev/openScale <openScale@noreply.github.com> Cc: stepeck <stefan.peckruhn@eldikta.de>, Author <author@noreply.github.com> Betreff: Re: [oliexdev/openScale] Bluetooth connection issues with supported Xiaomi Mi scale v2 (#676) 
In openScale goto settings->Bluetooth search for the scale click on it and they click on the Bluetooth icon in openScale in the overview fragment.

**Comment by oliexdev** [comment]
The Bluetooth name is the same for mi scale v2.
