### ISSUE TITLE
Questions about measurement settings (and Feature Request: In-app FAQ/guide)

### ISSUE THREAD

**Issue by e-t-l** [oliexdev/openScale#679]
I have a few questions about how to navigate the app and realized it would be great to have an in-app FAQ or navigation guide. In addition to that, I'd appreciate if anyone can answer the following Qs:

1. In the measurements settings menu, the gear icon next to each measurement's toggle switch just gives a checkbox that says, "Is on right axis." What does this mean?
2. The symbol for Thigh Measurement shows an arrow going around both thighs, but most fitness measurements (including Renpho's official guide) direct users to measure the circumference of a single thigh, not both thighs together. When entering a thigh measurement, is it indeed appropriate to only enter a single thigh's circumference? (And if so, can we fix that icon?)

It would be great to include a drop-down containing brief instructions on _how_ to take each body measurement (e.g. When a user taps on "Waist Circumference" on the Overview page, they get a drop-down that says, "Wrap measuring tape flat around stomach and back at belly-button height, and exhale normally." etc.)

**Comment by oliexdev** [comment]
> In the measurements settings menu, the gear icon next to each measurement's toggle switch just gives a checkbox that says, "Is on right axis." What does this mean?

Defines If the data is associated to the right or left side of the y axis in the chart. Just play around and you will see what it mean.

> The symbol for Thigh Measurement shows an arrow going around both thighs, but most fitness measurements (including Renpho's official guide) direct users to measure the circumference of a single thigh, not both thighs together. When entering a thigh measurement, is it indeed appropriate to only enter a single thigh's circumference? (And if so, can we fix that icon?)

sure send a PR with a better svg icon.

> It would be great to include a drop-down containing brief instructions on how to take each body measurement (e.g. When a user taps on "Waist Circumference" on the Overview page, they get a drop-down that says, "Wrap measuring tape flat around stomach and back at belly-button height, and exhale normally." etc.)

That's too much detail and individual this will only blown up the app.
