### ISSUE TITLE
Libra scale missing other measures than weight and metabolic rates

### ISSUE THREAD

**Issue by bam93** [oliexdev/openScale#685]
Hi,

I use both the free development version, and more recently the pro version of openscale. I can successfully connect my libra scale to the app, but it only measures basic weight and calories. The body fat etc. measures are neither performed on the scale nor received by the app. I suspect that when the official runtastic service for libra stopped, something got broken, and now (I guess) the app needs to initialize something on the scale for it to work again. Any suggestions/help for this?

Thanks,
MB

**Describe the bug**

**To Reproduce**

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**

**Additional context**

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.

**Comment by oliexdev** [comment]
I don't know, I don't own this scale but you could do a full reset on your scale and try again. Backup up your data first.
