### ISSUE TITLE
Make goal optional

### ISSUE THREAD

**Issue by TheLastProject** [oliexdev/openScale#690]
**Is your feature request related to a problem? Please describe.**
The app forces me to set a goal weight even though I don't really have any specific goal, I just want to be within a healthy BMI range. I also don't really have a set date in mind either.

**Describe the solution you'd like**
Make the goal weight and date optional.

**Describe alternatives you've considered**
Goal range? Then I could use the BMI range as goal even though that would still be an extra lookup unless the app could calculate this for me. But it will still have a date for when to reach that goal which I feel I don't need.

**Additional context**
I just want to track my weight to keep an eye on it. I used to use DroidWeight but that app is so old that it doesn't work properly anymore all the time (the reminders will randomly break for example). So I figured I would try another app but being forced to set a goal weight makes this app feel a bit overkill for me. Am I missing some design philosophy? Am I perhaps not the target audience for this app?

**Comment by oliexdev** [comment]
the whole statistic page needs to be rewritten (were you need the goal weight) but if you don't want to set a goal just set a random goal and goal date. You can disable the goal line in the settings.
