### ISSUE TITLE
AddUserTest always failing

### ISSUE THREAD

**Issue by eulerhm** [oliexdev/openScale#691]
Hi guys,

Running all tests of the current source code, an error always ocurrs with addUserTest:

 com.health.openscale.gui.AddUserTest > addUserTest[SM-M305M - 10] FAILED 
        org.junit.ComparisonFailure: expected:<[test]> but was:<[]>
        at org.junit.Assert.assertEquals(Assert.java:115)

I think the cause is likely to be related to the fact that the fragment (UserSettingsFragment) is not loaded. Thus the following assertion fails:

assertEquals("test", user.getUserName())

**Comment by oliexdev** [comment]
true but why you don't send a PR with the fix?
