### ISSUE TITLE
Weight not captured on libra-w

### ISSUE THREAD

**Issue by geggi69** [oliexdev/openScale#692]
The weight is not captured on Libra-w

The scale is connected to the phone, the weight appears on the screen but sometime the measure is not saved

**Comment by tomdeck** [comment]
I have the same issue using a Sanitas SBF 70.
I connect the phone to the scale, wait a few seconds, step on the scale. The weight does appear on the phone (even changes a few times) but once the scale changes to displaying the additional metrics the weight disappears from the phone and the measurements are not recorded.

**Comment by oliexdev** [comment]
without any clear bug report I will close this issue soon.
