### ISSUE TITLE
Xiaomi Smart Composition Scale V2 incorrect BIA measurements

### ISSUE THREAD

**Issue by Abs-beg** [oliexdev/openScale#698]
Hi, recently paid for the pro version on Android and there are a couple of issues I am seeing.

The first one isnt a huge issue but it only seems to display the historic measurements. If I stand on the scale and get a new set of measurements it doesnt show on the app if I sync it. It will show later after the scales have switched off and on again and the app is resynched.

The other issue is the more major issue in that all of the BIA measurements are incorrect. I am not expecting them to be spot on obviously but these are way off and displaying impossible numbers. Example below.

Total Body Water 40.05%
Muscle 100%
Body Fat 43.91%

If I use the Mi Fit app it shows the below numbers:

Water 58.5%
Muscle 80%
Body Fat 14.6%

Is there anything I can do to make these closer? As I dont want to continue using the Mi Fit app.

**Comment by oliexdev** [comment]
could be possible a bug in the reverse engineered calculation for some specific user settings. I wont look deeper sorry since it a lot of work, which I have once. if this happens everytime I would recommend to use the Mi Fit app.
