### ISSUE TITLE
Garmin Connect syncing

### ISSUE THREAD

**Issue by striker54** [oliexdev/openScale#702]
Hello,
I know that this feature was requested in the past without success, but maybe this feature can be implemented in a more simplistic manner?

Please check this project:
https://github.com/davidkroell/bodycomposition

I've test it and it works fine, sending the data.

If you could adapt it to the openScale app would be wonderfoul.

**Comment by oliexdev** [comment]
You have to sign in in the developer program to use their Garmin connect API (sync to their cloud), see https://developer.garmin.com/gc-developer-program/overview/ which I don't want.
Furthermore their license is not compatible with the GPLv3.
