### ISSUE TITLE
Which, if any, scale can be awakened by openScale?

### ISSUE THREAD

**Issue by Silverstar** [oliexdev/openScale#707]
Is there any scale, which is supported, which can be awaken by the app and perform the weighting process?
So I could have a weight on the scale permanently and query the scale for a measurement.
Thank you.

**Comment by oliexdev** [comment]
no sorry, the hardware works differently, only you trigger a pressure sensors on the scale the weighting is beginning.

**Comment by Silverstar** [comment]
Okay, I was hoping there is at least one which could be triggered by a command and not only by stepping on it. Thank you anyway for your great project.
I did not look into the diy scale yet, but I guess the microcontroller could be set to listen to e.g. a broadcast and then do measurements. If I get done spare time, I'll have a look at that.

**Comment by lbdroid** [comment]
How much battery do you want it to waste listening for a connection?
