### ISSUE TITLE
Calibration support

### ISSUE THREAD

**Issue by thunderbuddy85** [oliexdev/openScale#713]
**Is your feature request related to a problem? Please describe.**
Yes, weight is off by about 4-5lbs from home scale (non-smart)

**Describe the solution you'd like**
Add the option to calibrate the scale, the libra app before decommissioning had a calibration step before weighing

**Describe alternatives you've considered**
Not sure, buy a new scale? lol

**Additional context**
![20210309_085502](https://user-images.githubusercontent.com/80337902/110492487-da9c9f00-80b7-11eb-8d37-6af0337b4fba.jpg)

**Comment by oliexdev** [comment]
there is no calibration only a initialization. And who said that your non-smart scale has the correct value? Nevertheless the weight pressure are calibrated by the vendor. Furthermore the weight is calculated on the scale hardware. The weight is only transmitted via Bluetooth which is fetch by openScale.
