### ISSUE TITLE
Kamtron CS20M is supported

### ISSUE THREAD

**Issue by chiefymuc** [oliexdev/openScale#714]
I just wanted to report that the Kamtron CS20M is support. It shows up as QN-Scale on Bluetooth and just works.

Here is a link to amazon:
https://www.amazon.co.uk/Bathroom-Scales-Weighing-Body-Fat/dp/B07HH6DJHH

Some pictures here so that it can be transferred into the supported scales WIKI.

![Screenshot_20210317-141918](https://user-images.githubusercontent.com/9849753/111474658-913df680-872c-11eb-868a-dc279f82dc95.jpg)

![IMG_20210317_141655_](https://user-images.githubusercontent.com/9849753/111475840-c9920480-872d-11eb-9f51-3dd1eae120ef.jpg)

![IMG_20210317_141718_](https://user-images.githubusercontent.com/9849753/111475850-cb5bc800-872d-11eb-81af-a991cccb66b0.jpg)

Thanks for the cool App!

**Comment by oliexdev** [comment]
thanks for giving feedback and the scale photo, I have been added it to the wiki.
