### ISSUE TITLE
Best Commercial Scale

### ISSUE THREAD

**Issue by HolgBogarth** [oliexdev/openScale#719]
I am looking to purchase a "Smart" scale but would rather have my data local instead of in an overseas cloud.  Of the supported scales, which is the best in terms of functionality and reliability?  It seems like the Xiaomi Mi Scale v2 has all supported functionality but not sure if there are any issues with it.  Price is not really a concern but not all scales are available in the US like the Beurer models supported.

I know this is not a bug or scale support but did not see anywhere else to ask a general question.

**Comment by oliexdev** [comment]
please read the FAQ.
