### ISSUE TITLE
compatibility with ihealth HS2S weight scale

### ISSUE THREAD

**Issue by novalagung** [oliexdev/openScale#721]
hi, just wondering does openscale works with [ihealth HS2S](https://ihealthlabs.com/products/ihealth-nexus-wireless-body-composition-scale)? 

I saw on the readme openscale does works with iHealth HS3. is the current HS3 code can be used to consume data from HS2S?

Thank you in advance

**Comment by oliexdev** [comment]
I don't know, i don't own this scale. You can try it out if you want or if its too risky then don't buy it.
