### ISSUE TITLE
Kailona (NextCloud) data sync integration

### ISSUE THREAD

**Issue by proletarius101** [oliexdev/openScale#724]
**Is your feature request related to a problem? Please describe.**
It's hard to sync or migrate data in OpenScale, unless you manually export, which is inconvenient and prone to data loss. 

**Describe the solution you'd like**
[Kailona](https://docs.kailona.org/docs/) is an extensible, customizable and secure platform for your private electronic health records (EHR). It is available as Nextcloud application.

It's a good and standard place/format to save health records

**Describe alternatives you've considered**
Support Storage Access Framework or so to allow scheduled export to NextCloud/Google Drive

**Comment by oliexdev** [comment]
you can read https://github.com/oliexdev/openScale/wiki/Autosync-with-Nextcloud
