### ISSUE TITLE
Interested in using your code with embedded BLE with a scales 

### ISSUE THREAD

**Issue by PaulBoland** [oliexdev/openScale#725]
Hi,
I am developing an embedded BLE solution for looking after elderly people. The difference is it is truly independent and battery powered. I have many elements in trail production at the moment and I am now looking to link in with a BLE enabled scales.  For this I need to understand the protocol interaction which I see you have solved for many many scales.
I would like to know are you interested in discussing this with me.

Thanks
Paul B

**Comment by oliexdev** [comment]
I don't really understand your project a bit more information would be helpful. Any project site available?
