### ISSUE TITLE
Mi Scale XMTZCO1HM not pairing

### ISSUE THREAD

**Issue by GeorgeDouglasMcFly** [oliexdev/openScale#732]
Hey there,

I own a Mi Scale for many years and I haven't used it until today. I put in new batteries and removed the scale from my Mi Fit app because it wasn't found there. Afterwards I tried to pair it again, but it doesn't show up. Even with the openScale app it doesn't show up in the list. Is it possible that the bluetooth transmitter is broken? How can I fix this issue?

Best regards,
George

**Comment by oliexdev** [comment]
try it out with the original MiFit app if it still not working then it might be a hardware problem.
