### ISSUE TITLE
Q: why is Kcal commented out for Medisana 444?

### ISSUE THREAD

**Issue by lbschenkel** [oliexdev/openScale#734]
Hi, thanks for the great app. This is not a bug report. It is just a question I have, to satisfy my own curiosity.

I have a Medisana BS444 and I was looking at the source code to check what data the app was pulling from the scale. Then I noticed the following:
https://github.com/oliexdev/openScale/blob/cab0a627ed1491cee1247d5350bfb3ba18de5025/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS44x.java#L117

It appears that this has been commented out since the very beginning:
https://github.com/oliexdev/openScale/blob/29e67659a57b7ac5367424bbe8b9fb29200c47da/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java#L226

I was just wondering why the Kcal data is not used and has been commented out?

**Comment by oliexdev** [comment]
openScale uses for all scales the Harris-Benedict equation.
