### ISSUE TITLE
OneByOne: Bone mass calculation may be incorrect

### ISSUE THREAD

**Issue by ASerbinski** [oliexdev/openScale#743]
**Describe the bug**
Bone mass calculation involves the impedance value read from the scale, per
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/OneByoneLib.java#L68

This impedance value is calculated as the sum of the three bytes of the impedance coefficient as provided by the scale;
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOneByone.java#L149

However, the conversion of the impedance coefficient into an impedance value appears to be more complex;
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/OneByoneLib.java#L183

I believe that the latter conversion is correct, the one used by the bone mass function is incorrect and should be fixed.

**Comment by oliexdev** [comment]
close with PR #747
