### ISSUE TITLE
Ranges provided for muscle mass are not consistent with varied measurement calculations

### ISSUE THREAD

**Issue by ASerbinski** [oliexdev/openScale#744]
**Describe the bug**
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/evaluation/EvaluationSheet.java#L122-L139

Ranges provided for normal muscle mass are sourced from the user manual of some commercial/home scale per @oliexdev :

https://github.com/oliexdev/openScale/issues/637#issuecomment-706997564_
https://sanitas-online.de/media/download/751-737-1214_sbf70_de.pdf

Commercial home scales provide all kinds of different measurements.
This scale manufacturer suggests values around 70% (more likely to be lean body mass than muscle mass):
https://support.withings.com/hc/en-us/articles/220035767-Body-Cardio-What-are-the-normal-ranges-for-body-composition-

While these values may have some meaning, it is only within the context of what data these scales are actually providing, and subject to the errors made by these manufacturers in their interpretation of the meaning of the data they are providing, thus is not an appropriate range to be providing.

An academic source would be more appropriate.
https://journals.physiology.org/doi/pdf/10.1152/jappl.2000.89.1.81
See the "Relative SM" column in Table 1 of the 3rd page of the PDF (labeled page 83)

However, the reported ranges aren't necessarily representative of ideal, rather they are a sample of people who may together represent a normal range. Alternatively, it may be appropriate to use values provided by a fitness source that are consistent with academic records, such as; https://www.activ8rlives.com/support/data-collected/body-composition/muscle-mass/

**Comment by oliexdev** [comment]
closed with PR #746
