### ISSUE TITLE
Improved wiki

### ISSUE THREAD

**Issue by bcdiaconu** [oliexdev/openScale#764]
I modified a file in wiki. You can find the modifications here:
[How-to-reverse-engineer-a-bluetooth-scale.md as code](https://github.com/bcdiaconu/openscale_wiki/commit/cb891fe6f6316f85a3b82612362f85069c06e1c6)

[The actual look of it](https://github.com/bcdiaconu/openscale_wiki/blob/master/How-to-reverse-engineer-a-Bluetooth-4.x-scale.md)

**Comment by oliexdev** [comment]
thanks I updated the wiki page accordingly.
