### ISSUE TITLE
long press on chart to reset view

### ISSUE THREAD

**Issue by alekksander** [oliexdev/openScale#8]
currently to reset to default chart view (after zoom) is to restart app.

**Comment by oliexdev** [comment]
Hi alekksander,

thanks for your comment but you can just zoom out with your fingers you don't have to restart the app. ;)
But I will consider it to implement a reset view on a long press.

Best regards
Oli

**Comment by oliexdev** [comment]
I realised a chart reset view on a long press, see commit https://github.com/oliexdev/openScale/commit/aee8ef44bb9b36883eafd2381148b7e6ade0211b
