### ISSUE TITLE
Sizet ID115 not supported

### ISSUE THREAD

**Issue by Villelmo** [oliexdev/openScale#802]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i try link to device. 

**Describe the solution you'd like**
Add this device

**Describe alternatives you've considered**
Restart the device. 

**Additional context**
[https://user-images.githubusercontent.com/1309590/48314146-a5eeaa80-e5c5-11e8-97b7-c34427c210f0.jpg](url)

**Comment by oliexdev** [comment]
please fill out the [scale support issue](https://github.com/oliexdev/openScale/issues/new?assignees=&labels=scale+support&template=scale-support-request.md&title=) properly.
