### ISSUE TITLE
Add Samsung Health Sync

### ISSUE THREAD

**Issue by Weltraumpenner** [oliexdev/openScale#814]
I really like OpenScale, but I have a Galaxy Watch and would therefore prefer to use Samsung Health over Google Fit.

It would be awesome, if Samsung Health would be added to the supported Services.
Samsung is providing an API, so it should be possible.
https://developer.samsung.com/health-server/server/partner-only/api-reference/data-access.html

Of course it would be possible to Sync it from openScale to Google Fit and then to Samsung Health, but I would like to skip Google Fit.

**Comment by oliexdev** [comment]
Did you check if their license is open source compatible?

**Comment by QuentinLemCode** [comment]
@oliexdev What about using Health Connect ?
