### ISSUE TITLE
Issue on App to detect the Yunmai Mini

### ISSUE THREAD

**Issue by fquintela12** [oliexdev/openScale#817]
I have a Motorola mobile completed updated and when I open the app and click on Bluetooth icon and try to mensure my weigth and the app does not find the scale.

I need to try several time clicking on the Bluetooth icon to get the scale detected.

I have Yunmai scale.

Thank you,

**Comment by oliexdev** [comment]
low battery on your scale or you have to turn your scale on before searching?
