### ISSUE TITLE
Weight of different user showed in overview after live measurement

### ISSUE THREAD

**Issue by mirko-laruina** [oliexdev/openScale#818]
**Describe the bug**
After a live measurement is taken, the weight showed for the given user is not the one actually measured but it belongs to a different user. In particular, it referes to the user originally selected on the spinner component.

**To Reproduce**
1. Open Overview
2. Select a different user from the spinner
3. Take a measurement
4. The overview will update with the weight of the previously selected user.

Switching users fixes the issue

Reproduced with my custom fork where I'm implementing the support for a new scale model ( https://github.com/mirko-laruina/openScale ).

I think the problem is relative to `getScaleMeasurementsLiveData()` being called with the original user and not being updated after the switch

**Comment by oliexdev** [comment]
I can't reproduce this behaviour. Did you take a measurement via Bluetooth or a manual add? Did you enable the smart user assignment?
