### ISSUE TITLE
Body fat, lean mass are zero.

### ISSUE THREAD

**Issue by 0xc1f1** [oliexdev/openScale#821]
**Describe the bug**
When enabling the estimation of body fat and/or lean mass it always returns zero no matter what estimation formula is chosen or what weight, height etc I put in.

I have supplied weight, waist circumference, biceps circumference, neck circumference.

**To Reproduce**
1. Go to Settings -> Measurements
2. Click on the body fat toggle button to the right.
3. Click on body fat and enable "Estimate measurement".
4. Go back to "Overview" and you will see body fat is zero. This also goes for "Table" and other pages.

Reproduced with version 2.4.5 and other older versions found on fdroid.

**Expected behavior**
I would imagine that my body fat is a bit higher than 0 kg or maybe I just need to stop my cut.

Should it be the case that this results from me not having put in certain measurements I think that should be more clearly specified.

**Additional context**
I own a Google Pixel 4a that has Graphene OS(Android 12) flashed on it.

**Debug log**
My debug log does not list anything interesting outside of the profile I selected which I would prefer not to share but can do so if you believe it would help in anyway.

**Comment by oliexdev** [comment]
If you turn on the estimate measurement option it will only estimate the body fat / lean mass for new measurements not for old ones.
