### ISSUE TITLE
Export, edit and import question

### ISSUE THREAD

**Issue by KrazyLurt** [oliexdev/openScale#829]
I have a problem when importing a edited exported csv. It's a format issue. 
I have no issue opening a exported csv i Open Office choosing  Unicode (UTF-8) ,  comma
Saving brings up a notification that only text is saved.
Importing to OpenScale results in a format error.
A short guide would be helpful

**Comment by oliexdev** [comment]
What kind of guide? Open your saved csv file with a text editor and look at it, maybe OpenOffice changed the format if they are saved back. You can see the CSV openScale format if you just save an example and open it with a text editor.
