### ISSUE TITLE
Is Fitindex ES-26M officially supported in Openscale now?

### ISSUE THREAD

**Issue by ryan-johnson1970** [oliexdev/openScale#836]
I just placed an order because I saw the scale “partially” supported according to the wiki page. I’m trying to build an app that has to read scale values aMong other things and was hoping to use openscale as the reference implementation to learn from.  But after ordering I saw several issues reported as well. Can someone please let me know of it is officially supported?

Thanks

**Comment by oliexdev** [comment]
it works limited in openScale because the used QN library has not been revered engineered yet. But openScale will not guarantee if the scale will work... its still a hobby project.
