### ISSUE TITLE
Cannot get any measure from the scale even if app says "Connected" and "Please step barefoot on the scale"

### ISSUE THREAD

**Issue by noisemaker00** [oliexdev/openScale#843]
**Describe the bug**
Cannot get any measurement from scale.  Here the scale data:
Manufacturer: 1byone
Model: CF398BLE

**To Reproduce**
1. Open app
2. Click on BT icon
3. I get toasts with "Connected" and then "Please step barefoot on the scale"
4. I step on my scale but nothing appens

Reproduced with v2.4.5(60)

**Expected behavior**
When I step on scale app should register the measurements data

**Comment by oliexdev** [comment]
please add the openScale debug log file
