### ISSUE TITLE
Can't Detect FitIndex ES-M26

### ISSUE THREAD

**Issue by Plokmju22** [oliexdev/openScale#848]
**Describe the bug**
I'm unable to detect my FitIndex ES-26M-W using the app. The scale shows up fine in the FitIndex app so I think the scale is working, but it doesn't show up at all in openScale. I'm confused because it's listed as supported.

**To Reproduce**
1. Click on **Settings**
2. Click on **Bluetooth**
3. Click on **Your Bluetooth scale -**
4. Step on the Scale
5. Scale isn't detected

Reproduced with [a7c4d54](https://github.com/oliexdev/openScale/commit/a7c4d542529136eafa5549d1111ca00a4e0be750)

**Expected behavior**
Scale appears when searching and can be paired with openScale.

**Additional Information**
I've never paired any scale with openScale before, and it is currently unpaired to any other app (including the FitIndex app; I unpaired it after checking).

**Comment by oliexdev** [comment]
see #752 but I will remove the scale from the supported list.
Could you post your scale max address?

**Comment by Plokmju22** [comment]
Yep!

MAC Address is ED:67:38:F4:F2:33

I will review #752 right now; I appreciate all of your help.
