### ISSUE TITLE
Cannot get data from Xiami Mi Scale v2

### ISSUE THREAD

**Issue by Strubbl** [oliexdev/openScale#849]
**Describe the bug**
I get no data although the connection to scale was established

**To Reproduce**
1. install dev build (commit a7c4d542529136eafa5549d1111ca00a4e0be750)
2. Start app
3. add user
4. select scale
5. finish starting wizard
6. enable bluetooth via button
7. wait
8. see toast with connecting state
9. see toast with connected state
10. wait
11. see toast with disconnected state
12. see no data has arrived

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): yes

**Expected behavior**
Downloaded data from the scale can be seen e.g. in the table view of the app

**Additional context**
Device: Samsung SM-S901B
OS version: Android 12 (SDK 31)

This is a new device. The app was working fine with the Samsung S9 before. I imported the CSV and i know there are some new measurements since the last measurement in the CSV.

**Debug log**
see https://gist.github.com/Strubbl/f04909c7d3be78318b95967eebd1f35c

**Comment by oliexdev** [comment]
Did you also don't get measurement when you weight yourself?

**Comment by Strubbl** [comment]
No, i can confirm i can get new measurements. So only the old ones are missing. I can import them via csv. I think this issue can be closed.
