### ISSUE TITLE
wiki page "development version" link is broken

### ISSUE THREAD

**Issue by vn971** [oliexdev/openScale#852]
On this wiki page: https://github.com/oliexdev/openScale/wiki/How-to-reverse-engineer-a-Bluetooth-4.x-scale#2-find-out-the-bluetooth-services-and-characteristic

there is section 2.1 that says "Install the openScale development version" which points to a *travis-CI* build of the app. The link is broken and no longer works.

Instead, I think we want to reference the "dev-build" release on github, built via github actions/workflows. This is also the same link that is mentioned in the top section of the README.md: https://github.com/oliexdev/openScale/releases/tag/dev-build

I don't know how to make a PR against the wiki so I've created this issue here.

Cheers

**Comment by oliexdev** [comment]
Thanks fixed it.
