### ISSUE TITLE
How to use the app ?

### ISSUE THREAD

**Issue by 9ycbgf0k8fpg** [oliexdev/openScale#854]
Hello

I got myself a Xiaomi Body scale V2 and I am having trouble understanding how to use OpenScale with it even though I am somewhat tech literate. I have successfully connected the scale to the app and I got some readings from it, but I can not do it reliably. Here are my questions : 

- Am I supposed to use the app each time you want to make a measurement ? Or can I weigh myself a few times and then collect the data some days later ?
- If I am supposed to use the app each time, when do I need to step on the scale ? When I connect the app and step on the scale, I don't get any new data when I click on the "+" to add a measurement.

Overall I think there is a lack of clear instructions on how to use the app that should be addressed. 

Thank you for your work on this open source application !

**Comment by oliexdev** [comment]
It depends on your scale. With your Xiaomi Body scale v2 you have to initial your scale with openScale. After that you can measure yourself without the app. openScale can fetch the history measurements with this scale. But it is important that you don't mix the vendor app with openScale. For technical details read https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale

The "+" is for manual adding a measurement.
