### ISSUE TITLE
RENPHO RP-520BT - Import Data Problem + Missing Measurements

### ISSUE THREAD

**Issue by n7mafia** [oliexdev/openScale#855]
Hi, I've got two issues:
1) I tried syncronizing my measurements with Open Scale with a Renpho RP 520BT, OpenScale manage to read only partially the measurements. It gets Weight and BMI but misses basically all the rest (total body water, muscle, body fat etc)
2) I tried importing data (previously exported in a CSV by the Renpho App on a file with apparently correct headers (Time of Measurement, Weight (KG), BMI, Body Fat etc... but I get a "Could not import: Header line not valid, Time of Measurement..."

**Comment by oliexdev** [comment]
1) Could be possible that the rest measurements are not supported
2) You need to write a script that convert your exported CSV form the Renpho App to the correct format of the openScale CSV format, see https://github.com/oliexdev/openScale/wiki/Useful-import-scripts for some examples.
