### ISSUE TITLE
Export dir path prefix

### ISSUE THREAD

**Issue by FifiTheReal** [oliexdev/openScale#859]
**Describe the bug**

Since last release i can't modify export path, because export path has path prefix:
"/storage/emulated/0/Android/data/com.health.openscale.pro/files/"

I would like use "/storage/emulated/0/Download/openscale-Backup" as before but i can't do it.

**Debug log**
[openScale_2022-05-15_16-40.txt](https://github.com/oliexdev/openScale/files/8695281/openScale_2022-05-15_16-40.txt)

![Screenshot_20220515_163808_com health openscale pro](https://user-images.githubusercontent.com/34412887/168480523-adadad10-d2b0-4c9a-9354-4dd41f0ae0d0.jpg)

**Comment by oliexdev** [comment]
That's not possible anymore because in >= Android 11 they change the storage permissions, see https://developer.android.com/about/versions/11/privacy/storage
You cannot create in the background files that are outside your app scope.
