### ISSUE TITLE
Datatransfer Beurer BF720 to openScale does not work

### ISSUE THREAD

**Issue by domenicoromeo** [oliexdev/openScale#868]
Hello 

I was able to connect my phone and the openScale app to the Beurer BF720 successfully. 
I was also able to create an user within the openScale app.
I set only one user.
The openScale app connects via Bluetooth to the scale.
The scale takes measurements (displays the weight on the scale).

**--> After displaying the weight on the scale displays the value are not transmitted to the openScale app.**

The scale indicates on the bottom left of the display following symbol: "_ _ _". 
According to the manual this means: "Unknown measurement as it is outside the user assignment limit or a unique assignment is not possible"

I expect to get the measured values of the scale transferred to the openScale app.

Do I miss something in the settings or what do I have to do to fix this?

regards
Domenico

**Comment by AlBundy33** [comment]
maybe you have to setup your scale correctly so that the scale can assign the weight to your profile.
as i understand `_ _ _` means something like guest-mode

maybe you can change the profile with the set-buttons on the scale
