### ISSUE TITLE
self-hosted sync

### ISSUE THREAD

**Issue by zeugor** [oliexdev/openScale#870]
**Describe the solution you'd like**
I would like to have openScale installed in multiple Android terminals, and when we add a new measure in one of the terminals the change is applicable automatically in every terminal openScale instance.

**Describe alternatives you've considered**
Currently openScale offers scheduled backups. But in order to apply the change in other terminal, we need to import it manually.

**Additional context**
The synchronization issue could be self manage with google-drive, dropbox, syncthing...

**Comment by oliexdev** [comment]
you could use openScale sync.
