### ISSUE TITLE
BMI color scale is skewed in comparison with WHO classification

### ISSUE THREAD

**Issue by martin-kokos** [oliexdev/openScale#875]
**Describe the bug**
BMI color scale is skewed in comparison with WHO (World Health Organization) classification https://en.wikipedia.org/wiki/Body_mass_index#Categories
While openscale uses 24.5 as a center point, WHO considers 25 and higher as "overweight". 21.7 would be the center point of "normal range" by WHO

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Body mass index (BMI)'
3. See blue-green-red color bar

Reproduced with: 2.4.6

**Expected behavior**
BMI color bar should be according to some accepted source so people don't judge their health according to wrong metric.

**Additional context**
openScale:
```
          25
,----,----,----,----,
    ---oooooo+++ 
```
WHO:
```
          25
,----,----,----,----,
----oooooo+++++
```

**Comment by oliexdev** [comment]
The evaluation of the BMI depends on the age and the sex.
