### ISSUE TITLE
Visceral fat from Mi Body Composition Scale 2

### ISSUE THREAD

**Issue by datruccone** [oliexdev/openScale#880]
**Describe the bug**
Hi there, I noticed that the Visceral Fat showed by Open Scale is way higher than the one reported by official Zepp app and also Notify for Mi Band, about 16 vs 12.
I see on MiScalelib that Visceral Fat is calculated based on Height, Age, Gender and Weight and not using impedance at all nor using Waist/Hip ratios 
I'm not an expert either on the Mi Scale nor nutrition but is this the right method to calculate Visceral Fat?, why it could be the difference between Open Scale and both Zepp and Notify?

**Expected behavior**
Same value as Zepp and Notify (if they are right).

**Additional context**
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/MiScaleLib.java#L48

**Comment by oliexdev** [comment]
Could be possible that they have changed the calculation in the new Zepp Life app. We reverse engineered the official old Mi app. Unfortunately, the body calculation of the vendors app are totally intransparent.
