### ISSUE TITLE
multi user issue with body fat

### ISSUE THREAD

**Issue by aisbergde** [oliexdev/openScale#882]
**Describe the bug**
The Mi scale is used by different persons with different weigh. Normally when importing the measures they are correctly separared by user. And the imported values should not depend on the user selected on the overview tab.
But depending on the selected user at the moment when the app connects to the scale the imported values for body fat are different. They are wrong, if not the person is selected, which currently uses the scale.
Here you see wrong values for the last 2 days. The values are wrong for both users, using the scale.

![Screenshot_2022-09-20-08-03-47-034_com health openscale](https://user-images.githubusercontent.com/9020187/191180821-4c7eca44-e723-436a-a446-3fe9783d2fc1.jpg)
![Screenshot_2022-09-20-08-04-35-784_com health openscale](https://user-images.githubusercontent.com/9020187/191180854-d8ac0b17-a7c3-42ca-867f-6c8840514201.jpg)

It looks like the issue is related only to body fat. The settings are to import the body fat, but not to calculate.

**To Reproduce**
* Use scale by 2 persons with different weight
* enable the settings
** smart user assignment
** ignore out of range data
** merge with last measurement
* select on the overview the person, which will use the scale
* press the Bluetooth icon and step on the scale
** the right values should be imported
* next day (or just later, to avoid merging values)
** in the overview windows select not the person, which will use the scale, but the second person.
**  press the Bluetooth icon and step on the scale
** wrong values for body fat be imported

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build):
latest version, available on f-droid is used
v2.4.6 (61)

**Expected behavior**

* values should be imported consistently not depending on the person, currently selected in the overview window
* correct values should be imported

**Comment by aisbergde** [comment]
same issue for visceral fat
![Screenshot_2022-09-20-08-34-08-340_com health openscale](https://user-images.githubusercontent.com/9020187/191184496-004b10ab-45ba-42a2-8566-f1719af1eaa4.jpg)

**Comment by oliexdev** [comment]
Could you try to disable the "merge with last measurement" option to see if this problem still happens?

**Comment by aisbergde** [comment]
I will try tomorrow

**Comment by aisbergde** [comment]
I disabled. But is does not read the current value, when I enable Bluetooth and step on the scale. But if I now disable Bluetooth and enable, it imports the last value. I need to experiment a bit in the next days what will be the best workflow.
