### ISSUE TITLE
Can't connect on BF800

### ISSUE THREAD

**Issue by Dariodom** [oliexdev/openScale#883]
Hi! I just bought this app since my BF800 can't, as many say, connect to my phone via bluetooth using Beurer Health Manager app.

Unfortunately i cannot connect also using this App, can anyone help me? (I actually don't know if is a bug, a problem or the Scale is not supported)

Ps. I really apprecciate this initiative, i think you are great!

**Comment by oliexdev** [comment]
sorry your scale is currently not supported, see https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale

**Comment by Dariodom** [comment]
But on the link you sent me it says that Beurer BF800 is fully supported!

https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale

Il Gio 8 Dic 2022, 14:25 OliE ***@***.***> ha scritto:

**Comment by oliexdev** [comment]
sorry you are right but if it doesn't connect with the original vendor app then your scale or your bluetooth is faulty. Did you enable Bluetooth, do you enable location permission? Could you paste the openScale debug log file here when you try to connect to your scale?

**Comment by Dariodom** [comment]
I tried everything and nothing seems to work but many people have the same
problem, i think the problem it's not in the scale but in the app itself.

Il Ven 9 Dic 2022, 09:31 OliE ***@***.***> ha scritto:
