### ISSUE TITLE
Xiaomi Mi 2 - No reference user available

### ISSUE THREAD

**Issue by IntinteDAO** [oliexdev/openScale#886]
Hello, I have a Xiaomi Mi Body Composition 2. For many interactions I get a message

> No reference user available, please create one

I don't really understand what he means. I have a user added to OpenScale, and the scale itself has a Bluetooth connection to the app, and OpenScale is able to retrieve data (not entirely correct, I think, but that will be thought of later) from the scale.

In addition, it's nice if each input to the scale allows the user to download data, not those "forced" by OpenScale.

**Comment by oliexdev** [comment]
You have enabled the assisted weighting option in the user setting. For that you need at least two users, one as a reference user.
