### ISSUE TITLE
is it possible to sync only one user from the scale?

### ISSUE THREAD

**Issue by AlBundy33** [oliexdev/openScale#888]
II play with the idea to buy a Xiaomi body composition scale 2 (because of the price) or a Beurer BF720 (because it seems that it can be used standalone without the vendors app).

If I create two users on the scale is it possible to sync my user only to openecale on my device and the secind userin another device (e.g. girlfriends phone)?

how does openscale knows what data belongs to what user?
afail BF720 stores the name of the user but only up to 30 datapoints.
So it would be good to know that openscale is capable to select only the data of the correct user because I'm not sure if BF720 deletes the data after sync.

https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale
What does "Initialisation process" and "History data" mean?

Means "Initialisation process" I can buy the scale and can ignore the vendors app (and cloud) and just start with openScale?

**Comment by AlBundy33** [comment]
Currently I have one user in my Beurer BF720 and it works as expected.

I'll ask again if I add an additional user 😄

**Comment by 6b6279** [comment]
Hello, sorry for bumping this older thread, but I just setup the BF720 with the openScale app and I have noticed that the user I have created on the app wasn't correctly synced with the scale, so that, e.g., the gender of the user on the scale was incorrect. Have you had a similar issue with the BF720?

**Comment by AlBundy33** [comment]
I've also created the user on the scale.
OpenScale shows my data correct but I can't remember if I maybe changed the data manually.
