### ISSUE TITLE
Feature request; calculate and display last seven day's average as additional statistics option? 

### ISSUE THREAD

**Issue by zorbathegreek** [oliexdev/openScale#899]
First of all, great app! I use it manually for myself and another person. Easy, intuitive usage.
 
My weight fluctuates a little every day (but I think that is so for everyone) and I have problems to see the "bigger picture" early on. So I exported my values to .csv and opened and played around with that in a spreadsheet, and came up with a non-revolutionary, however eye-pleasing result. I just created another column in the spreadsheet by calculating the arithmetic average of the last 7 days. When I display those numbers over time, I can see much better where my weight is heading.  Please see the pictures that follow. 

![Sverre_daily_weight](https://user-images.githubusercontent.com/19348109/202507526-e7c18ab4-54e9-47b6-917d-c9f8ec83789f.png)

![Sverre_7_day_average_weight](https://user-images.githubusercontent.com/19348109/202507593-f0693c7e-38b0-4b4a-ad9a-b574b03b57d5.png)

Would it be possible to calculate the average of the last seven days and display those numbers over time as a graph, just as now we see the daily weight values in the "standard view", e.g. by pressing an extra button in the statistics section? 

I tried the same with monthly averages, but they tend to have little meaning, optically, when the fluctuations aren't all that drastic. 

In the code, we have to include/ignore days with/without values, and adjust the divisor accordingly. Logically, the first seven days at the beginning of the list also have no value (no proper result).

**Comment by oliexdev** [comment]
openScale used the the Hacker's Diet Libra like trendline based on an exponentially smoothed moving average calculation, see https://www.fourmilab.ch/hackdiet/e4/pencilpaper.html

You can enable the "week view" in the chart to smooth the graph.
