### ISSUE TITLE
[FR] Dark theme

### ISSUE THREAD

**Issue by woj-tek** [oliexdev/openScale#91]
It would be cool if the application had a dark/black theme.

**Comment by retro-78** [comment]
+1

**Comment by oliexdev** [comment]
good idea but need to figure out how to implement that. I don't really like the xml stuff in android... :/
so any help are welcome.

**Comment by oliexdev** [comment]
done with commit https://github.com/oliexdev/openScale/commit/2dc40e4bc45adcfd867b4f9e14ac60e4da2c662a

**Comment by erijo** [comment]
Nice work @oliexdev, looks really nice!

One thing I noticed is that the text color and indicator color in the gauge should probably not be black.

**Comment by oliexdev** [comment]
I missed that one. It is fixed now. :smile:

**Comment by erijo** [comment]
:+1:

**Comment by erijo** [comment]
One more thing: should the text color really be gray for the light theme? It doesn't look as good as it did before when the text was black (IMHO).
