### ISSUE TITLE
Export weight in kg not pounds

### ISSUE THREAD

**Issue by mfshapiro** [oliexdev/openScale#920]
**Describe the bug**
My weight in the app shows in pounds but gets exported to the CSV file in kilograms. I can't find any setting option to fix this.

Also, the export contains all columns, even those I've disabled in the display options. Not a big deal because I can delete the "empty" columns from the CSV file, but it would be nice to only export selected data elements.

Thanks for your help.

**Comment by oliexdev** [comment]
Sorry that's intended behavior of openScale. The base unit is kg. Any other unit are calculated from kg. With the exported data you can easily calculate your unit.
