### ISSUE TITLE
Notifications permission not requested (Android 13)

### ISSUE THREAD

**Issue by TinfoilSubmarine** [oliexdev/openScale#928]
**Describe the bug**
The reminder is not showing up as a notification after updating to the latest version (2.5.0). When going into android settings for the app, the notifications are unable to be toggled on.

**To Reproduce**
1. Enable reminder.
2. Wait until specified day/time.
3. See that notification/reminder never pops up.

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???

**Expected behavior**
A reminder notification should pop up at the specified day/time.

**Comment by oliexdev** [comment]
thanks for the hint, should be fixed now in the latest dev build. Please try it out.
