### ISSUE TITLE
For chart, add axis labels and grid lines

### ISSUE THREAD

**Issue by CameronNemo** [oliexdev/openScale#933]
**Is your feature request related to a problem? Please describe.**
It is difficult to tell what each data point in the plot represents, weight wise. I'd like to be able to easily glance and see what the weights are.

**Describe the solution you'd like**
Y-axis labels and grid lines allow me to see immediately what weight each of the data points represent.

**Describe alternatives you've considered**
Clicking/tapping on the data points: cumbersome, especially when there are many data points

**Additional context**
I think before the latest update this was actually part of the chart. Not sure why it was removed, if so.

**Comment by oliexdev** [comment]
in the chart page all axis and grids are shown. In the overview not because there is not much space and not needed.
