### ISSUE TITLE
Bug report template has broken links

### ISSUE THREAD

**Issue by mnalis** [oliexdev/openScale#939]
**Describe the bug**
Bug template contains broken link to https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

**To Reproduce**
1. Go to https://github.com/oliexdev/openScale/issues
2. Click on 'New issue' and `Bug report`
3. textarea will fill with template that says `Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): ???`
4. trying to visit https://github.com/oliexdev/openScale/releases/tag/travis-dev-build gives `404 not found`

**Expected behavior**
Links mentioned in template should work

**Additional context**
This is bug about a bug reporting system, not  about app itself

**Debug log**

**Comment by oliexdev** [comment]
thx should be fixed
