### ISSUE TITLE
Add SBF73 its same SBF72

### ISSUE THREAD

**Issue by davvarrr** [oliexdev/openScale#940]
Hello, I just bought a scale SBF73 it and not support, but seen that the SBF72 is well recognized I tested by changing just the SBF72 in SBF73 and it works very well, the user already created on the scale is well recognized and all the information on the body are also.

if you need pictures of the app said the month, for the moment I will keep the one I created to support the SBF73

I don't know how to extract the log ble and sorry for my english I translate them by deepl

**Comment by 2spirit** [comment]
Hello, where do you change the name SBF72 -> SBF73 ?

**Comment by 2spirit** [comment]
OK, I found it , @oliexdev , in ./android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
line 130 , you can add "deviceName.equals("SBF73")"

Thanks !
