### ISSUE TITLE
Black fonts on grey backgrounds are hard to read

### ISSUE THREAD

**Issue by glocalglocal** [oliexdev/openScale#944]
With dark themes, black fonts are difficult to read on grey backgrounds. In broad daylight, it becomes practically impossible. 

![image](https://user-images.githubusercontent.com/16408198/225971861-c3e440e5-90ed-4732-91ea-2cb74c243dc8.png)

**Comment by alpapan** [comment]
Yes. It's also almost impossible to set the person's bday when you first install the app and use it.

Took me a couple of minutes to even realise there was supposed to be a button and almost gave up.
 
![Screenshot_20230425-134128](https://user-images.githubusercontent.com/608484/234169309-bbb6da73-5881-4e4f-b54f-1b9e7635cb20.png)

**Comment by oliexdev** [comment]
Yeah I currently changing the Android theme to the new Material 3 but I still have some troubles. Any help are welcome. The first screenshot should be fixed in the dev version the second currently not.

**Comment by oliexdev** [comment]
should be fixed.
