### ISSUE TITLE
fitage scale unexpected error occured; app renpho connects with scale

### ISSUE THREAD

**Issue by evdhoek** [oliexdev/openScale#946]
Errormessage after OpenScale crashes:  "unexpected error" Pls create a new issue.
Scale in use is a Fitage scale. Bluetooth states it is a QN Scale. On the scale itself the connected led is not visible.

**To Reproduce**
1. Go to Overview
2. Click on "Bluetooth"
App crashes
4. Shown Error "unexpected error" Pls create a new issue.

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/dev-build): v2.5.1 (63)

"unexpected error" Pls create a new issue.

**Additional contex
App Renpho (com.qingniu.renpho) can be connected with the scale and shows 13 measurement items.

None.

**Debug log**
Attach a debug log (see Settin

[btsnoop_hci.log](https://github.com/oliexdev/openScale/files/11129080/btsnoop_hci.log)

**Comment by oliexdev** [comment]
sorry this scale is not supported.
