### ISSUE TITLE
Feature Request: Additional Fields to Support Bioelectrical Impedance Values from Full Body Scan Scales

### ISSUE THREAD

**Issue by mauricecyril** [oliexdev/openScale#948]
Feature request to please add support for full body scan scales (ie. ones that have 8 sensors [4 at the feet, 4 at the hands holding a sensor bar at 45%]).

These scales seem to capture the following impedance values:

Bioelectrical Impedance:
- Right Arm 20(kHz)
- Right Arm 100(kHz)
- Left Arm 20(kHz)
- Left Arm 100(kHz)
- Trunk 20(kHz)
- Trunk 100(kHz)
- Right Leg 20(kHz)
- Right Leg 100(kHz)
- Left Leg 20(kHz)
- Left Leg 100(kHz)

Which then allows the following additional metrics to be captured.

Weight which can be broken down into the following sub categories:
- Body Fat
- Inorganic Salt
- Protein
- Body Water
- Muscle
- Skeletal Muscle

Segmented Fat Analysis:
- Right Arm kg
- Right Arm %
- Left Arm kg
- Left Arm %
- Trunk kg
- Trunk %
- Right Leg kg
- Right Leg %
- Left Leg kg
- Left Leg %

Muscle Balance:
- Right Arm kg
- Right Arm %
- Left Arm kg
- Left Arm %
- Trunk kg
- Trunk %
- Right Leg kg
- Right Leg %
- Left Leg kg
- Left Leg %

Other Indicators:
- Visceral Fat Grade
- Basal Metabolic Rate (BMR)
- Fat-Free Body Weight
- Subcutaneous Fat
- SMI

**Comment by oliexdev** [comment]
see #4
