### ISSUE TITLE
`adb backup` fails with "Package com.health.openscale is not eligible for backup, removing"

### ISSUE THREAD

**Issue by nxxxse** [oliexdev/openScale#951]
**Describe the bug**

https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/AndroidManifest.xml allows adb backups (keywords: Google backup, seedvault) but `adb backup` fails for some reason.

 I am aware of the backup mechanism that is integrated in openScale. I still would like to use the Android standard way of doing backups work with openScale.

**To Reproduce**
1. Run `adb backup -keyvalue -f com.health.openscale.ab com.health.openscale` on computer
2. Run `adb logcat -v year,uid,color -s 'BackupManagerService'`

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/dev-build): Yes. It works with the debug built!

**Expected behavior**

App data is backed up.

**Additional context**

Observed on Android 12 and 13. I even uninstalled openScale on Android 13 and created a fresh profile of openScale. Same issue.

**Debug log**

```
2023-04-10 23:27:50.015  1000  1352  6511 I BackupManagerService: Package com.health.openscale is not eligible for backup, removing
```

**Comment by oliexdev** [comment]
Android change the behavior of adb backup see https://developer.android.com/about/versions/12/behavior-changes-12#adb-backup-restrictions
