### ISSUE TITLE
Beurer BF720 wrong BMI data

### ISSUE THREAD

**Issue by githubbapoopa** [oliexdev/openScale#956]
Beurer BF720 shows the wrong BMI data.

Instead of the BMI values the weight values are displayed.

for example

real data: weight 80kg, BMI 24
data in openscale weight 80kg, BMI 80

Instead of the correct BMI data the weight ist "doubled".

Reproduced with 2.5.1

2.4.6 works fine btw

**Comment by oliexdev** [comment]
please double check your height in openScale.

openScale use the following simple formula for the BMI:

> return weight / ((body_height / 100.0f)*(body_height / 100.0f));
