### ISSUE TITLE
Add alarm to bathroom weighing scales

### ISSUE THREAD

**Issue by cathal9** [oliexdev/openScale#964]
Hi, I am looking to buy a bathroom weighing scales  The specific features I will need are as follows. i) it needs to have no weight numbers visible (I assume I can achieve this by putting a cover over any scales)  ii) I need to be able to add an alarm to each weighing scales at a predetermined weight To give you a bit of background I am setting up a weight loss business and one of the features is that there is no numbers on the scales. Initially I will add an alarm to each scale to be triggered by the patients starting  weight. 
To find out each week  if they have lost weight. They will put on a stomach pouch and keep adding one lbs weights (to the pouch) until the alarm goes off (thus the number of lbs in the pouch is the amount of weight they have lost to date)...so in theory each week (when they weigh themselves) they should be adding more and more each week until the alarm goes off.

**Comment by oliexdev** [comment]
and what is your question? If you want to create your own bathroom scale you can read https://github.com/oliexdev/openScale/wiki/Custom-Bluetooth-Scale
Maybe its inspired you.
