### ISSUE TITLE
Medisana BS444 not showing up in BLE scanner

### ISSUE THREAD

**Issue by wasbeer** [oliexdev/openScale#97]
Hi,

my Medisana BS444 scale does not show up in the built-in BLE scanner. Is this normal? 

It also doesn't show up in the third party BLE scanner app. I did not register the scale yet with Vitadock.

Is it still necessary to add the MAC to the class, or does the BLE scanner cover this part?

**Comment by oliexdev** [comment]
No you don't have to add a MAC address the built-in BLE scanner in openScale search for your device name. 
When your scale is on your device should be found by a BLE scanner normally.
Does it work with the original app? Maybe you bought a faulty scale.

**Comment by oliexdev** [comment]
I will close this issue. Comment here if you have any further questions.
