### ISSUE TITLE
looks like this page is incomplete

### ISSUE THREAD

**Issue by cinghialino** [oliexdev/openScale#974]
The page https://github.com/oliexdev/openScale/wiki/Supported-scales-in-openScale

has several images of various scales at the bottom but many have no link.
Can we have additional information on this? 
what is the meaning of having images of verious scales with no additional info? I'm sorry it's bugging me more than it should. 

Are there any plans to fully support the FitIndex ES-26M?

thanks

**Comment by oliexdev** [comment]
feel free to add additional info and to fully support FitINdex ES-26M :)
