### ISSUE TITLE
Support for Health Connect API Platform

### ISSUE THREAD

**Issue by diamant-x** [oliexdev/openScale#979]
**Is your feature request related to a problem? Please describe.**
Health Connect is an Android platform that allows health and fitness apps to use the same on-device data, within a unified ecosystem.

For Android developers, it provides an API for reading and writing a user's on-device health and fitness data.
For Android users, it offers a place to exercise control over which apps have read and or write access to their health and fitness data.

**Describe the solution you'd like**
Health Connect provides on-device storage. Our goal is to create a system that puts users fully in control of their data, as well as which apps and services they share it with.

**Describe alternatives you've considered**
Using other softwares. This one will be the de-facto API for health data in Android. Also, it will help for the developer to be Ok in terms of data privacy and regulation regarding health data exchange in the future.

**Additional context**
https://developer.android.com/guide/health-and-fitness/health-connect

**Comment by QuentinLemCode** [comment]
Duplicate https://github.com/oliexdev/openScale/issues/891
