### ISSUE TITLE
Add Muscle mass

### ISSUE THREAD

**Issue by fabads** [oliexdev/openScale#98]
Hello,

My scale displays a muscle mass instead of Muscle %.
Would it be possible to include this feature or a toggle in the settings to allow selection of % or mass ?

Thx for this great app!

Fabrice

**Comment by oliexdev** [comment]
see #59

**Comment by fabads** [comment]
Not sure to understand the answer. As the other user my scale gives a mass
instead of percents.

**Comment by oliexdev** [comment]
like in #59 described currently I am not quite sure how to best implement it.
