### ISSUE TITLE
UI: dark mode: Settings > Users > Edit Birthday Cancel and OK use wrong font color

### ISSUE THREAD

**Issue by foss-** [oliexdev/openScale#980]
Android 13.1
OpenScale 2.5.2

**Describe the bug**
Wrong color for action buttons in user settings.

**To Reproduce**
1. open Settings > Users > Add user
2. Edit Birthday
3. look at Cancel and OK buttons using black font color on dark background.

**Expected behavior**
Font should use white color.

**Additional context**
<img src="https://github.com/oliexdev/openScale/assets/5708172/e5cd1a85-b722-45e6-a494-b610a44b9344" width="300">

**Comment by oliexdev** [comment]
should be fixed now with the latest commit https://github.com/oliexdev/openScale/commit/8b4326687c91d33f496a0f37dc5fc7e14388aca9
