### ISSUE TITLE
Custom time-range (Last X days)

### ISSUE THREAD

**Issue by buerviper** [oliexdev/openScale#988]
**Is your feature request related to a problem? Please describe.**
I can set my statistics to pre-defined time-ranges (all days, last 7 days, last 30 days, since a specific day, or a specific range in the past). 

**Describe the solution you'd like**
I would like to set also a custom time-range (like past 60 days) instead of setting a reference day in the past.

**Describe alternatives you've considered**
I could change the reference day every other week, but this seems like unnecessary work.

**Comment by oliexdev** [comment]
I think the time ranges are more than enough.
