### ISSUE TITLE
Custom measurement fields - useful for meta information

### ISSUE THREAD

**Issue by PellelNitram** [oliexdev/openScale#997]
_First off, I love the openScale app!!_

**Is your feature request related to a problem? Please describe.**

Sometimes I weigh myself on different scales or with different clothes on. I would like to keep track of this meta information next to the actual measurements.

This additional meta information would be useful for statistical analyses of the data down the road.

**Describe the solution you'd like**

In the settings, one can already pick many different measurements like e.g. the mandatory weight but also body fat or muscle mass or BMI and many others.

Would it be possible to add the possibility here to add custom meta information that I can name myself? That would solve my initial problem as I could then add fields to store the name or ID of the scale that I use or note a comment about what I wore.

**Describe alternatives you've considered**

So far, I am using the comments field to store this information using semi colons to imitate additional measurement dimensions.

**Conclusion**

What do you think? Is this is a realistic feature or too niche? :-)

Again, thanks so much @oliexdev for the creation of openScale!!

**Comment by oliexdev** [comment]
We had this request several time, please see my answer in the other issue. In short it would be awesome but it is a hell to implement that.
