### ISSUE TITLE
move measurement to another user

### ISSUE THREAD

**Issue by FransM** [oliexdev/openScale#999]
**Is your feature request related to a problem? Please describe.**
I like to be able to move a measurement from one user to another user, because somehow a measurement ended up at the wrong user. I can edit the measurement but not move it to a different user.

Note: the reason for the move was that smart user recognition assigned to the wrong user.

**Describe the solution you'd like**
A way to move the measurement to another user (e.g. using the edit measurement form)

**Describe alternatives you've considered**
Didn't find any.

**Comment by SteffenCH** [comment]
Plus one to this! I'm looking for this feature also.

Two people who almost weigh the same, will often get mixed up by the auto detection

**Comment by oliexdev** [comment]
@FransM enable in the settings->measurements the "user" , then you can also edit the user assignment
@SteffenCH that's why you can disable the auto detection mode in the settings. It doesn't work as you describe if two people have almost the same weight.
